/* dbo.ROLLER only: normalize ROL_KODU/ROL_ADI + add missing platform roles */
IF OBJECT_ID(N'dbo.ROLLER', N'U') IS NULL RETURN;

BEGIN TRAN;

IF OBJECT_ID('tempdb..#role_seed') IS NOT NULL DROP TABLE #role_seed;
CREATE TABLE #role_seed
(
    legacy_kod nvarchar(30) NULL,
    rol_kodu nvarchar(30) NOT NULL,
    rol_adi nvarchar(50) NOT NULL,
    departman nvarchar(50) NOT NULL,
    seviye tinyint NOT NULL,
    varsayilan_mi bit NOT NULL,
    aciklama nvarchar(255) NULL
);

INSERT INTO #role_seed (legacy_kod, rol_kodu, rol_adi, departman, seviye, varsayilan_mi, aciklama) VALUES
(N'super_admin',N'SUPER_ADMIN',N'SUPER ADMIN',N'ADMIN',99,0,N'FULL PLATFORM AUTHORITY'),
(N'genel_mudur',N'GENERAL_MANAGER',N'GENERAL MANAGER',N'ADMIN',95,0,N'EXECUTIVE OVERSIGHT'),
(N'genel_mudur_yardimcisi',N'DEPUTY_GENERAL_MANAGER',N'DEPUTY GENERAL MANAGER',N'ADMIN',90,0,N'EXECUTIVE DELEGATED AUTHORITY'),
(N'finans_direktoru',N'FINANCE_DIRECTOR',N'FINANCE DIRECTOR',N'FINANCE',85,0,N'FINANCIAL GOVERNANCE'),
(N'finans_yoneticisi',N'FINANCE_MANAGER',N'FINANCE MANAGER',N'FINANCE',80,0,N'PAYMENT AND REFUND CONTROL'),
(N'muhasebe_sefi',N'ACCOUNTING_LEAD',N'ACCOUNTING LEAD',N'FINANCE',75,0,N'ACCOUNTING LEAD'),
(N'muhasebe_uzmani',N'ACCOUNTING_SPECIALIST',N'ACCOUNTING SPECIALIST',N'FINANCE',70,0,N'INVOICE AND RECONCILIATION'),
(N'muhasebe_yardimcisi',N'ACCOUNTING_ASSISTANT',N'ACCOUNTING ASSISTANT',N'FINANCE',65,0,N'ACCOUNTING SUPPORT'),
(N'finansal_raporlama_uzmani',N'FINANCIAL_REPORTING_SPECIALIST',N'FINANCIAL REPORTING SPECIALIST',N'FINANCE',72,0,N'ADVANCED FINANCIAL REPORTING'),
(N'operasyon_direktoru',N'OPERATIONS_DIRECTOR',N'OPERATIONS DIRECTOR',N'OPERATIONS',80,0,N'OPERATIONS LEAD'),
(N'operasyon_yoneticisi',N'OPERATIONS_MANAGER',N'OPERATIONS MANAGER',N'OPERATIONS',75,0,N'DAILY OPERATIONS MANAGEMENT'),
(N'otel_iliskileri_yoneticisi',N'HOTEL_RELATIONS_MANAGER',N'HOTEL RELATIONS MANAGER',N'OPERATIONS',72,0,N'PARTNER HOTEL MANAGEMENT'),
(N'otel_iliskileri_uzmani',N'HOTEL_RELATIONS_SPECIALIST',N'HOTEL RELATIONS SPECIALIST',N'OPERATIONS',68,0,N'PARTNER HOTEL SUPPORT'),
(N'icerik_yoneticisi',N'CONTENT_MANAGER',N'CONTENT MANAGER',N'OPERATIONS',65,0,N'CONTENT OWNERSHIP'),
(N'icerik_editoru',N'CONTENT_EDITOR',N'CONTENT EDITOR',N'OPERATIONS',60,0,N'CONTENT EDITING'),
(N'fotograf_onay_sorumlusu',N'PHOTO_QA_SPECIALIST',N'PHOTO QA SPECIALIST',N'OPERATIONS',60,0,N'IMAGE QUALITY CONTROL'),
(N'extranet_destek_uzmani',N'EXTRANET_SUPPORT_SPECIALIST',N'EXTRANET SUPPORT SPECIALIST',N'OPERATIONS',62,0,N'PARTNER EXTRANET SUPPORT'),
(N'destek_direktoru',N'SUPPORT_DIRECTOR',N'SUPPORT DIRECTOR',N'SUPPORT',75,0,N'SUPPORT OPERATIONS LEADERSHIP'),
(N'destek_yoneticisi',N'SUPPORT_MANAGER',N'SUPPORT MANAGER',N'SUPPORT',70,0,N'SUPPORT TEAM MANAGEMENT'),
(N'kdemli_destek_uzmani',N'SENIOR_SUPPORT_SPECIALIST',N'SENIOR SUPPORT SPECIALIST',N'SUPPORT',60,0,N'ADVANCED SUPPORT'),
(N'destek_uzmani',N'SUPPORT_SPECIALIST',N'SUPPORT SPECIALIST',N'SUPPORT',50,0,N'CUSTOMER SUPPORT'),
(N'destek_asistani',N'SUPPORT_ASSISTANT',N'SUPPORT ASSISTANT',N'SUPPORT',45,0,N'ENTRY LEVEL SUPPORT'),
(N'sosyal_medya_destek',N'SOCIAL_SUPPORT_SPECIALIST',N'SOCIAL MEDIA SUPPORT SPECIALIST',N'SUPPORT',48,0,N'SOCIAL SUPPORT CHANNELS'),
(N'iade_ve_anlasmazlik_uzmani',N'REFUND_DISPUTE_SPECIALIST',N'REFUND DISPUTE SPECIALIST',N'SUPPORT',65,0,N'REFUND AND DISPUTE'),
(N'cto',N'CTO',N'CTO',N'IT',95,0,N'TECHNOLOGY STRATEGY'),
(N'teknik_lider',N'TECH_LEAD',N'TECH LEAD',N'IT',85,0,N'ENGINEERING LEADERSHIP'),
(N'kidemli_yazilimci',N'SENIOR_SOFTWARE_ENGINEER',N'SENIOR SOFTWARE ENGINEER',N'IT',80,0,N'SENIOR ENGINEERING'),
(N'yazilim_uzmani',N'SOFTWARE_ENGINEER',N'SOFTWARE ENGINEER',N'IT',70,0,N'APPLICATION DEVELOPMENT'),
(N'stajyer_yazilimci',N'JUNIOR_SOFTWARE_ENGINEER',N'JUNIOR SOFTWARE ENGINEER',N'IT',40,0,N'JUNIOR ENGINEERING'),
(N'sistem_yoneticisi',N'SYSTEM_ADMINISTRATOR',N'SYSTEM ADMINISTRATOR',N'IT',85,0,N'INFRASTRUCTURE OPERATIONS'),
(N'veritabani_yoneticisi',N'DATABASE_ADMINISTRATOR',N'DATABASE ADMINISTRATOR',N'IT',88,0,N'DATABASE ADMINISTRATION'),
(N'devops_muhendisi',N'DEVOPS_ENGINEER',N'DEVOPS ENGINEER',N'IT',82,0,N'CI CD AND RELEASE ENGINEERING'),
(N'guvenlik_uzmani',N'CYBER_SECURITY_SPECIALIST',N'CYBER SECURITY SPECIALIST',N'IT',90,0,N'PLATFORM SECURITY'),
(N'test_muhendisi',N'QA_ENGINEER',N'QA ENGINEER',N'IT',65,0,N'QUALITY ASSURANCE'),
(N'hukuk_direktoru',N'LEGAL_DIRECTOR',N'LEGAL DIRECTOR',N'LEGAL',90,0,N'LEGAL STRATEGY'),
(N'hukuk_musaviri',N'LEGAL_COUNSEL',N'LEGAL COUNSEL',N'LEGAL',85,0,N'CONTRACTS AND DISPUTES'),
(N'veri_koruma_gorevlisi',N'DATA_PROTECTION_OFFICER',N'DATA PROTECTION OFFICER',N'LEGAL',88,0,N'DATA PROTECTION COMPLIANCE'),
(N'uyumluluk_uzmani',N'COMPLIANCE_SPECIALIST',N'COMPLIANCE SPECIALIST',N'LEGAL',80,0,N'REGULATORY COMPLIANCE'),
(N'ik_direktoru',N'HR_DIRECTOR',N'HR DIRECTOR',N'HR',80,0,N'HUMAN RESOURCES LEAD'),
(N'ik_yoneticisi',N'HR_MANAGER',N'HR MANAGER',N'HR',75,0,N'HR OPERATIONS'),
(N'ik_uzmani',N'HR_SPECIALIST',N'HR SPECIALIST',N'HR',70,0,N'HR SPECIALIST'),
(N'egitim_koordinatoru',N'TRAINING_COORDINATOR',N'TRAINING COORDINATOR',N'HR',68,0,N'LEARNING AND DEVELOPMENT'),
(N'satis_yoneticisi',N'SALES_MANAGER',N'SALES MANAGER',N'SALES',75,0,N'SALES TEAM MANAGEMENT'),
(N'pazarlama_yoneticisi',N'MARKETING_MANAGER',N'MARKETING MANAGER',N'MARKETING',75,0,N'CAMPAIGN MANAGEMENT'),
(N'developer',N'DEVELOPER',N'DEVELOPER',N'IT',72,0,N'DEVELOPMENT REQUEST ROLE'),
(NULL,N'PLATFORM_ADMIN',N'PLATFORM ADMIN',N'ADMIN',96,0,N'CENTRAL ADMIN OPERATIONS'),
(NULL,N'ADMIN',N'ADMIN',N'ADMIN',94,0,N'CORE ADMIN PANEL ACCESS'),
(NULL,N'PARTNER_OWNER',N'PARTNER OWNER',N'PARTNER',78,0,N'PARTNER PRIMARY AUTHORITY'),
(NULL,N'PARTNER_MANAGER',N'PARTNER MANAGER',N'PARTNER',72,0,N'PARTNER MANAGEMENT'),
(NULL,N'PARTNER_STAFF',N'PARTNER STAFF',N'PARTNER',60,0,N'PARTNER OPERATIONAL USER'),
(NULL,N'COMPANY_OWNER',N'COMPANY OWNER',N'COMPANY',74,0,N'CORPORATE PRIMARY AUTHORITY'),
(NULL,N'COMPANY_MANAGER',N'COMPANY MANAGER',N'COMPANY',68,0,N'CORPORATE RESERVATION MANAGEMENT'),
(NULL,N'COMPANY_STAFF',N'COMPANY STAFF',N'COMPANY',56,0,N'CORPORATE BOOKING USER'),
(NULL,N'SALES_AGENT',N'SALES AGENT',N'SALES',62,0,N'PHONE OR INBOUND RESERVATION SALES'),
(NULL,N'ACCOUNTING_AGENT',N'ACCOUNTING AGENT',N'ACCOUNTING',58,0,N'FINANCE OPERATOR ROLE'),
(NULL,N'SUPPORT_AGENT',N'SUPPORT AGENT',N'SUPPORT',52,0,N'SUPPORT OPERATOR ROLE'),
(NULL,N'END_USER',N'END USER',N'CUSTOMER',10,1,N'PLATFORM CUSTOMER ACCOUNT');

UPDATE r
SET
    r.ROL_KODU = s.rol_kodu,
    r.ROL_ADI = s.rol_adi,
    r.DEPARTMAN = s.departman,
    r.SEVIYE = s.seviye,
    r.VARSAYILAN_MI = s.varsayilan_mi,
    r.ACIKLAMA = s.aciklama
FROM dbo.ROLLER r
INNER JOIN #role_seed s
    ON UPPER(REPLACE(REPLACE(LTRIM(RTRIM(r.ROL_KODU)), N' ', N'_'), N'-', N'_')) = s.rol_kodu
    OR (s.legacy_kod IS NOT NULL AND UPPER(REPLACE(REPLACE(LTRIM(RTRIM(r.ROL_KODU)), N' ', N'_'), N'-', N'_')) = UPPER(s.legacy_kod));

INSERT INTO dbo.ROLLER (ROL_KODU, ROL_ADI, DEPARTMAN, SEVIYE, UST_ROL_ID, VARSAYILAN_MI, ACIKLAMA, OLUSTURULMA_TARIHI)
SELECT s.rol_kodu, s.rol_adi, s.departman, s.seviye, NULL, s.varsayilan_mi, s.aciklama, SYSUTCDATETIME()
FROM #role_seed s
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.ROLLER r
    WHERE UPPER(LTRIM(RTRIM(r.ROL_KODU))) = s.rol_kodu
);

UPDATE dbo.ROLLER
SET
    ROL_KODU = UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ROL_KODU,N'Ç',N'C'),N'Ö',N'O'),N'Ş',N'S'),N'İ',N'I'),N'I',N'I'),N'Ü',N'U'),N'Ğ',N'G'),N'ç',N'C'),N'ö',N'O'),N'ş',N'S'),N'ü',N'U'),N'ı',N'I')),
    ROL_ADI  = UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ROL_ADI ,N'Ç',N'C'),N'Ö',N'O'),N'Ş',N'S'),N'İ',N'I'),N'I',N'I'),N'Ü',N'U'),N'Ğ',N'G'),N'ç',N'C'),N'ö',N'O'),N'ş',N'S'),N'ü',N'U'),N'ı',N'I'));

COMMIT TRAN;
