/* dbo.ROLLER only: TURKCE adlandirma (ROL_KODU, ROL_ADI, DEPARTMAN) */
IF OBJECT_ID(N'dbo.ROLLER', N'U') IS NULL RETURN;

BEGIN TRAN;

IF OBJECT_ID('tempdb..#role_tr_seed') IS NOT NULL DROP TABLE #role_tr_seed;
CREATE TABLE #role_tr_seed
(
    legacy_kod nvarchar(30) NULL,
    en_kod nvarchar(30) NULL,
    tr_kod nvarchar(30) NOT NULL,
    tr_ad nvarchar(50) NOT NULL,
    tr_departman nvarchar(50) NOT NULL,
    seviye tinyint NOT NULL,
    varsayilan_mi bit NOT NULL,
    aciklama nvarchar(255) NULL
);

INSERT INTO #role_tr_seed (legacy_kod, en_kod, tr_kod, tr_ad, tr_departman, seviye, varsayilan_mi, aciklama) VALUES
(N'super_admin',N'SUPER_ADMIN',N'SUPER_YONETICI',N'SUPER YONETICI',N'YONETIM',99,0,N'TUM PLATFORM YETKISI'),
(N'genel_mudur',N'GENERAL_MANAGER',N'GENEL_MUDUR',N'GENEL MUDUR',N'YONETIM',95,0,N'UST DUZEY YONETIM'),
(N'genel_mudur_yardimcisi',N'DEPUTY_GENERAL_MANAGER',N'GENEL_MUDUR_YARDIMCISI',N'GENEL MUDUR YARDIMCISI',N'YONETIM',90,0,N'YONETIM DESTEGI'),
(N'finans_direktoru',N'FINANCE_DIRECTOR',N'FINANS_DIREKTORU',N'FINANS DIREKTORU',N'FINANS',85,0,N'FINANS YONETIMI'),
(N'finans_yoneticisi',N'FINANCE_MANAGER',N'FINANS_YONETICISI',N'FINANS YONETICISI',N'FINANS',80,0,N'ODEME VE IADE YONETIMI'),
(N'muhasebe_sefi',N'ACCOUNTING_LEAD',N'MUHASEBE_SEFI',N'MUHASEBE SEFI',N'FINANS',75,0,N'MUHASEBE EKIP YONETIMI'),
(N'muhasebe_uzmani',N'ACCOUNTING_SPECIALIST',N'MUHASEBE_UZMANI',N'MUHASEBE UZMANI',N'FINANS',70,0,N'FATURA VE MUTABAKAT'),
(N'muhasebe_yardimcisi',N'ACCOUNTING_ASSISTANT',N'MUHASEBE_YARDIMCISI',N'MUHASEBE YARDIMCISI',N'FINANS',65,0,N'MUHASEBE DESTEGI'),
(N'finansal_raporlama_uzmani',N'FINANCIAL_REPORTING_SPECIALIST',N'FINANSAL_RAPORLAMA_UZMANI',N'FINANSAL RAPORLAMA UZMANI',N'FINANS',72,0,N'FINANSAL RAPORLAMA'),

(N'operasyon_direktoru',N'OPERATIONS_DIRECTOR',N'OPERASYON_DIREKTORU',N'OPERASYON DIREKTORU',N'OPERASYON',80,0,N'OPERASYON YONETIMI'),
(N'operasyon_yoneticisi',N'OPERATIONS_MANAGER',N'OPERASYON_YONETICISI',N'OPERASYON YONETICISI',N'OPERASYON',75,0,N'GUNLUK OPERASYON'),
(N'otel_iliskileri_yoneticisi',N'HOTEL_RELATIONS_MANAGER',N'OTEL_ILISKILERI_YONETICISI',N'OTEL ILISKILERI YONETICISI',N'OPERASYON',72,0,N'OTEL PARTNER YONETIMI'),
(N'otel_iliskileri_uzmani',N'HOTEL_RELATIONS_SPECIALIST',N'OTEL_ILISKILERI_UZMANI',N'OTEL ILISKILERI UZMANI',N'OPERASYON',68,0,N'OTEL DESTEK VE TAKIP'),
(N'icerik_yoneticisi',N'CONTENT_MANAGER',N'ICERIK_YONETICISI',N'ICERIK YONETICISI',N'OPERASYON',65,0,N'ICERIK YONETIMI'),
(N'icerik_editoru',N'CONTENT_EDITOR',N'ICERIK_EDITORU',N'ICERIK EDITORU',N'OPERASYON',60,0,N'ICERIK DUZENLEME'),
(N'fotograf_onay_sorumlusu',N'PHOTO_QA_SPECIALIST',N'FOTOGRAF_KALITE_UZMANI',N'FOTOGRAF KALITE UZMANI',N'OPERASYON',60,0,N'GORSEL KALITE KONTROL'),
(N'extranet_destek_uzmani',N'EXTRANET_SUPPORT_SPECIALIST',N'EXTRANET_DESTEK_UZMANI',N'EXTRANET DESTEK UZMANI',N'OPERASYON',62,0,N'PARTNER PANEL DESTEGI'),

(N'destek_direktoru',N'SUPPORT_DIRECTOR',N'DESTEK_DIREKTORU',N'DESTEK DIREKTORU',N'DESTEK',75,0,N'DESTEK OPERASYONU YONETIMI'),
(N'destek_yoneticisi',N'SUPPORT_MANAGER',N'DESTEK_YONETICISI',N'DESTEK YONETICISI',N'DESTEK',70,0,N'DESTEK EKIP YONETIMI'),
(N'kdemli_destek_uzmani',N'SENIOR_SUPPORT_SPECIALIST',N'KIDEMLI_DESTEK_UZMANI',N'KIDEMLI DESTEK UZMANI',N'DESTEK',60,0,N'ZORLU VAKA YONETIMI'),
(N'destek_uzmani',N'SUPPORT_SPECIALIST',N'DESTEK_UZMANI',N'DESTEK UZMANI',N'DESTEK',50,0,N'MUSTERI DESTEGI'),
(N'destek_asistani',N'SUPPORT_ASSISTANT',N'DESTEK_ASISTANI',N'DESTEK ASISTANI',N'DESTEK',45,0,N'DESTEK GIRIS SEVIYESI'),
(N'sosyal_medya_destek',N'SOCIAL_SUPPORT_SPECIALIST',N'SOSYAL_MEDYA_DESTEK_UZMANI',N'SOSYAL MEDYA DESTEK UZMANI',N'DESTEK',48,0,N'SOSYAL KANAL DESTEGI'),
(N'iade_ve_anlasmazlik_uzmani',N'REFUND_DISPUTE_SPECIALIST',N'IADE_ANLASMAZLIK_UZMANI',N'IADE ANLASMAZLIK UZMANI',N'DESTEK',65,0,N'IADE VE UYUSMAZLIK YONETIMI'),

(N'cto',N'CTO',N'TEKNOLOJI_DIREKTORU',N'TEKNOLOJI DIREKTORU',N'BILGI_TEKNOLOJILERI',95,0,N'TEKNOLOJI STRATEJISI'),
(N'teknik_lider',N'TECH_LEAD',N'TEKNIK_LIDER',N'TEKNIK LIDER',N'BILGI_TEKNOLOJILERI',85,0,N'YAZILIM TEKNIK YONETIMI'),
(N'kidemli_yazilimci',N'SENIOR_SOFTWARE_ENGINEER',N'KIDEMLI_YAZILIM_MUHENDISI',N'KIDEMLI YAZILIM MUHENDISI',N'BILGI_TEKNOLOJILERI',80,0,N'KIDEMLI GELISTIRME'),
(N'yazilim_uzmani',N'SOFTWARE_ENGINEER',N'YAZILIM_MUHENDISI',N'YAZILIM MUHENDISI',N'BILGI_TEKNOLOJILERI',70,0,N'UYGULAMA GELISTIRME'),
(N'stajyer_yazilimci',N'JUNIOR_SOFTWARE_ENGINEER',N'JUNIOR_YAZILIM_MUHENDISI',N'JUNIOR YAZILIM MUHENDISI',N'BILGI_TEKNOLOJILERI',40,0,N'JUNIOR GELISTIRME'),
(N'sistem_yoneticisi',N'SYSTEM_ADMINISTRATOR',N'SISTEM_YONETICISI',N'SISTEM YONETICISI',N'BILGI_TEKNOLOJILERI',85,0,N'SISTEM VE ALTYAPI YONETIMI'),
(N'veritabani_yoneticisi',N'DATABASE_ADMINISTRATOR',N'VERITABANI_YONETICISI',N'VERITABANI YONETICISI',N'BILGI_TEKNOLOJILERI',88,0,N'VERITABANI YONETIMI'),
(N'devops_muhendisi',N'DEVOPS_ENGINEER',N'DEVOPS_MUHENDISI',N'DEVOPS MUHENDISI',N'BILGI_TEKNOLOJILERI',82,0,N'DEVOPS VE CI CD'),
(N'guvenlik_uzmani',N'CYBER_SECURITY_SPECIALIST',N'SIBER_GUVENLIK_UZMANI',N'SIBER GUVENLIK UZMANI',N'BILGI_TEKNOLOJILERI',90,0,N'SIBER GUVENLIK'),
(N'test_muhendisi',N'QA_ENGINEER',N'TEST_KALITE_MUHENDISI',N'TEST KALITE MUHENDISI',N'BILGI_TEKNOLOJILERI',65,0,N'KALITE VE TEST'),

(N'hukuk_direktoru',N'LEGAL_DIRECTOR',N'HUKUK_DIREKTORU',N'HUKUK DIREKTORU',N'HUKUK',90,0,N'HUKUK STRATEJISI'),
(N'hukuk_musaviri',N'LEGAL_COUNSEL',N'HUKUK_MUSAVIRI',N'HUKUK MUSAVIRI',N'HUKUK',85,0,N'SOZLESME VE UYUSMAZLIK'),
(N'veri_koruma_gorevlisi',N'DATA_PROTECTION_OFFICER',N'VERI_KORUMA_GOREVLISI',N'VERI KORUMA GOREVLISI',N'HUKUK',88,0,N'KVKK GDPR UYUMU'),
(N'uyumluluk_uzmani',N'COMPLIANCE_SPECIALIST',N'UYUMLULUK_UZMANI',N'UYUMLULUK UZMANI',N'HUKUK',80,0,N'MEVZUAT UYUMU'),

(N'ik_direktoru',N'HR_DIRECTOR',N'IK_DIREKTORU',N'IK DIREKTORU',N'INSAN_KAYNAKLARI',80,0,N'INSAN KAYNAKLARI YONETIMI'),
(N'ik_yoneticisi',N'HR_MANAGER',N'IK_YONETICISI',N'IK YONETICISI',N'INSAN_KAYNAKLARI',75,0,N'IK OPERASYON YONETIMI'),
(N'ik_uzmani',N'HR_SPECIALIST',N'IK_UZMANI',N'IK UZMANI',N'INSAN_KAYNAKLARI',70,0,N'IK UZMANLIK SURECLERI'),
(N'egitim_koordinatoru',N'TRAINING_COORDINATOR',N'EGITIM_KOORDINATORU',N'EGITIM KOORDINATORU',N'INSAN_KAYNAKLARI',68,0,N'EGITIM VE GELISIM'),

(N'satis_yoneticisi',N'SALES_MANAGER',N'SATIS_YONETICISI',N'SATIS YONETICISI',N'SATIS',75,0,N'SATIS EKIP YONETIMI'),
(NULL,N'SALES_AGENT',N'SATIS_TEMSILCISI',N'SATIS TEMSILCISI',N'SATIS',62,0,N'SATIS OPERASYONU'),
(N'pazarlama_yoneticisi',N'MARKETING_MANAGER',N'PAZARLAMA_YONETICISI',N'PAZARLAMA YONETICISI',N'PAZARLAMA',75,0,N'PAZARLAMA VE KAMPANYA'),

(NULL,N'PLATFORM_ADMIN',N'PLATFORM_YONETICISI',N'PLATFORM YONETICISI',N'YONETIM',96,0,N'PLATFORM MERKEZI YONETIM'),
(NULL,N'ADMIN',N'YONETICI',N'YONETICI',N'YONETIM',94,0,N'ADMIN PANEL YETKISI'),

(NULL,N'PARTNER_OWNER',N'PARTNER_SAHIBI',N'PARTNER SAHIBI',N'PARTNER',78,0,N'PARTNER HESAP ANA YETKILI'),
(NULL,N'PARTNER_MANAGER',N'PARTNER_YONETICISI',N'PARTNER YONETICISI',N'PARTNER',72,0,N'PARTNER YONETIM ROLU'),
(NULL,N'PARTNER_STAFF',N'PARTNER_PERSONELI',N'PARTNER PERSONELI',N'PARTNER',60,0,N'PARTNER OPERASYON KULLANICISI'),

(NULL,N'COMPANY_OWNER',N'FIRMA_SAHIBI',N'FIRMA SAHIBI',N'FIRMA',74,0,N'FIRMA HESAP ANA YETKILI'),
(NULL,N'COMPANY_MANAGER',N'FIRMA_YONETICISI',N'FIRMA YONETICISI',N'FIRMA',68,0,N'FIRMA REZERVASYON YONETIMI'),
(NULL,N'COMPANY_STAFF',N'FIRMA_PERSONELI',N'FIRMA PERSONELI',N'FIRMA',56,0,N'FIRMA KULLANICI ROLU'),

(NULL,N'ACCOUNTING_AGENT',N'MUHASEBE_TEMSILCISI',N'MUHASEBE TEMSILCISI',N'FINANS',58,0,N'MUHASEBE OPERASYON ROLU'),
(NULL,N'SUPPORT_AGENT',N'DESTEK_TEMSILCISI',N'DESTEK TEMSILCISI',N'DESTEK',52,0,N'DESTEK OPERASYON ROLU'),
(N'developer',N'DEVELOPER',N'GELISTIRICI',N'GELISTIRICI',N'BILGI_TEKNOLOJILERI',72,0,N'GELISTIRME TALEBI ROLU'),
(NULL,N'END_USER',N'SON_KULLANICI',N'SON KULLANICI',N'MUSTERI',10,1,N'PLATFORM SON KULLANICI HESABI');

UPDATE r
SET
    r.ROL_KODU = s.tr_kod,
    r.ROL_ADI = s.tr_ad,
    r.DEPARTMAN = s.tr_departman,
    r.SEVIYE = s.seviye,
    r.VARSAYILAN_MI = s.varsayilan_mi,
    r.ACIKLAMA = s.aciklama
FROM dbo.ROLLER r
INNER JOIN #role_tr_seed s
    ON UPPER(REPLACE(REPLACE(LTRIM(RTRIM(r.ROL_KODU)), N' ', N'_'), N'-', N'_')) = UPPER(s.tr_kod)
    OR (s.en_kod IS NOT NULL AND UPPER(REPLACE(REPLACE(LTRIM(RTRIM(r.ROL_KODU)), N' ', N'_'), N'-', N'_')) = UPPER(s.en_kod))
    OR (s.legacy_kod IS NOT NULL AND UPPER(REPLACE(REPLACE(LTRIM(RTRIM(r.ROL_KODU)), N' ', N'_'), N'-', N'_')) = UPPER(s.legacy_kod));

INSERT INTO dbo.ROLLER (ROL_KODU, ROL_ADI, DEPARTMAN, SEVIYE, UST_ROL_ID, VARSAYILAN_MI, ACIKLAMA, OLUSTURULMA_TARIHI)
SELECT s.tr_kod, s.tr_ad, s.tr_departman, s.seviye, NULL, s.varsayilan_mi, s.aciklama, SYSUTCDATETIME()
FROM #role_tr_seed s
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.ROLLER r
    WHERE UPPER(LTRIM(RTRIM(r.ROL_KODU))) = UPPER(s.tr_kod)
);

COMMIT TRAN;
