-- Tablo: dbo.SEMA_MIGRASYONLARI
-- Migration gecmisi tablosu
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'dbo.SEMA_MIGRASYONLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[SEMA_MIGRASYONLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [BETIK_ADI] nvarchar(260) NOT NULL,
        [KONTROL_TOPLAMI] char(64) NOT NULL,
        [UYGULANMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_SEMA_MIGRASYONLARI_UYGULANMA] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_SEMA_MIGRASYONLARI] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [UQ_SEMA_MIGRASYONLARI_BETIK_HASH] UNIQUE ([BETIK_ADI], [KONTROL_TOPLAMI])
    );
    CREATE INDEX [IX_SEMA_MIGRASYONLARI_BETIK] ON [dbo].[SEMA_MIGRASYONLARI]([BETIK_ADI]);
END
GO
