-- Tablo: dbo.FATURALAR
IF OBJECT_ID(N'dbo.FATURALAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[FATURALAR] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [FATURA_NO] nvarchar(30) NOT NULL,
        [FATURA_TARIHI] date NOT NULL,
        [FATURA_TURU] nvarchar(255) NOT NULL,
        [REZERVASYON_ID] bigint NULL,
        [OTEL_ID] bigint NULL,
        [KULLANICI_ID] bigint NULL,
        [PARTNER_ID] bigint NULL,
        [FIRMA_ID] bigint NULL,
        [ODEME_ISLEM_ID] bigint NULL,
        [FATURA_KESEN] nvarchar(255) NOT NULL,
        [FATURA_KESEN_UNVAN] nvarchar(200) NOT NULL,
        [FATURA_KESEN_VERGI_DAIRESI] nvarchar(100) NOT NULL,
        [FATURA_KESEN_VERGI_NO] nvarchar(20) NOT NULL,
        [FATURA_KESEN_ADRES] nvarchar(max) NOT NULL,
        [FATURA_ALICI_UNVAN] nvarchar(200) NOT NULL,
        [FATURA_ALICI_VERGI_DAIRESI] nvarchar(100) NULL,
        [FATURA_ALICI_VERGI_NO] nvarchar(20) NULL,
        [FATURA_ALICI_TC_NO] nvarchar(11) NULL,
        [FATURA_ALICI_ADRES] nvarchar(max) NOT NULL,
        [FATURA_ALICI_EPOSTA] nvarchar(100) NULL,
        [ARA_TOPLAM] decimal(10,2) NOT NULL,
        [KDV_ORANI] decimal(5,2) NULL CONSTRAINT [DF__faturalar__kdv_o__2BFE89A6] DEFAULT ((20.00)),
        [KDV_TUTARI] decimal(10,2) NOT NULL,
        [DIGER_VERGILER] decimal(10,2) NULL CONSTRAINT [DF__faturalar__diger__2CF2ADDF] DEFAULT ((0.00)),
        [KONAKLAMA_VERGISI_ORANI] decimal(5,2) NULL CONSTRAINT [DF__faturalar__konak__2DE6D218] DEFAULT ((2.00)),
        [KONAKLAMA_VERGISI_TUTARI] decimal(10,2) NULL CONSTRAINT [DF__faturalar__konak__2EDAF651] DEFAULT ((0.00)),
        [GENEL_TOPLAM] decimal(10,2) NOT NULL,
        [PARA_BIRIMI] nvarchar(3) NULL,
        [YALNIZ_YAZIYLA] nvarchar(500) NULL,
        [E_FATURA_UUID] nvarchar(36) NULL,
        [E_FATURA_DURUMU] nvarchar(255) NULL,
        [E_FATURA_GONDERIM_TARIHI] datetime2(0) NULL,
        [E_FATURA_ONAY_TARIHI] datetime2(0) NULL,
        [E_FATURA_ENTEGRASYON_TURU] nvarchar(255) NULL,
        [ENTEGRATOR_ADI] nvarchar(50) NULL,
        [FATURA_PDF_YOLU] nvarchar(500) NULL,
        [FATURA_HTML_YOLU] nvarchar(500) NULL,
        [FATURA_XML_YOLU] nvarchar(500) NULL,
        [FATURA_DURUMU] nvarchar(255) NULL,
        [IPTAL_NEDENI] nvarchar(500) NULL,
        [IPTAL_TARIHI] datetime2(0) NULL,
        [IPTAL_EDEN_ADMIN_ID] bigint NULL,
        [FATURA_NOTU] nvarchar(max) NULL,
        [SIPARIS_NO] nvarchar(50) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__faturalar__olust__2FCF1A8A] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [VADE_TARIHI] date NULL,
        [ODEME_TARIHI] date NULL,
        CONSTRAINT [PK_FATURALAR] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
