-- Tablo: dbo.FIRMALAR
IF OBJECT_ID(N'dbo.FIRMALAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[FIRMALAR] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [FIRMA_KODU] nvarchar(32) NOT NULL,
        [FIRMA_ADI] nvarchar(200) NOT NULL,
        [FIRMA_TURU] nvarchar(255) NOT NULL,
        [VERGI_NO] nvarchar(20) NOT NULL,
        [VERGI_DAIRESI] nvarchar(100) NULL,
        [TICARET_SICIL_NO] nvarchar(50) NULL,
        [MERSIS_NO] nvarchar(32) NULL,
        [FIRMA_EPOSTA] nvarchar(100) NULL,
        [FIRMA_TELEFON] nvarchar(20) NULL,
        [WEB_SITESI] nvarchar(255) NULL,
        [LOGO_YOLU] nvarchar(255) NULL,
        [SEKTOR] nvarchar(100) NULL,
        [CALISAN_SAYISI] int NULL CONSTRAINT [DF__firmalar__calisa__40058253] DEFAULT ((0)),
        [AYLIK_SEYAHAT_BUTCESI] decimal(12,2) NULL,
        [VARSAYILAN_PARA_BIRIMI] nvarchar(3) NOT NULL,
        [ACIK_ADRES] nvarchar(max) NULL,
        [SEHIR] nvarchar(100) NULL,
        [ILCE] nvarchar(100) NULL,
        [POSTA_KODU] nvarchar(10) NULL,
        [YETKILI_AD_SOYAD] nvarchar(100) NULL,
        [YETKILI_UNVANI] nvarchar(100) NULL,
        [YETKILI_EPOSTA] nvarchar(100) NULL,
        [YETKILI_TELEFON] nvarchar(20) NULL,
        [ONAY_DURUMU] nvarchar(255) NOT NULL,
        [BASVURU_TARIHI] datetime2(0) NULL CONSTRAINT [DF__firmalar__basvur__40F9A68C] DEFAULT (sysutcdatetime()),
        [ONAY_SURECI_BASLAMA_TARIHI] datetime2(0) NULL,
        [ONAY_TARIHI] datetime2(0) NULL,
        [REDDEDILME_TARIHI] datetime2(0) NULL,
        [ONAYLAYAN_KULLANICI_ID] bigint NULL,
        [ONAY_NOTU] nvarchar(max) NULL,
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF__firmalar__aktif___41EDCAC5] DEFAULT ((1)),
        [GIRIS_IZNI_AKTIF_MI] bit NOT NULL CONSTRAINT [DF__firmalar__giris___42E1EEFE] DEFAULT ((0)),
        [PLANLANAN_ONAY_SURESI_SAAT] smallint NOT NULL CONSTRAINT [DF__firmalar__planla__43D61337] DEFAULT ((24)),
        [KAYIT_KAYNAGI] nvarchar(50) NOT NULL,
        [SOZLESME_ONAY_TARIHI] datetime2(0) NULL,
        [KVKK_ONAY_TARIHI] datetime2(0) NULL,
        [NOTLAR] nvarchar(max) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__firmalar__olustu__44CA3770] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_FIRMALAR] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
