-- Tablo: dbo.GUVENLI_DOSYA_ERISIM_TOKENLARI
IF OBJECT_ID(N'dbo.GUVENLI_DOSYA_ERISIM_TOKENLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[GUVENLI_DOSYA_ERISIM_TOKENLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [GUVENLI_DOSYA_ID] bigint NOT NULL,
        [ERISIM_TOKENI] nvarchar(64) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [HESAP_TIPI] nvarchar(30) NOT NULL,
        [KULLANIM_SAYISI] int NOT NULL CONSTRAINT [DF__guvenli_d__kulla__47A6A41B] DEFAULT ((0)),
        [MAKSIMUM_KULLANIM_SAYISI] int NULL,
        [GECERLILIK_TARIHI] datetime2(0) NOT NULL,
        [SON_ERISIM_TARIHI] datetime2(0) NULL,
        [IPTAL_TARIHI] datetime2(0) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__guvenli_d__olust__489AC854] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_GUVENLI_DOSYA_ERISIM_TOKENLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
