-- Tablo: dbo.KAMPANYALAR
IF OBJECT_ID(N'dbo.KAMPANYALAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KAMPANYALAR] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KAMPANYA_KODU] nvarchar(50) NOT NULL,
        [KAMPANYA_ADI] nvarchar(200) NOT NULL,
        [SEO_SLUG] nvarchar(255) NULL,
        [SAYFA_URL] nvarchar(255) NULL,
        [KAMPANYA_ACIKLAMASI] nvarchar(max) NULL,
        [KISA_ACIKLAMA] nvarchar(255) NULL,
        [DETAY_ACIKLAMA] nvarchar(max) NULL,
        [TUR] nvarchar(255) NOT NULL,
        [INDIRIM_ORANI] decimal(5,2) NULL,
        [INDIRIM_TUTARI] decimal(10,2) NULL,
        [MAKSIMUM_INDIRIM_TUTARI] decimal(10,2) NULL,
        [MINIMUM_SEPET_TUTARI] decimal(10,2) NULL,
        [HEDEF_OTEL_TURU] nvarchar(255) NULL,
        [HEDEF_OTEL_IDLERI] nvarchar(max) NULL,
        [HEDEF_SEHIRLER] nvarchar(max) NULL,
        [HEDEF_ILCELER] nvarchar(max) NULL,
        [HEDEF_MAHALLELER] nvarchar(max) NULL,
        [HEDEF_KULLANICI_TURU] nvarchar(255) NULL,
        [MINIMUM_GECMIS_REZERVASYON] tinyint NULL,
        [BASLANGIC_TARIHI] datetime2(0) NOT NULL,
        [BITIS_TARIHI] datetime2(0) NOT NULL,
        [REZERVASYON_TARIH_ARALIGI_BASLANGIC] date NULL,
        [REZERVASYON_TARIH_ARALIGI_BITIS] date NULL,
        [KONAKLAMA_TARIH_ARALIGI_BASLANGIC] date NULL,
        [KONAKLAMA_TARIH_ARALIGI_BITIS] date NULL,
        [MINIMUM_GECELEME] tinyint NULL CONSTRAINT [DF__kampanyal__minim__55F4C372] DEFAULT ((1)),
        [MAKSIMUM_GECELEME] smallint NULL,
        [ERKEN_REZERVASYON_GUN_SAYISI] smallint NULL,
        [TOPLAM_KULLANIM_LIMITI] int NULL,
        [KULLANICI_BASINA_LIMIT] tinyint NULL CONSTRAINT [DF__kampanyal__kulla__56E8E7AB] DEFAULT ((1)),
        [KULLANILAN_ADET] int NULL CONSTRAINT [DF__kampanyal__kulla__57DD0BE4] DEFAULT ((0)),
        [GOSTERIM_ADEDI] int NOT NULL CONSTRAINT [DF__kampanyal__goste__58D1301D] DEFAULT ((0)),
        [AKTIF_MI] bit NULL CONSTRAINT [DF__kampanyal__aktif__59C55456] DEFAULT ((1)),
        [GORUNURLUK_DURUMU] nvarchar(255) NOT NULL,
        [PARTNER_KATILIM_ACIK] bit NOT NULL CONSTRAINT [DF__kampanyal__partn__5AB9788F] DEFAULT ((1)),
        [PARTNER_KATILIM_BASLANGIC] datetime2(0) NULL,
        [PARTNER_KATILIM_BITIS] datetime2(0) NULL,
        [OTOMATIK_SONA_ERSIN] bit NOT NULL CONSTRAINT [DF__kampanyal__otoma__5BAD9CC8] DEFAULT ((1)),
        [ONE_CIKAN_KAMPANYA] bit NULL CONSTRAINT [DF__kampanyal__one_c__5CA1C101] DEFAULT ((0)),
        [SIRALAMA] int NOT NULL CONSTRAINT [DF__kampanyal__siral__5D95E53A] DEFAULT ((0)),
        [AKTIF_SAYFA_VITRINI] bit NOT NULL CONSTRAINT [DF__kampanyal__aktif__5E8A0973] DEFAULT ((0)),
        [BANNER_GORSELI] nvarchar(255) NULL,
        [HERO_GORSELI] nvarchar(500) NULL,
        [KART_GORSELI] nvarchar(500) NULL,
        [MOBIL_GORSEL] nvarchar(500) NULL,
        [META_TITLE] nvarchar(255) NULL,
        [META_DESCRIPTION] nvarchar(500) NULL,
        [CANONICAL_URL] nvarchar(500) NULL,
        [KAMPANYA_ETIKETI] nvarchar(100) NULL,
        [PROMO_BADGE] nvarchar(100) NULL,
        [KAMPANYA_RENK_KODU] nvarchar(20) NULL,
        [LISTELEME_BASLIGI] nvarchar(255) NULL,
        [LISTELEME_ACIKLAMASI] nvarchar(500) NULL,
        [KULLANIM_KOSULLARI] nvarchar(max) NULL,
        [OLUSTURAN_ADMIN_ID] bigint NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__kampanyal__olust__5F7E2DAC] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_KAMPANYALAR] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
