-- Tablo: dbo.KOMISYON_MUHASEBE_KAYITLARI
IF OBJECT_ID(N'dbo.KOMISYON_MUHASEBE_KAYITLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KOMISYON_MUHASEBE_KAYITLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KAYIT_NO] nvarchar(30) NOT NULL,
        [KAYIT_TARIHI] date NOT NULL,
        [DONEM] nvarchar(7) NOT NULL,
        [REZERVASYON_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [PARTNER_ID] bigint NOT NULL,
        [FATURA_ID] bigint NULL,
        [TOPLAM_REZERVASYON_TUTARI] decimal(10,2) NOT NULL,
        [KOMISYON_ORANI] decimal(5,2) NOT NULL,
        [KOMISYON_TUTARI] decimal(10,2) NOT NULL,
        [EK_KESINTILER] decimal(10,2) NULL CONSTRAINT [DF__komisyon___ek_ke__625A9A57] DEFAULT ((0.00)),
        [NET_OTELE_ODENECEK] decimal(10,2) NOT NULL,
        [OTELE_ODEME_DURUMU] nvarchar(255) NULL,
        [OTELE_ODEME_TARIHI] date NULL,
        [OTELE_ODEME_REFERANSI] nvarchar(50) NULL,
        [ODEME_EMRI_NO] nvarchar(30) NULL,
        [MUHASEBE_HESAP_KODU] nvarchar(20) NULL,
        [KARSI_HESAP_KODU] nvarchar(20) NULL,
        [YEVMIYE_NO] nvarchar(20) NULL,
        [FIS_NO] nvarchar(20) NULL,
        [MUTABAKAT_DURUMU] nvarchar(255) NULL,
        [MUTABAKAT_GONDERIM_TARIHI] datetime2(0) NULL,
        [MUTABAKAT_ONAY_TARIHI] datetime2(0) NULL,
        [MUTABAKAT_NOTU] nvarchar(max) NULL,
        [ITIRAZ_VAR_MI] bit NULL CONSTRAINT [DF__komisyon___itira__634EBE90] DEFAULT ((0)),
        [ITIRAZ_NEDENI] nvarchar(500) NULL,
        [ITIRAZ_TARIHI] datetime2(0) NULL,
        [ITIRAZ_COZUM_TARIHI] datetime2(0) NULL,
        [ITIRAZ_COZUM_ACIKLAMASI] nvarchar(max) NULL,
        [DUZELTME_TUTARI] decimal(10,2) NULL,
        [STOPAJ_ORANI] decimal(5,2) NULL CONSTRAINT [DF__komisyon___stopa__6442E2C9] DEFAULT ((0.00)),
        [STOPAJ_TUTARI] decimal(10,2) NULL CONSTRAINT [DF__komisyon___stopa__65370702] DEFAULT ((0.00)),
        [KDV_ORANI] decimal(5,2) NULL CONSTRAINT [DF__komisyon___kdv_o__662B2B3B] DEFAULT ((20.00)),
        [KDV_TUTARI] decimal(10,2) NULL CONSTRAINT [DF__komisyon___kdv_t__671F4F74] DEFAULT ((0.00)),
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__komisyon___olust__681373AD] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [OLUSTURAN_ADMIN_ID] bigint NULL,
        [ONAYLAYAN_FINANS_ADMIN_ID] bigint NULL,
        CONSTRAINT [PK_KOMISYON_MUHASEBE_KAYITLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
