-- Tablo: dbo.KULLANICILAR
IF OBJECT_ID(N'dbo.KULLANICILAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICILAR] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [AD_SOYAD] nvarchar(100) NOT NULL,
        [EPOSTA] nvarchar(100) NOT NULL,
        [TELEFON] nvarchar(20) NULL,
        [TC_KIMLIK_NO] nvarchar(11) NULL,
        [DOGUM_TARIHI] date NULL,
        [CINSIYET] nvarchar(255) NULL,
        [UYRUK] nvarchar(50) NULL,
        [ADRES] nvarchar(max) NULL,
        [SEHIR] nvarchar(100) NULL,
        [ILCE] nvarchar(100) NULL,
        [MAHALLE] nvarchar(120) NULL,
        [POSTA_KODU] nvarchar(10) NULL,
        [TERCIH_EDILEN_ODA_TIPI] nvarchar(50) NULL,
        [YATAK_TERCIHI] nvarchar(50) NULL,
        [KONUSULAN_DILLER] nvarchar(200) NULL,
        [SEYAHAT_AMACI] nvarchar(255) NULL,
        [OZEL_ISTEKLER] nvarchar(max) NULL,
        [IKI_ASAMALI_DOGRULAMA_AKTIF_MI] bit NOT NULL CONSTRAINT [DF__users__iki_asama__4BCC3ABA] DEFAULT ((0)),
        [PROFIL_TAMAMLANMA_TARIHI] datetime2(0) NULL,
        [SIFRE] nvarchar(255) NOT NULL,
        [ROL] nvarchar(64) NOT NULL CONSTRAINT [DF_users_rol] DEFAULT ('user'),
        [SAHIPLIK_PARTNER_ID] bigint NULL,
        [FIRMA_ID] bigint NULL,
        [DEPARTMAN] nvarchar(100) NULL,
        [GOREV_UNVANI] nvarchar(100) NULL,
        [SATIS_EKIBI] nvarchar(100) NULL,
        [GUNLUK_SATIS_HEDEFI] decimal(12,2) NULL,
        [AYLIK_SATIS_HEDEFI] decimal(12,2) NULL,
        [DAHILI_NUMARA] nvarchar(20) NULL,
        [HARCAMA_LIMITI] decimal(10,2) NULL,
        [ONAY_GEREKSINIMI] bit NOT NULL CONSTRAINT [DF__users__onay_gere__4CC05EF3] DEFAULT ((0)),
        [PERSONEL_KODU] nvarchar(30) NULL,
        [FIRMA_YONETICI_MI] bit NOT NULL CONSTRAINT [DF__users__firma_yon__4DB4832C] DEFAULT ((0)),
        [SON_SIRKET_GIRISI_TARIHI] datetime2(0) NULL,
        [PROFIL_FOTOGRAFI] nvarchar(255) NULL,
        [EPOSTA_DOGRULAMA_TARIHI] datetime2(0) NULL,
        [BASARISIZ_GIRIS_SAYISI] smallint NOT NULL CONSTRAINT [DF__users__basarisiz__4EA8A765] DEFAULT ((0)),
        [SON_BASARISIZ_GIRIS_TARIHI] datetime2(0) NULL,
        [GIRIS_KILIT_BITIS_TARIHI] datetime2(0) NULL,
        [EPOSTA_DOGRULAMA_SON_GONDERIM_TARIHI] datetime2(0) NULL,
        [TELEFON_DOGRULAMA_TARIHI] datetime2(0) NULL,
        [KVKK_ONAY_TARIHI] datetime2(0) NULL,
        [PAZARLAMA_IZNI] bit NOT NULL CONSTRAINT [DF__users__pazarlama__4F9CCB9E] DEFAULT ((0)),
        [KAYIT_KAYNAGI] nvarchar(50) NULL,
        [SON_GIRIS_TARIHI] datetime2(0) NULL,
        [SON_GIRIS_IP] nvarchar(45) NULL,
        [HESAP_DURUMU] tinyint NOT NULL CONSTRAINT [DF__users__hesap_dur__5090EFD7] DEFAULT ((1)),
        [DIL_TERCIHI] nvarchar(5) NULL,
        [PARA_BIRIMI] nvarchar(3) NULL,
        [ULKE] nvarchar(50) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__users__olusturul__51851410] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [TELEFON_E164] nvarchar(32) NULL,
        [TELEFON_DOGRULAMA_KANALI] nvarchar(30) NULL,
        [TELEFON_DOGRULAMA_DURUMU] nvarchar(30) NULL,
        [TELEFON_SON_DOGRULAMA_ISTEK_TARIHI] datetime2(7) NULL,
        [TELEFON_SON_SAHIPLIK_TEYIT_TARIHI] datetime2(7) NULL,
        [TELEFON_DEGISTIRILME_TARIHI] datetime2(7) NULL,
        [IKI_ASAMALI_DOGRULAMA_KANALI] nvarchar(20) NULL CONSTRAINT [DF_users_iki_asamali_dogrulama_kanali] DEFAULT (N'email'),
        [PROFIL_RESIM_URL] nvarchar(255) NULL,
        [PROFIL_RESIM_KAYNAK] nvarchar(30) NULL,
        [TERCIH_LOCALE] nvarchar(16) NULL,
        [TERCIH_PARA_BIRIMI] nvarchar(8) NULL,
        [PROFIL_GORSEL_GUVENLI_DOSYA_ID] bigint NULL,
        [IKI_ASAMALI_EPOSTA_AKTIF] bit NOT NULL CONSTRAINT [DF_users_iki_asamali_eposta_aktif] DEFAULT ((0)),
        CONSTRAINT [PK_KULLANICILAR] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
