-- Tablo: dbo.KULLANICI_BILDIRIM_TERCIHLERI
IF OBJECT_ID(N'dbo.KULLANICI_BILDIRIM_TERCIHLERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_BILDIRIM_TERCIHLERI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [REZERVASYON_EPOSTA] bit NOT NULL CONSTRAINT [DF__kullanici__rezer__72910220] DEFAULT ((1)),
        [REZERVASYON_PUSH] bit NOT NULL CONSTRAINT [DF__kullanici__rezer__73852659] DEFAULT ((1)),
        [CHECKIN_HATIRLATMA] bit NOT NULL CONSTRAINT [DF__kullanici__check__74794A92] DEFAULT ((1)),
        [IPTAL_DEGISIM] bit NOT NULL CONSTRAINT [DF__kullanici__iptal__756D6ECB] DEFAULT ((1)),
        [KAMPANYA_EPOSTA] bit NOT NULL CONSTRAINT [DF__kullanici__kampa__76619304] DEFAULT ((0)),
        [KAMPANYA_SMS] bit NOT NULL CONSTRAINT [DF__kullanici__kampa__7755B73D] DEFAULT ((0)),
        [SISTEM_BILDIRIMI] bit NOT NULL CONSTRAINT [DF__kullanici__siste__7849DB76] DEFAULT ((1)),
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__kullanici__olust__793DFFAF] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [GIRIS_EPOSTA] bit NOT NULL CONSTRAINT [DF_kullanici_bildirim_tercihleri_giris_eposta] DEFAULT ((0)),
        CONSTRAINT [PK_KULLANICI_BILDIRIM_TERCIHLERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
