-- Tablo: dbo.KULLANICI_DEPARTMAN
IF OBJECT_ID(N'dbo.KULLANICI_DEPARTMAN', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_DEPARTMAN] (
        [KULLANICI_ID] bigint NOT NULL,
        [DEPARTMAN_ID] smallint NOT NULL,
        [UNVAN] nvarchar(100) NULL,
        [ISE_BASLAMA_TARIHI] date NULL,
        [YONETICI_MI] bit NULL CONSTRAINT [DF__kullanici__yonet__01D345B0] DEFAULT ((0)),
        CONSTRAINT [PK_KULLANICI_DEPARTMAN] PRIMARY KEY CLUSTERED ([KULLANICI_ID], [DEPARTMAN_ID] ASC)
    );
END
