-- Tablo: dbo.KULLANICI_DIJITAL_PASAPORTLARI
IF OBJECT_ID(N'dbo.KULLANICI_DIJITAL_PASAPORTLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_DIJITAL_PASAPORTLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [SEHIR] nvarchar(120) NOT NULL,
        [ULKE] nvarchar(120) NULL,
        [ILK_KONAKLAMA_TARIHI] date NULL,
        [SON_KONAKLAMA_TARIHI] date NULL,
        [TOPLAM_KONAKLAMA_SAYISI] int NOT NULL CONSTRAINT [DF__kullanici__topla__04AFB25B] DEFAULT ((0)),
        [DAMGA_KODU] nvarchar(80) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__kullanici__olust__05A3D694] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__kullanici__gunce__0697FACD] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_KULLANICI_DIJITAL_PASAPORTLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
