-- Tablo: dbo.KULLANICI_FAVORI_FIYAT_ALARMLARI
IF OBJECT_ID(N'dbo.KULLANICI_FAVORI_FIYAT_ALARMLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_FAVORI_FIYAT_ALARMLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [HEDEF_MAKSIMUM_FIYAT] decimal(12,2) NOT NULL,
        [BASLANGIC_TARIHI] date NOT NULL,
        [BITIS_TARIHI] date NOT NULL,
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF__user_favo__aktif__4707859D] DEFAULT ((1)),
        [SON_TETIKLENEN_TARIH] datetime2(0) NULL,
        [SON_TETIKLENEN_FIYAT] decimal(12,2) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__user_favo__olust__47FBA9D6] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__user_favo__gunce__48EFCE0F] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_KULLANICI_FAVORI_FIYAT_ALARMLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
