-- Tablo: dbo.KULLANICI_OTURUM_ISTATISTIKLERI
IF OBJECT_ID(N'dbo.KULLANICI_OTURUM_ISTATISTIKLERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_OTURUM_ISTATISTIKLERI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [HESAP_TIPI] nvarchar(255) NOT NULL,
        [PARTNER_ID] bigint NULL,
        [CIHAZ_ANAHTARI] nvarchar(128) NOT NULL,
        [CIHAZ_ETIKETI] nvarchar(150) NULL,
        [BENI_HATIRLA_TERCIHI] bit NULL CONSTRAINT [DF__kullanici__beni___0E391C95] DEFAULT ((0)),
        [TOPLAM_ZIYARET_SAYISI] int NULL CONSTRAINT [DF__kullanici__topla__0F2D40CE] DEFAULT ((0)),
        [TOPLAM_OTURUM_SURESI_SANIYE] bigint NULL CONSTRAINT [DF__kullanici__topla__10216507] DEFAULT ((0)),
        [SON_OTURUM_BASLANGICI] datetime2(0) NULL,
        [SON_OTURUM_BITISI] datetime2(0) NULL,
        [SON_AKTIVITE_TARIHI] datetime2(0) NULL,
        [SON_IP_HASH] nchar(64) NULL,
        [SON_KULLANICI_ARACISI_HASH] nchar(64) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__kullanici__olust__11158940] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_KULLANICI_OTURUM_ISTATISTIKLERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
