-- Tablo: dbo.KULLANICI_SADAKAT_HESAPLARI
IF OBJECT_ID(N'dbo.KULLANICI_SADAKAT_HESAPLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_SADAKAT_HESAPLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [TOPLAM_PUAN] int NOT NULL CONSTRAINT [DF__kullanici__topla__24285DB4] DEFAULT ((0)),
        [KULLANILABILIR_PUAN] int NOT NULL CONSTRAINT [DF__kullanici__kulla__251C81ED] DEFAULT ((0)),
        [BU_YIL_KAZANILAN_PUAN] int NOT NULL CONSTRAINT [DF__kullanici__bu_yi__2610A626] DEFAULT ((0)),
        [BU_YIL_KULLANILAN_PUAN] int NOT NULL CONSTRAINT [DF__kullanici__bu_yi__2704CA5F] DEFAULT ((0)),
        [MEVCUT_SEVIYE_ID] bigint NULL,
        [SONRAKI_SEVIYE_ID] bigint NULL,
        [SON_SEVIYE_GUNCELLEME_TARIHI] datetime2(0) NULL,
        [PUAN_GECERLILIK_TARIHI] date NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__kullanici__olust__27F8EE98] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__kullanici__gunce__28ED12D1] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_KULLANICI_SADAKAT_HESAPLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
