-- Tablo: dbo.KULLANICI_SEYAHAT_PLAN_OTEL_SECIMLERI
IF OBJECT_ID(N'dbo.KULLANICI_SEYAHAT_PLAN_OTEL_SECIMLERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[KULLANICI_SEYAHAT_PLAN_OTEL_SECIMLERI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [PLAN_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [EKLEYEN_KULLANICI_ID] bigint NOT NULL,
        [OY_PUANI] int NOT NULL CONSTRAINT [DF__kullanici__oy_pu__2BC97F7C] DEFAULT ((0)),
        [NOTLAR] nvarchar(255) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__kullanici__olust__2CBDA3B5] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_KULLANICI_SEYAHAT_PLAN_OTEL_SECIMLERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
