-- Tablo: dbo.ODEME_ISLEMLERI
IF OBJECT_ID(N'dbo.ODEME_ISLEMLERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ODEME_ISLEMLERI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [ISLEM_NO] nvarchar(30) NOT NULL,
        [REZERVASYON_ID] bigint NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [ODEME_TURU] nvarchar(255) NOT NULL,
        [ODEME_YONTEMI] nvarchar(255) NOT NULL,
        [ODEME_DURUMU] nvarchar(255) NULL,
        [TUTAR] decimal(10,2) NOT NULL,
        [KOMISYON_TUTARI] decimal(10,2) NULL CONSTRAINT [DF__odeme_isl__komis__7167D3BD] DEFAULT ((0.00)),
        [VERGI_TUTARI] decimal(10,2) NULL CONSTRAINT [DF__odeme_isl__vergi__725BF7F6] DEFAULT ((0.00)),
        [TOPLAM_TAHSILAT] decimal(10,2) NOT NULL,
        [PARA_BIRIMI] nvarchar(3) NULL,
        [KUR_ORANI] decimal(10,6) NULL CONSTRAINT [DF__odeme_isl__kur_o__73501C2F] DEFAULT ((1.000000)),
        [ORIJINAL_TUTAR] decimal(10,2) NULL,
        [ORIJINAL_PARA_BIRIMI] nvarchar(3) NULL,
        [TAKSIT_SAYISI] tinyint NULL CONSTRAINT [DF__odeme_isl__taksi__74444068] DEFAULT ((1)),
        [TAKSIT_SIRASI] tinyint NULL CONSTRAINT [DF__odeme_isl__taksi__753864A1] DEFAULT ((1)),
        [ANA_ODEME_ID] bigint NULL,
        [KART_SAHIBI_ADI] nvarchar(100) NULL,
        [KART_NUMARASI_MASKED] nvarchar(20) NULL,
        [KART_TIPI] nvarchar(255) NULL,
        [KART_SON_KULLANMA] nvarchar(5) NULL,
        [BANKA_ADI] nvarchar(100) NULL,
        [IBAN_MASKED] nvarchar(30) NULL,
        [ODEME_SAGLAYICI] nvarchar(255) NULL,
        [SAGLAYICI_ISLEM_NO] nvarchar(100) NULL,
        [SAGLAYICI_ONAY_KODU] nvarchar(50) NULL,
        [SAGLAYICI_HATA_KODU] nvarchar(20) NULL,
        [SAGLAYICI_HATA_MESAJI] nvarchar(500) NULL,
        [UC_D_SECURE_KULLANILDI] bit NULL CONSTRAINT [DF__odeme_isl__uc_d___762C88DA] DEFAULT ((0)),
        [UC_D_SECURE_DURUMU] nvarchar(255) NULL,
        [IADE_EDILEBILIR_TUTAR] decimal(10,2) NULL,
        [IADE_EDILEN_TUTAR] decimal(10,2) NULL CONSTRAINT [DF__odeme_isl__iade___7720AD13] DEFAULT ((0.00)),
        [IADE_NEDENI] nvarchar(255) NULL,
        [IADE_ACIKLAMASI] nvarchar(max) NULL,
        [IADE_TARIHI] datetime2(0) NULL,
        [IADE_EDEN_ADMIN_ID] bigint NULL,
        [IPTAL_KESINTISI_ORANI] decimal(5,2) NULL,
        [IPTAL_KESINTISI_TUTARI] decimal(10,2) NULL,
        [FATURA_ID] bigint NULL,
        [ODEME_IP_ADRESI] nvarchar(45) NULL,
        [ODEME_CIHAZ_BILGISI] nvarchar(255) NULL,
        [ODEME_KONUM] nvarchar(100) NULL,
        [RISK_PUANI] tinyint NULL CONSTRAINT [DF__odeme_isl__risk___7814D14C] DEFAULT ((0)),
        [RISK_KONTROLU_SONUCU] nvarchar(255) NULL,
        [MANUEL_ONAY_GEREKTIRIR] bit NULL CONSTRAINT [DF__odeme_isl__manue__7908F585] DEFAULT ((0)),
        [MANUEL_ONAYLAYAN_ADMIN_ID] bigint NULL,
        [MANUEL_ONAY_TARIHI] datetime2(0) NULL,
        [ODEME_BASLANGIC_TARIHI] datetime2(0) NULL CONSTRAINT [DF__odeme_isl__odeme__79FD19BE] DEFAULT (sysutcdatetime()),
        [ODEME_TAMAMLANMA_TARIHI] datetime2(0) NULL,
        [SON_DURUM_DEGISIKLIGI] datetime2(0) NULL,
        CONSTRAINT [PK_ODEME_ISLEMLERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
