-- Tablo: dbo.OTELLER
IF OBJECT_ID(N'dbo.OTELLER', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[OTELLER]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [OTEL_KODU] nvarchar(32) NOT NULL,
        [PARTNER_ID] bigint NOT NULL,
        [KULLANICI_ID] bigint NULL,
        [OTEL_ADI] nvarchar(255) NOT NULL,
        [OTEL_TURU] nvarchar(255) NOT NULL,
        [YILDIZ_SAYISI] tinyint NULL,
        [TURIZM_BELGE_NO] nvarchar(50) NULL,
        [TURIZM_BELGE_TURU] nvarchar(255) NULL,
        [ULKE] nvarchar(50) NULL,
        [SEHIR] nvarchar(50) NOT NULL,
        [ILCE] nvarchar(50) NOT NULL,
        [MAHALLE] nvarchar(100) NULL,
        [TAM_ADRES] nvarchar(max) NOT NULL,
        [POSTA_KODU] nvarchar(10) NULL,
        [ENLEM] decimal(10,8) NULL,
        [BOYLAM] decimal(11,8) NULL,
        [ULKE_ID] bigint NULL,
        [SEHIR_ID] bigint NULL,
        [ILCE_ID] bigint NULL,
        [MAHALLE_ID] bigint NULL,
        [BOLGE_ID] int NULL,
        [TELEFON_1] nvarchar(20) NOT NULL,
        [TELEFON_2] nvarchar(20) NULL,
        [FAKS] nvarchar(20) NULL,
        [EPOSTA] nvarchar(100) NOT NULL,
        [WEB_SITESI] nvarchar(255) NULL,
        [REZERVASYON_TELEFONU] nvarchar(20) NULL,
        [SATIS_KONTAK_ADI] nvarchar(100) NULL,
        [SATIS_KONTAK_TELEFONU] nvarchar(20) NULL,
        [SATIS_KONTAK_EPOSTA] nvarchar(100) NULL,
        [SATIS_NOTLARI] nvarchar(max) NULL,
        [CHECK_IN_SAATI] time(0) NULL,
        [CHECK_OUT_SAATI] time(0) NULL,
        [GEC_CHECK_OUT_MUMKUN_MU] bit CONSTRAINT [DF__oteller__gec_che__29AC2CE0] DEFAULT ((0)) NULL,
        [GEC_CHECK_OUT_UCRETI] decimal(10,2) NULL,
        [ERKEN_CHECK_IN_MUMKUN_MU] bit CONSTRAINT [DF__oteller__erken_c__2AA05119] DEFAULT ((0)) NULL,
        [ERKEN_CHECK_IN_UCRETI] decimal(10,2) NULL,
        [TOPLAM_ODA_SAYISI] smallint NOT NULL,
        [TOPLAM_YATAK_KAPASITESI] smallint NULL,
        [KAT_SAYISI] tinyint NULL,
        [ASANSOR_VAR_MI] bit CONSTRAINT [DF__oteller__asansor__2B947552] DEFAULT ((0)) NULL,
        [ASANSOR_SAYISI] tinyint CONSTRAINT [DF__oteller__asansor__2C88998B] DEFAULT ((0)) NULL,
        [KISA_ACIKLAMA] nvarchar(500) NULL,
        [UZUN_ACIKLAMA] nvarchar(max) NULL,
        [KONUM_ACIKLAMASI] nvarchar(max) NULL,
        [KOMISYON_TURU] nvarchar(255) NULL,
        [VARSAYILAN_KOMISYON_ORANI] decimal(5,2) NOT NULL,
        [KOMISYON_HESAPLAMA_TIPI] nvarchar(255) NULL,
        [ODEME_VADESI] nvarchar(255) NOT NULL,
        [ODEME_YONTEMI] nvarchar(255) NOT NULL,
        [FATURA_KESIM_TURU] nvarchar(255) NOT NULL,
        [DEPOZITO_TUTARI] decimal(10,2) NULL,
        [DEPOZITO_IADE_SURESI] tinyint NULL,
        [MINIMUM_KONAKLAMA_GECESI] tinyint CONSTRAINT [DF__oteller__minimum__2D7CBDC4] DEFAULT ((1)) NULL,
        [MAKSIMUM_KONAKLAMA_GECESI] smallint CONSTRAINT [DF__oteller__maksimu__2E70E1FD] DEFAULT ((30)) NULL,
        [KONUSULAN_DILLER] nvarchar(255) NULL,
        [ORTALAMA_PUAN] decimal(3,2) CONSTRAINT [DF__oteller__ortalam__2F650636] DEFAULT ((0.00)) NULL,
        [TOPLAM_YORUM_SAYISI] int CONSTRAINT [DF__oteller__toplam___30592A6F] DEFAULT ((0)) NULL,
        [TEMIZLIK_PUANI] decimal(3,2) CONSTRAINT [DF__oteller__temizli__314D4EA8] DEFAULT ((0.00)) NULL,
        [KONFOR_PUANI] decimal(3,2) CONSTRAINT [DF__oteller__konfor___324172E1] DEFAULT ((0.00)) NULL,
        [KONUM_PUANI] decimal(3,2) CONSTRAINT [DF__oteller__konum_p__3335971A] DEFAULT ((0.00)) NULL,
        [PERSONEL_PUANI] decimal(3,2) CONSTRAINT [DF__oteller__persone__3429BB53] DEFAULT ((0.00)) NULL,
        [FIYAT_PERFORMANS_PUANI] decimal(3,2) CONSTRAINT [DF__oteller__fiyat_p__351DDF8C] DEFAULT ((0.00)) NULL,
        [KAPAK_FOTOGRAFI] nvarchar(255) NULL,
        [GALERI] nvarchar(max) NULL,
        [VIDEO_URL] nvarchar(255) NULL,
        [SANAL_TUR_URL] nvarchar(255) NULL,
        [YAYIN_DURUMU] nvarchar(255) NULL,
        [ONAY_DURUMU] nvarchar(255) NULL,
        [ONAY_TARIHI] datetime2(0) NULL,
        [ONAYLAYAN_ADMIN_ID] bigint NULL,
        [POPULERLIK_SIRASI] int CONSTRAINT [DF__oteller__populer__361203C5] DEFAULT ((0)) NULL,
        [ONE_CIKAN_OTEL] bit CONSTRAINT [DF__oteller__one_cik__370627FE] DEFAULT ((0)) NULL,
        [TAVSIYE_EDILEN_OTEL] bit CONSTRAINT [DF__oteller__tavsiye__37FA4C37] DEFAULT ((0)) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) CONSTRAINT [DF__oteller__olustur__38EE7070] DEFAULT (sysutcdatetime()) NULL,
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [PARTNER_CEZA_BITIS_TARIHI] datetime2(0) NULL,
        [SEHIR_NORMALIZE] AS (lower(translate(coalesce([SEHIR],N''),concat(nchar((304)),nchar((73)),nchar((305)),nchar((199)),nchar((231)),nchar((286)),nchar((287)),nchar((214)),nchar((246)),nchar((350)),nchar((351)),nchar((220)),nchar((252))),N'iiiccggoossuu'))) PERSISTED,
        [ILCE_NORMALIZE] AS (lower(translate(coalesce([ILCE],N''),concat(nchar((304)),nchar((73)),nchar((305)),nchar((199)),nchar((231)),nchar((286)),nchar((287)),nchar((214)),nchar((246)),nchar((350)),nchar((351)),nchar((220)),nchar((252))),N'iiiccggoossuu'))) PERSISTED,
        [MAHALLE_NORMALIZE] AS (lower(translate(coalesce([MAHALLE],N''),concat(nchar((304)),nchar((73)),nchar((305)),nchar((199)),nchar((231)),nchar((286)),nchar((287)),nchar((214)),nchar((246)),nchar((350)),nchar((351)),nchar((220)),nchar((252))),N'iiiccggoossuu'))) PERSISTED,
        [OTEL_ADI_NORMALIZE] AS (lower(translate(coalesce([OTEL_ADI],N''),concat(nchar((304)),nchar((73)),nchar((305)),nchar((199)),nchar((231)),nchar((286)),nchar((287)),nchar((214)),nchar((246)),nchar((350)),nchar((351)),nchar((220)),nchar((252))),N'iiiccggoossuu'))) PERSISTED,
        [KONUM_NORMALIZE] AS (lower(translate(concat(coalesce([MAHALLE],N''),N' ',coalesce([ILCE],N''),N' ',coalesce([SEHIR],N'')),concat(nchar((304)),nchar((73)),nchar((305)),nchar((199)),nchar((231)),nchar((286)),nchar((287)),nchar((214)),nchar((246)),nchar((350)),nchar((351)),nchar((220)),nchar((252))),N'iiiccggoossuu'))) PERSISTED,
        [FTS_ARAMA_METNI] AS (concat(coalesce([OTEL_ADI],N''),N' ',coalesce([MAHALLE],N''),N' ',coalesce([ILCE],N''),N' ',coalesce([SEHIR],N''))) PERSISTED,
        [OTEL_TIPI_ID] int NULL,
        CONSTRAINT [PK_OTELLER] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
