-- Tablo: dbo.OTEL_OZELLIK_ILISKILERI
IF OBJECT_ID(N'dbo.OTEL_OZELLIK_ILISKILERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[OTEL_OZELLIK_ILISKILERI] (
        [OTEL_ID] bigint NOT NULL,
        [OZELLIK_ID] int NOT NULL,
        [EK_UCRET] decimal(10,2) NULL,
        [ACIKLAMA] nvarchar(255) NULL,
        [KATEGORI_ID] int NULL,
        CONSTRAINT [PK_OTEL_OZELLIK_ILISKILERI] PRIMARY KEY CLUSTERED ([OTEL_ID], [OZELLIK_ID] ASC)
    );
END
