-- Tablo: dbo.OTEL_OZELLIK_KATEGORILERI
IF OBJECT_ID(N'dbo.OTEL_OZELLIK_KATEGORILERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[OTEL_OZELLIK_KATEGORILERI] (
        [ID] smallint IDENTITY(1,1) NOT NULL,
        [KATEGORI_ADI] nvarchar(50) NOT NULL,
        [KATEGORI_IKON] nvarchar(50) NULL,
        [SIRALAMA] tinyint NULL CONSTRAINT [DF__otel_ozel__siral__1E3A7A34] DEFAULT ((0)),
        [AKTIF_MI] bit NULL CONSTRAINT [DF__otel_ozel__aktif__1F2E9E6D] DEFAULT ((1)),
        CONSTRAINT [PK_OTEL_OZELLIK_KATEGORILERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
