-- Tablo: dbo.PANEL_HEADER_BILDIRI_OKUMALARI
IF OBJECT_ID(N'dbo.PANEL_HEADER_BILDIRI_OKUMALARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PANEL_HEADER_BILDIRI_OKUMALARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [PANEL_KODU] nvarchar(24) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [BILDIRI_ANAHTARI] nvarchar(190) NOT NULL,
        [OKUNDU_MI] bit NOT NULL CONSTRAINT [DF__panel_hea__okund__408F9238] DEFAULT ((1)),
        [OKUNDU_TARIHI] datetime2(0) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__panel_hea__olust__4183B671] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__panel_hea__gunce__4277DAAA] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_PANEL_HEADER_BILDIRI_OKUMALARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
