-- Tablo: dbo.PARTNER_BASVURU_HAREKETLERI
IF OBJECT_ID(N'dbo.PARTNER_BASVURU_HAREKETLERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PARTNER_BASVURU_HAREKETLERI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [PARTNER_ID] bigint NOT NULL,
        [ONCEKI_DURUM] nvarchar(40) NULL,
        [YENI_DURUM] nvarchar(40) NOT NULL,
        [ISLEM_TIPI] nvarchar(60) NOT NULL,
        [ACIKLAMA] nvarchar(500) NULL,
        [ISLEM_YAPAN_KULLANICI_ID] bigint NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF__partner_b__olust__4830B400] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_PARTNER_BASVURU_HAREKETLERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
