-- Tablo: dbo.PARTNER_DETAYLARI
IF OBJECT_ID(N'dbo.PARTNER_DETAYLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PARTNER_DETAYLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [FIRMA_UNVANI] nvarchar(200) NOT NULL,
        [FIRMA_TURU] nvarchar(255) NOT NULL,
        [TICARET_SICIL_NO] nvarchar(50) NULL,
        [TICARET_ODASI] nvarchar(100) NULL,
        [KURULUS_YILI] nvarchar(max) NULL,
        [VERGI_DAIRESI] nvarchar(100) NOT NULL,
        [VERGI_NUMARASI] nvarchar(20) NOT NULL,
        [TC_KIMLIK_NO] nvarchar(11) NULL,
        [FATURA_ADRESI] nvarchar(max) NOT NULL,
        [FATURA_IL] nvarchar(50) NOT NULL,
        [FATURA_ILCE] nvarchar(50) NOT NULL,
        [FATURA_POSTA_KODU] nvarchar(10) NULL,
        [YETKILI_AD_SOYAD] nvarchar(100) NOT NULL,
        [YETKILI_TC_NO] nvarchar(11) NOT NULL,
        [YETKILI_TELEFON] nvarchar(20) NOT NULL,
        [YETKILI_EPOSTA] nvarchar(100) NOT NULL,
        [YETKILI_GOREV] nvarchar(100) NULL,
        [BANKA_ADI] nvarchar(100) NOT NULL,
        [BANKA_SUBESI] nvarchar(100) NULL,
        [IBAN] nvarchar(26) NOT NULL,
        [HESAP_SAHIBI_ADI] nvarchar(150) NOT NULL,
        [HESAP_PARA_BIRIMI] nvarchar(255) NULL,
        [SOZLESME_NO] nvarchar(50) NULL,
        [SOZLESME_BASLANGIC_TARIHI] date NULL,
        [SOZLESME_BITIS_TARIHI] date NULL,
        [SOZLESME_PDF_YOLU] nvarchar(255) NULL,
        [ONAY_DURUMU] nvarchar(255) NULL,
        [ONAY_TARIHI] datetime2(0) NULL,
        [ONAYLAYAN_ADMIN_ID] bigint NULL,
        [RED_NEDENI] nvarchar(500) NULL,
        [WEB_SITESI] nvarchar(255) NULL,
        [LOGO_YOLU] nvarchar(255) NULL,
        [ACIKLAMA] nvarchar(max) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NULL CONSTRAINT [DF__partner_d__olust__51BA1E3A] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [EPOSTA_GIRIS_ONAYI_VERILDI_MI] bit NOT NULL CONSTRAINT [DF_partner_detaylari_eposta_giris_onayi_verildi_mi] DEFAULT ((0)),
        [EPOSTA_GIRIS_ONAY_TARIHI] datetime2(7) NULL,
        [EPOSTA_GIRIS_ONAYLAYAN_ADMIN_ID] bigint NULL,
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_partner_detaylari_aktif_mi] DEFAULT ((1)),
        [OTEL_TIPI_ID] int NULL,
        CONSTRAINT [PK_PARTNER_DETAYLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
