-- Tablo: dbo.REZERVASYONLAR
IF OBJECT_ID(N'dbo.REZERVASYONLAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[REZERVASYONLAR]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [REZERVASYON_NO] nvarchar(20) NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [ODA_TIP_ID] bigint NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [FIRMA_ID] bigint NULL,
        [FIRMA_CALISAN_ID] bigint NULL,
        [SATIS_TEMSILCISI_ID] bigint NULL,
        [SATIS_MUSTERI_ID] bigint NULL,
        [REZERVASYON_TASLAGI_ID] bigint NULL,
        [MISAFIR_AD_SOYAD] nvarchar(100) NOT NULL,
        [MISAFIR_EPOSTA] nvarchar(100) NOT NULL,
        [MISAFIR_TELEFON] nvarchar(20) NOT NULL,
        [MISAFIR_SEHIR] nvarchar(100) NULL,
        [MISAFIR_ILCE] nvarchar(100) NULL,
        [MISAFIR_MAHALLE] nvarchar(120) NULL,
        [MISAFIR_ADRES] nvarchar(max) NULL,
        [MISAFIR_ULKE] nvarchar(50) NULL,
        [MISAFIR_ULKE_ID] bigint NULL,
        [MISAFIR_IL_ID] bigint NULL,
        [MISAFIR_ILCE_ID] bigint NULL,
        [MISAFIR_MAHALLE_ID] bigint NULL,
        [MISAFIR_NOTU] nvarchar(max) NULL,
        [GIRIS_TARIHI] date NOT NULL,
        [CIKIS_TARIHI] date NOT NULL,
        [GECE_SAYISI] smallint NULL,
        [YETISKIN_SAYISI] tinyint NOT NULL,
        [COCUK_SAYISI] tinyint CONSTRAINT [DF__rezervasy__cocuk__689D8392] DEFAULT ((0)) NULL,
        [BEBEK_SAYISI] tinyint CONSTRAINT [DF__rezervasy__bebek__6991A7CB] DEFAULT ((0)) NULL,
        [COCUK_YASLARI] nvarchar(max) NULL,
        [ODA_SAYISI] tinyint CONSTRAINT [DF__rezervasy__oda_s__6A85CC04] DEFAULT ((1)) NULL,
        [GECELIK_FIYAT] decimal(10,2) NOT NULL,
        [TOPLAM_ODA_TUTARI] decimal(10,2) NOT NULL,
        [EK_HIZMET_TUTARI] decimal(10,2) CONSTRAINT [DF__rezervasy__ek_hi__6B79F03D] DEFAULT ((0.00)) NULL,
        [VERGI_TUTARI] decimal(10,2) CONSTRAINT [DF__rezervasy__vergi__6C6E1476] DEFAULT ((0.00)) NULL,
        [INDIRIM_TUTARI] decimal(10,2) CONSTRAINT [DF__rezervasy__indir__6D6238AF] DEFAULT ((0.00)) NULL,
        [TOPLAM_TASARRUF] decimal(10,2) CONSTRAINT [DF__rezervasy__topla__6E565CE8] DEFAULT ((0.00)) NOT NULL,
        [KUPON_INDIRIMI] decimal(10,2) CONSTRAINT [DF__rezervasy__kupon__6F4A8121] DEFAULT ((0.00)) NULL,
        [TOPLAM_TUTAR] decimal(10,2) NOT NULL,
        [KOMISYON_ORANI] decimal(5,2) NOT NULL,
        [KOMISYON_TUTARI] decimal(10,2) NULL,
        [OTELE_ODENECEK_TUTAR] decimal(10,2) NULL,
        [PARA_BIRIMI] nvarchar(3) NULL,
        [ODEME_DURUMU] nvarchar(255) NULL,
        [ODEME_YONTEMI] nvarchar(255) NULL,
        [ODEME_TARIHI] datetime2(0) NULL,
        [ON_ODEME_TUTARI] decimal(10,2) NULL,
        [KALAN_ODEME_TUTARI] decimal(10,2) NULL,
        [DURUM] nvarchar(255) NULL,
        [IPTAL_TARIHI] datetime2(0) NULL,
        [IPTAL_NEDENI] nvarchar(500) NULL,
        [IPTAL_EDEN] nvarchar(255) NULL,
        [IPTAL_KESINTISI] decimal(10,2) NULL,
        [IADE_TUTARI] decimal(10,2) NULL,
        [OTEL_ONAY_DURUMU] nvarchar(255) NULL,
        [FIRMA_ONAY_DURUMU] nvarchar(255) NOT NULL,
        [FIRMA_ONAYLAYAN_KULLANICI_ID] bigint NULL,
        [SATIS_ONAYLAYAN_KULLANICI_ID] bigint NULL,
        [SATIS_ONAY_TARIHI] datetime2(0) NULL,
        [FIRMA_ONAY_TARIHI] datetime2(0) NULL,
        [OTEL_ONAY_TARIHI] datetime2(0) NULL,
        [OTEL_RED_NEDENI] nvarchar(500) NULL,
        [ERKEN_GIRIS_TALEBI] bit CONSTRAINT [DF__rezervasy__erken__703EA55A] DEFAULT ((0)) NULL,
        [GEC_CIKIS_TALEBI] bit CONSTRAINT [DF__rezervasy__gec_c__7132C993] DEFAULT ((0)) NULL,
        [TRANSFER_TALEBI] bit CONSTRAINT [DF__rezervasy__trans__7226EDCC] DEFAULT ((0)) NULL,
        [OZEL_ISTEKLER] nvarchar(max) NULL,
        [MUSTERI_TALEP_NOTU] nvarchar(max) NULL,
        [KAYNAK] nvarchar(255) NULL,
        [REZERVASYON_KANALI] nvarchar(255) NULL,
        [KAMPANYA_KODU] nvarchar(50) NULL,
        [REFERANS_KODU] nvarchar(50) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) CONSTRAINT [DF__rezervasy__olust__731B1205] DEFAULT (sysutcdatetime()) NULL,
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [CHECK_IN_YAPILDI_MI] bit CONSTRAINT [DF__rezervasy__check__740F363E] DEFAULT ((0)) NULL,
        [CHECK_IN_TARIHI] datetime2(0) NULL,
        [CHECK_OUT_YAPILDI_MI] bit CONSTRAINT [DF__rezervasy__check__75035A77] DEFAULT ((0)) NULL,
        [CHECK_OUT_TARIHI] datetime2(0) NULL,
        [KOMISYON_VERGI_KURAL_ID] bigint NULL,
        [NET_ODA_TUTARI] decimal(18,2) NULL,
        [KDV_ORANI] decimal(5,2) NULL,
        [KDV_TUTARI] decimal(18,2) NULL,
        [KONAKLAMA_VERGISI_ORANI] decimal(5,2) NULL,
        [KONAKLAMA_VERGISI_TUTARI] decimal(18,2) NULL,
        [TOPLAM_VERGI_TUTARI] decimal(18,2) NULL,
        [KOMISYON_GELIR_VERGISI_ORANI] decimal(5,2) NULL,
        [KOMISYON_GELIR_VERGISI_TUTARI] decimal(18,2) NULL,
        [PLATFORM_NET_KOMISYON_TUTARI] decimal(18,2) NULL,
        [KAPIDA_ODEME_TUTARI] decimal(18,2) NULL,
        [KAPIDA_ODEME_DURUMU] nvarchar(50) NULL,
        [ONLINE_ODEME_TUTARI] decimal(18,2) NULL,
        [ONLINE_ODEME_DURUMU] nvarchar(50) NULL,
        [TAHSIL_EDILEN_TUTAR] decimal(18,2) NULL,
        [KALAN_TAHSIL_EDILECEK_TUTAR] decimal(18,2) NULL,
        [VERGILER_DAHIL_TOPLAM_TUTAR] decimal(18,2) NULL,
        [ODEME_REFERANS_NO] nvarchar(100) NULL,
        [MUHASEBE_NOTU] nvarchar(500) NULL,
        [ODEME_DURUMU_ID] bigint NULL,
        [HAVALE_EFT_BEKLEYEN_TUTARI] decimal(18,2) NULL,
        [REZERVASYON_DURUMU_ID] bigint NULL,
        [DURUM_OZEL_VERI] nvarchar(max) NULL,
        CONSTRAINT [PK_REZERVASYONLAR] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
