-- Tablo: dbo.REZERVASYON_FATURALARI
IF OBJECT_ID(N'dbo.REZERVASYON_FATURALARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[REZERVASYON_FATURALARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [REZERVASYON_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [YUKLEYEN_KULLANICI_ID] bigint NULL,
        [GUVENLI_DOSYA_ID] bigint NULL,
        [DOSYA_ADI] nvarchar(260) NULL,
        [MIME_TIPI] nvarchar(120) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_REZERVASYON_FATURALARI_OLUSTURULMA] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_REZERVASYON_FATURALARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
