-- Tablo: dbo.REZERVASYON_TASLAKLARI
IF OBJECT_ID(N'dbo.REZERVASYON_TASLAKLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[REZERVASYON_TASLAKLARI]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [TASLAK_KODU] nvarchar(36) NOT NULL,
        [KULLANICI_ID] bigint NULL,
        [SESSION_ANAHTARI] nvarchar(100) NULL,
        [KAYNAK] nvarchar(255) NOT NULL,
        [DURUM] nvarchar(255) NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [ODA_TIP_ID] bigint NULL,
        [TAMAMLANAN_REZERVASYON_ID] bigint NULL,
        [MISAFIR_AD_SOYAD] nvarchar(120) NULL,
        [MISAFIR_EPOSTA] nvarchar(120) NULL,
        [MISAFIR_TELEFON] nvarchar(20) NULL,
        [MISAFIR_SEHIR] nvarchar(100) NULL,
        [MISAFIR_ILCE] nvarchar(100) NULL,
        [MISAFIR_MAHALLE] nvarchar(120) NULL,
        [MISAFIR_ADRES] nvarchar(max) NULL,
        [MISAFIR_ULKE_ID] bigint NULL,
        [MISAFIR_IL_ID] bigint NULL,
        [MISAFIR_ILCE_ID] bigint NULL,
        [MISAFIR_MAHALLE_ID] bigint NULL,
        [GIRIS_TARIHI] date NOT NULL,
        [CIKIS_TARIHI] date NOT NULL,
        [YETISKIN_SAYISI] tinyint CONSTRAINT [DF__rezervasy__yetis__61F08603] DEFAULT ((2)) NOT NULL,
        [COCUK_SAYISI] tinyint CONSTRAINT [DF__rezervasy__cocuk__62E4AA3C] DEFAULT ((0)) NOT NULL,
        [ODA_SAYISI] tinyint CONSTRAINT [DF__rezervasy__oda_s__63D8CE75] DEFAULT ((1)) NOT NULL,
        [GECELIK_FIYAT] decimal(10,2) NULL,
        [VERGI_TUTARI] decimal(10,2) NULL,
        [TOPLAM_TUTAR] decimal(10,2) NULL,
        [PARA_BIRIMI] nvarchar(3) NOT NULL,
        [DONUS_URL] nvarchar(500) NULL,
        [PROFIL_TAMAMLANMA_URL] nvarchar(500) NULL,
        [NOTLAR] nvarchar(max) NULL,
        [METADATA] nvarchar(max) NULL,
        [SON_AKTIVITE_TARIHI] datetime2(0) CONSTRAINT [DF__rezervasy__son_a__64CCF2AE] DEFAULT (sysutcdatetime()) NOT NULL,
        [SON_BILDIRIM_TARIHI] datetime2(0) NULL,
        [GECERLILIK_TARIHI] datetime2(0) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) CONSTRAINT [DF__rezervasy__olust__65C116E7] DEFAULT (sysutcdatetime()) NOT NULL,
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [NET_ODA_TUTARI] decimal(18,2) NULL,
        [KDV_ORANI] decimal(9,4) NULL,
        [KDV_TUTARI] decimal(18,2) NULL,
        [KONAKLAMA_VERGISI_ORANI] decimal(9,4) NULL,
        [KONAKLAMA_VERGISI_TUTARI] decimal(18,2) NULL,
        CONSTRAINT [PK_REZERVASYON_TASLAKLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
