-- Tablo: dbo.SCHEMA_MIGRATIONS
IF OBJECT_ID(N'dbo.SCHEMA_MIGRATIONS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[SCHEMA_MIGRATIONS]
    (
        [BETIK_ADI] nvarchar(255) NOT NULL,
        [CHECKSUM] nchar(64) NOT NULL,
        [APPLIED_AT] datetime2(0) CONSTRAINT [DF__schema_mi__appli__184C96B4] DEFAULT (sysutcdatetime()) NOT NULL,
        CONSTRAINT [PK_SCHEMA_MIGRATIONS] PRIMARY KEY CLUSTERED ([BETIK_ADI] ASC)
    );
END
