-- Tablo: dbo.SISTEM_DIYAGRAMLARI
IF OBJECT_ID(N'dbo.SISTEM_DIYAGRAMLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[SISTEM_DIYAGRAMLARI]
    (
        [AD] sysname NOT NULL,
        [PRINCIPAL_ID] int NOT NULL,
        [DIAGRAM_ID] int IDENTITY(1,1) NOT NULL,
        [VERSION] int NULL,
        [DEFINITION] varbinary(max) NULL,
        CONSTRAINT [PK_SISTEM_DIYAGRAMLARI] PRIMARY KEY CLUSTERED ([DIAGRAM_ID] ASC)
    );
END
