-- Tablo: dbo.YARDIM_MERKEZI_KATEGORI_DETAYLARI
IF OBJECT_ID(N'dbo.YARDIM_MERKEZI_KATEGORI_DETAYLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[YARDIM_MERKEZI_KATEGORI_DETAYLARI] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [DESTEK_KATEGORI_ID] bigint NOT NULL,
        [HERO_BASLIK] nvarchar(160) NULL,
        [HERO_ALT_BASLIK] nvarchar(260) NULL,
        [HERO_GORSEL_URL] nvarchar(400) NULL,
        [TAM_ACIKLAMA] nvarchar(max) NULL,
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_ym_kat_detay_aktif] DEFAULT ((1)),
        [GUNCELLENME_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_ym_kat_detay_guncel] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_YARDIM_MERKEZI_KATEGORI_DETAYLARI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
