-- Tablo: dbo.YORUMLAR
IF OBJECT_ID(N'dbo.YORUMLAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[YORUMLAR]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [REZERVASYON_ID] bigint NULL,
        [GENEL_PUAN] tinyint NOT NULL,
        [TEMIZLIK_PUANI] tinyint NOT NULL,
        [KONFOR_PUANI] tinyint NOT NULL,
        [KONUM_PUANI] tinyint NOT NULL,
        [PERSONEL_PUANI] tinyint NOT NULL,
        [FIYAT_PERFORMANS_PUANI] tinyint NOT NULL,
        [YORUM_BASLIGI] nvarchar(200) NULL,
        [YORUM_METNI] nvarchar(max) NOT NULL,
        [OLUMLU_YANLAR] nvarchar(max) NULL,
        [OLUMSUZ_YANLAR] nvarchar(max) NULL,
        [KONAKLAMA_TARIHI] date NULL,
        [KONAKLAMA_TURU] nvarchar(255) NULL,
        [KALDIGI_ODA_TIPI] nvarchar(100) NULL,
        [GECE_SAYISI] tinyint NULL,
        [DOGRULANMIS_KONAKLAMA] bit CONSTRAINT [DF__yorumlar__dogrul__68687968] DEFAULT ((0)) NULL,
        [ONAY_DURUMU] nvarchar(255) NULL,
        [ONAYLAYAN_ADMIN_ID] bigint NULL,
        [ONAY_TARIHI] datetime2(0) NULL,
        [RED_NEDENI] nvarchar(500) NULL,
        [FAYDALI_OY_SAYISI] int CONSTRAINT [DF__yorumlar__faydal__695C9DA1] DEFAULT ((0)) NULL,
        [FAYDASIZ_OY_SAYISI] int CONSTRAINT [DF__yorumlar__faydas__6A50C1DA] DEFAULT ((0)) NULL,
        [RAPOR_SAYISI] smallint CONSTRAINT [DF__yorumlar__rapor___6B44E613] DEFAULT ((0)) NULL,
        [OTEL_YANITI] nvarchar(max) NULL,
        [OTEL_YANITI_TARIHI] datetime2(0) NULL,
        [YANITLAYAN_KULLANICI_ID] bigint NULL,
        [YORUM_GORSELLERI] nvarchar(max) NULL,
        [ANONIM_MI] bit CONSTRAINT [DF__yorumlar__anonim__6C390A4C] DEFAULT ((0)) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) CONSTRAINT [DF__yorumlar__olustu__6D2D2E85] DEFAULT (sysutcdatetime()) NULL,
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [SEYAHAT_PROFILI] nvarchar(40) NULL,
        [MEMNUNIYET_SEVIYESI] tinyint NULL,
        [GENEL_PUAN_10] tinyint NULL,
        [PUAN_ODA_10] tinyint NULL,
        [PUAN_KONUM_10] tinyint NULL,
        [PUAN_FIYAT_10] tinyint NULL,
        [PUAN_PERSONEL_10] tinyint NULL,
        [PUAN_TEMIZLIK_10] tinyint NULL,
        [PUAN_SESSIZLIK_10] tinyint NULL,
        [PUAN_ULASIM_10] tinyint NULL,
        CONSTRAINT [PK_YORUMLAR] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
