-- Tablo: dbo.AKILLI_ROTA — Akıllı Rota etiket kataloğu
IF OBJECT_ID(N'dbo.AKILLI_ROTA', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AKILLI_ROTA]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [ETIKET_KODU] nvarchar(80) NOT NULL,
        [ETIKET_ADI] nvarchar(120) NOT NULL,
        [HASHTAG] nvarchar(120) NOT NULL,
        [ARAMA_METNI] nvarchar(500) NULL,
        [RENK_SINIFI] nvarchar(20) NOT NULL CONSTRAINT [DF_AKILLI_ROTA_RENK] DEFAULT (N'sage'),
        [SIRA_NO] int NOT NULL CONSTRAINT [DF_AKILLI_ROTA_SIRA] DEFAULT ((100)),
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_AKILLI_ROTA_AKTIF] DEFAULT ((1)),
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_AKILLI_ROTA_OLUSTURMA] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_AKILLI_ROTA] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UQ_AKILLI_ROTA_ETIKET_KODU'
      AND object_id = OBJECT_ID(N'dbo.AKILLI_ROTA')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_AKILLI_ROTA_ETIKET_KODU]
        ON [dbo].[AKILLI_ROTA] ([ETIKET_KODU] ASC);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_AKILLI_ROTA_AKTIF_SIRA'
      AND object_id = OBJECT_ID(N'dbo.AKILLI_ROTA')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_AKILLI_ROTA_AKTIF_SIRA]
        ON [dbo].[AKILLI_ROTA] ([AKTIF_MI] ASC, [SIRA_NO] ASC)
        INCLUDE ([ETIKET_KODU], [ETIKET_ADI], [HASHTAG], [RENK_SINIFI]);
END
GO

-- Tablo: dbo.AKILLI_ROTA_OTELLER — otel etiket üyelikleri
IF OBJECT_ID(N'dbo.AKILLI_ROTA_OTELLER', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AKILLI_ROTA_OTELLER]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [AKILLI_ROTA_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [KATILMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_AKILLI_ROTA_OTELLER_KATILMA] DEFAULT (sysutcdatetime()),
        [BITIS_TARIHI] datetime2(0) NULL,
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_AKILLI_ROTA_OTELLER_AKTIF] DEFAULT ((1)),
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_AKILLI_ROTA_OTELLER_OLUSTURMA] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        [KULLANICI_ID] bigint NULL,
        CONSTRAINT [PK_AKILLI_ROTA_OTELLER] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UQ_AKILLI_ROTA_OTELLER_ROTA_OTEL'
      AND object_id = OBJECT_ID(N'dbo.AKILLI_ROTA_OTELLER')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_AKILLI_ROTA_OTELLER_ROTA_OTEL]
        ON [dbo].[AKILLI_ROTA_OTELLER] ([AKILLI_ROTA_ID] ASC, [OTEL_ID] ASC);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_AKILLI_ROTA_OTELLER_OTEL_AKTIF'
      AND object_id = OBJECT_ID(N'dbo.AKILLI_ROTA_OTELLER')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_AKILLI_ROTA_OTELLER_OTEL_AKTIF]
        ON [dbo].[AKILLI_ROTA_OTELLER] ([OTEL_ID] ASC, [AKTIF_MI] ASC)
        INCLUDE ([AKILLI_ROTA_ID], [BITIS_TARIHI]);
END
GO

IF OBJECT_ID(N'dbo.FK_AKILLI_ROTA_OTELLER_ROTA', N'F') IS NULL
   AND OBJECT_ID(N'dbo.AKILLI_ROTA_OTELLER', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.AKILLI_ROTA', N'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[AKILLI_ROTA_OTELLER] WITH CHECK
        ADD CONSTRAINT [FK_AKILLI_ROTA_OTELLER_ROTA] FOREIGN KEY ([AKILLI_ROTA_ID]) REFERENCES [dbo].[AKILLI_ROTA] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_AKILLI_ROTA_OTELLER_OTEL', N'F') IS NULL
   AND OBJECT_ID(N'dbo.AKILLI_ROTA_OTELLER', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.OTELLER', N'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[AKILLI_ROTA_OTELLER] WITH CHECK
        ADD CONSTRAINT [FK_AKILLI_ROTA_OTELLER_OTEL] FOREIGN KEY ([OTEL_ID]) REFERENCES [dbo].[OTELLER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_AKILLI_ROTA_OTELLER_KULLANICI', N'F') IS NULL
   AND OBJECT_ID(N'dbo.AKILLI_ROTA_OTELLER', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.KULLANICILAR', N'U') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[AKILLI_ROTA_OTELLER] WITH CHECK
        ADD CONSTRAINT [FK_AKILLI_ROTA_OTELLER_KULLANICI] FOREIGN KEY ([KULLANICI_ID]) REFERENCES [dbo].[KULLANICILAR] ([ID]);
END
GO
