-- Kayıtlı ödeme kartları: AES-256-GCM şifreli veri, token ve partner görüntüleme denetimi
SET NOCOUNT ON;

IF COL_LENGTH(N'dbo.KULLANICI_ODEME_YONTEMLERI', N'KART_TOKEN') IS NULL
BEGIN
    ALTER TABLE [dbo].[KULLANICI_ODEME_YONTEMLERI] ADD [KART_TOKEN] nvarchar(64) NULL;
END;
GO

IF COL_LENGTH(N'dbo.KULLANICI_ODEME_YONTEMLERI', N'SIFRELI_KART_VERISI') IS NULL
BEGIN
    ALTER TABLE [dbo].[KULLANICI_ODEME_YONTEMLERI] ADD [SIFRELI_KART_VERISI] varbinary(max) NULL;
END;
GO

IF COL_LENGTH(N'dbo.KULLANICI_ODEME_YONTEMLERI', N'MASKELI_PAN') IS NULL
BEGIN
    ALTER TABLE [dbo].[KULLANICI_ODEME_YONTEMLERI] ADD [MASKELI_PAN] nvarchar(32) NULL;
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_KULLANICI_ODEME_YONTEMLERI_KART_TOKEN'
      AND object_id = OBJECT_ID(N'dbo.KULLANICI_ODEME_YONTEMLERI'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UX_KULLANICI_ODEME_YONTEMLERI_KART_TOKEN]
        ON [dbo].[KULLANICI_ODEME_YONTEMLERI]([KART_TOKEN])
        WHERE [KART_TOKEN] IS NOT NULL;
END;
GO

IF OBJECT_ID(N'dbo.REZERVASYON_ODEME_KART_SNAPSHOT', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[REZERVASYON_ODEME_KART_SNAPSHOT] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [REZERVASYON_ID] bigint NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [KAYITLI_KART_ID] bigint NULL,
        [KART_TOKEN] nvarchar(64) NOT NULL,
        [SIFRELI_KART_VERISI] varbinary(max) NOT NULL,
        [MASKELI_PAN] nvarchar(32) NOT NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_REZ_ODEME_KART_SNAPSHOT_OLUSTURULMA] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_REZERVASYON_ODEME_KART_SNAPSHOT] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_REZERVASYON_ODEME_KART_SNAPSHOT_REZERVASYON'
      AND object_id = OBJECT_ID(N'dbo.REZERVASYON_ODEME_KART_SNAPSHOT'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UX_REZERVASYON_ODEME_KART_SNAPSHOT_REZERVASYON]
        ON [dbo].[REZERVASYON_ODEME_KART_SNAPSHOT]([REZERVASYON_ID]);
END;
GO

IF OBJECT_ID(N'dbo.PARTNER_ODEME_KART_GORUNTULEME_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PARTNER_ODEME_KART_GORUNTULEME_LOG] (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [REZERVASYON_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [PARTNER_KULLANICI_ID] bigint NOT NULL,
        [DENEME_SIRASI] int NOT NULL,
        [BASARILI_MI] bit NOT NULL,
        [IP_ADRESI] nvarchar(64) NULL,
        [KULLANICI_ARAC] nvarchar(500) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_PARTNER_ODEME_KART_LOG_OLUSTURULMA] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_PARTNER_ODEME_KART_GORUNTULEME_LOG] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_PARTNER_ODEME_KART_LOG_REZERVASYON'
      AND object_id = OBJECT_ID(N'dbo.PARTNER_ODEME_KART_GORUNTULEME_LOG'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_PARTNER_ODEME_KART_LOG_REZERVASYON]
        ON [dbo].[PARTNER_ODEME_KART_GORUNTULEME_LOG]([REZERVASYON_ID], [OLUSTURULMA_TARIHI] DESC);
END;
GO
