/* KULLANICILAR profil adres ID zinciri (ULKELER → ILLER → ILCELER → MAHALLELER) */
SET NOCOUNT ON;

IF COL_LENGTH(N'dbo.KULLANICILAR', N'ULKE_ID') IS NULL
    ALTER TABLE [dbo].[KULLANICILAR] ADD [ULKE_ID] bigint NULL;

IF COL_LENGTH(N'dbo.KULLANICILAR', N'IL_ID') IS NULL
    ALTER TABLE [dbo].[KULLANICILAR] ADD [IL_ID] bigint NULL;

IF COL_LENGTH(N'dbo.KULLANICILAR', N'ILCE_ID') IS NULL
    ALTER TABLE [dbo].[KULLANICILAR] ADD [ILCE_ID] bigint NULL;

IF COL_LENGTH(N'dbo.KULLANICILAR', N'MAHALLE_ID') IS NULL
    ALTER TABLE [dbo].[KULLANICILAR] ADD [MAHALLE_ID] bigint NULL;

GO
