/* scope: dbo.OTEL_OZELLIKLERI only
   goal: paid services (vale/transfer etc.) should use EK_UCRET model
*/
IF OBJECT_ID(N'dbo.OTEL_OZELLIKLERI', N'U') IS NULL RETURN;
IF OBJECT_ID(N'dbo.OTEL_OZELLIK_KATEGORILERI', N'U') IS NULL RETURN;

BEGIN TRAN;

/* paid features: switch FIYAT -> EK_UCRET semantic */
UPDATE dbo.OTEL_OZELLIKLERI
SET DEGER_TIPI = N'EK_UCRET'
WHERE UCRETLI_MI = 1
  AND COALESCE(DEGER_TIPI, N'') IN (N'FIYAT', N'PRICE');

/* ensure transport category exists */
IF NOT EXISTS (SELECT 1 FROM dbo.OTEL_OZELLIK_KATEGORILERI WHERE KATEGORI_ADI = N'ULASIM_OTOPARK')
BEGIN
    INSERT INTO dbo.OTEL_OZELLIK_KATEGORILERI (KATEGORI_ADI, KATEGORI_IKON, SIRALAMA, AKTIF_MI)
    VALUES (N'ULASIM_OTOPARK', N'fa-square-parking', 80, 1);
END

DECLARE @katId smallint;
SELECT TOP 1 @katId = ID FROM dbo.OTEL_OZELLIK_KATEGORILERI WHERE KATEGORI_ADI = N'ULASIM_OTOPARK';

/* add missing vale / transfer features */
IF NOT EXISTS (SELECT 1 FROM dbo.OTEL_OZELLIKLERI WHERE OZELLIK_KODU = N'VALE_HIZMETI')
BEGIN
    INSERT INTO dbo.OTEL_OZELLIKLERI
    (
      KATEGORI_ID, OZELLIK_ADI, OZELLIK_IKON, UCRETLI_MI, ONE_CIKAN_OZELLIK, SIRALAMA, AKTIF_MI,
      OZELLIK_KODU, FILTRELENEBILIR_MI, DEGER_TIPI, SECENEKLER_JSON, GORUNUM_ALANI
    )
    VALUES
    (
      @katId, N'VALE HIZMETI', N'fa-car-side', 1, 0, 730, 1,
      N'VALE_HIZMETI', 1, N'EK_UCRET', N'["ARAC_BASI","GUNLUK","GIRIS_CIKIS"]', N'OTEL_DETAY'
    );
END

IF NOT EXISTS (SELECT 1 FROM dbo.OTEL_OZELLIKLERI WHERE OZELLIK_KODU = N'SEHIR_ICI_TRANSFER')
BEGIN
    INSERT INTO dbo.OTEL_OZELLIKLERI
    (
      KATEGORI_ID, OZELLIK_ADI, OZELLIK_IKON, UCRETLI_MI, ONE_CIKAN_OZELLIK, SIRALAMA, AKTIF_MI,
      OZELLIK_KODU, FILTRELENEBILIR_MI, DEGER_TIPI, SECENEKLER_JSON, GORUNUM_ALANI
    )
    VALUES
    (
      @katId, N'SEHIR ICI TRANSFER', N'fa-taxi', 1, 0, 740, 1,
      N'SEHIR_ICI_TRANSFER', 1, N'EK_UCRET', N'["KISI_BASI","ARAC_BASI","MESAFE_BAZLI"]', N'OTEL_DETAY'
    );
END

IF NOT EXISTS (SELECT 1 FROM dbo.OTEL_OZELLIKLERI WHERE OZELLIK_KODU = N'OZEL_TRANSFER')
BEGIN
    INSERT INTO dbo.OTEL_OZELLIKLERI
    (
      KATEGORI_ID, OZELLIK_ADI, OZELLIK_IKON, UCRETLI_MI, ONE_CIKAN_OZELLIK, SIRALAMA, AKTIF_MI,
      OZELLIK_KODU, FILTRELENEBILIR_MI, DEGER_TIPI, SECENEKLER_JSON, GORUNUM_ALANI
    )
    VALUES
    (
      @katId, N'OZEL TRANSFER', N'fa-van-shuttle', 1, 0, 750, 1,
      N'OZEL_TRANSFER', 1, N'EK_UCRET', N'["ARAC_BASI","LOKASYON_BAZLI"]', N'OTEL_DETAY'
    );
END

/* normalize existing transport features to EK_UCRET */
UPDATE dbo.OTEL_OZELLIKLERI
SET
    DEGER_TIPI = N'EK_UCRET',
    SECENEKLER_JSON = COALESCE(SECENEKLER_JSON, N'["UCRETSIZ","UCRETLI"]')
WHERE OZELLIK_KODU IN (N'OTOPARK', N'HAVAALANI_SERVISI', N'VALE_HIZMETI', N'SEHIR_ICI_TRANSFER', N'OZEL_TRANSFER');

COMMIT TRAN;
