/* scope: dbo.OTEL_OZELLIK_KATEGORILERI + dbo.OTEL_OZELLIKLERI + dbo.OTEL_OZELLIK_ILISKILERI */
/* NOTE: ODA_FIYAT_MUSAITLIK intentionally untouched */

IF OBJECT_ID(N'dbo.OTEL_OZELLIK_KATEGORILERI', N'U') IS NULL RETURN;
IF OBJECT_ID(N'dbo.OTEL_OZELLIKLERI', N'U') IS NULL RETURN;
IF OBJECT_ID(N'dbo.OTEL_OZELLIK_ILISKILERI', N'U') IS NULL RETURN;

BEGIN TRAN;

/* 1) OTEL_OZELLIKLERI metadata columns */
IF COL_LENGTH('dbo.OTEL_OZELLIKLERI', 'OZELLIK_KODU') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIKLERI ADD OZELLIK_KODU nvarchar(80) NULL;

IF COL_LENGTH('dbo.OTEL_OZELLIKLERI', 'FILTRELENEBILIR_MI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIKLERI ADD FILTRELENEBILIR_MI bit NOT NULL CONSTRAINT DF_OTEL_OZELLIKLERI_FILTRELENEBILIR DEFAULT(1);
END

IF COL_LENGTH('dbo.OTEL_OZELLIKLERI', 'DEGER_TIPI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIKLERI ADD DEGER_TIPI nvarchar(30) NOT NULL CONSTRAINT DF_OTEL_OZELLIKLERI_DEGER_TIPI DEFAULT(N'BOOL');
END

IF COL_LENGTH('dbo.OTEL_OZELLIKLERI', 'SECENEKLER_JSON') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIKLERI ADD SECENEKLER_JSON nvarchar(max) NULL;

IF COL_LENGTH('dbo.OTEL_OZELLIKLERI', 'GORUNUM_ALANI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIKLERI ADD GORUNUM_ALANI nvarchar(30) NOT NULL CONSTRAINT DF_OTEL_OZELLIKLERI_GORUNUM DEFAULT(N'OTEL_DETAY');
END

/* 2) OTEL_OZELLIK_ILISKILERI value/price model columns */
IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'AKTIF_MI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD AKTIF_MI bit NOT NULL CONSTRAINT DF_OTEL_OZELLIK_ILISKILERI_AKTIF DEFAULT(1);
END

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'DEGER_METNI') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD DEGER_METNI nvarchar(255) NULL;

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'DEGER_JSON') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD DEGER_JSON nvarchar(max) NULL;

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYATLANDIRMA_TIPI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYATLANDIRMA_TIPI nvarchar(30) NOT NULL CONSTRAINT DF_OTEL_OZELLIK_ILISKILERI_FT DEFAULT(N'YOK');
END

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYAT_PARA_BIRIMI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYAT_PARA_BIRIMI nvarchar(10) NOT NULL CONSTRAINT DF_OTEL_OZELLIK_ILISKILERI_PB DEFAULT(N'TRY');
END

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYAT_BIRIMI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYAT_BIRIMI nvarchar(30) NOT NULL CONSTRAINT DF_OTEL_OZELLIK_ILISKILERI_FB DEFAULT(N'YOK');
END

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYAT_1_KISI') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYAT_1_KISI decimal(10,2) NULL;
IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYAT_2_KISI') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYAT_2_KISI decimal(10,2) NULL;
IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYAT_3_KISI') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYAT_3_KISI decimal(10,2) NULL;
IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'FIYAT_4_KISI') IS NULL
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD FIYAT_4_KISI decimal(10,2) NULL;

IF COL_LENGTH('dbo.OTEL_OZELLIK_ILISKILERI', 'GUNCELLENME_TARIHI') IS NULL
BEGIN
    ALTER TABLE dbo.OTEL_OZELLIK_ILISKILERI ADD GUNCELLENME_TARIHI datetime2 NULL;
END

/* 3) category seed */
IF OBJECT_ID('tempdb..#kat_seed') IS NOT NULL DROP TABLE #kat_seed;
CREATE TABLE #kat_seed
(
    KATEGORI_ADI nvarchar(50) NOT NULL,
    KATEGORI_IKON nvarchar(50) NULL,
    SIRALAMA tinyint NOT NULL
);

INSERT INTO #kat_seed (KATEGORI_ADI, KATEGORI_IKON, SIRALAMA) VALUES
(N'GENEL_HIZMETLER', N'fa-concierge-bell', 10),
(N'YEME_ICME', N'fa-utensils', 20),
(N'ODA_DONANIMI', N'fa-bed', 30),
(N'SPA_SAGLIK', N'fa-spa', 40),
(N'SPOR_AKTIVITE', N'fa-dumbbell', 50),
(N'COCUK_AILE', N'fa-people-roof', 60),
(N'ERISILEBILIRLIK', N'fa-wheelchair', 70),
(N'ULASIM_OTOPARK', N'fa-square-parking', 80),
(N'IS_TOPLANTI', N'fa-briefcase', 90),
(N'GUVENLIK', N'fa-shield-halved', 100);

INSERT INTO dbo.OTEL_OZELLIK_KATEGORILERI (KATEGORI_ADI, KATEGORI_IKON, SIRALAMA, AKTIF_MI)
SELECT s.KATEGORI_ADI, s.KATEGORI_IKON, s.SIRALAMA, 1
FROM #kat_seed s
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.OTEL_OZELLIK_KATEGORILERI k WHERE k.KATEGORI_ADI = s.KATEGORI_ADI
);

UPDATE k
SET
    k.KATEGORI_IKON = COALESCE(NULLIF(k.KATEGORI_IKON, N''), s.KATEGORI_IKON),
    k.SIRALAMA = s.SIRALAMA,
    k.AKTIF_MI = 1
FROM dbo.OTEL_OZELLIK_KATEGORILERI k
INNER JOIN #kat_seed s ON s.KATEGORI_ADI = k.KATEGORI_ADI;

/* 4) feature seed */
IF OBJECT_ID('tempdb..#oz_seed') IS NOT NULL DROP TABLE #oz_seed;
CREATE TABLE #oz_seed
(
    OZELLIK_KODU nvarchar(80) NOT NULL,
    KATEGORI_ADI nvarchar(50) NOT NULL,
    OZELLIK_ADI nvarchar(100) NOT NULL,
    OZELLIK_IKON nvarchar(50) NULL,
    UCRETLI_MI bit NOT NULL,
    ONE_CIKAN_OZELLIK bit NOT NULL,
    SIRALAMA smallint NOT NULL,
    FILTRELENEBILIR_MI bit NOT NULL,
    DEGER_TIPI nvarchar(30) NOT NULL,
    SECENEKLER_JSON nvarchar(max) NULL,
    GORUNUM_ALANI nvarchar(30) NOT NULL
);

INSERT INTO #oz_seed VALUES
(N'RESEPSIYON_24_SAAT',N'GENEL_HIZMETLER',N'24 SAAT RESEPSIYON',N'fa-clock',0,1,10,1,N'BOOL',NULL,N'OTEL_KARTI'),
(N'UCRETSIZ_WIFI',N'GENEL_HIZMETLER',N'UCRETSIZ WIFI',N'fa-wifi',0,1,20,1,N'BOOL',NULL,N'OTEL_KARTI'),
(N'ASANSOR',N'GENEL_HIZMETLER',N'ASANSOR',N'fa-elevator',0,0,30,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'KLIMA',N'GENEL_HIZMETLER',N'KLIMA',N'fa-fan',0,0,40,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'GUNLUK_TEMIZLIK',N'GENEL_HIZMETLER',N'GUNLUK TEMIZLIK',N'fa-broom',0,0,50,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'RESTORAN',N'YEME_ICME',N'RESTORAN',N'fa-utensils',0,1,110,1,N'BOOL',NULL,N'OTEL_KARTI'),
(N'KAHVALTI',N'YEME_ICME',N'KAHVALTI SERVISI',N'fa-mug-hot',1,1,120,1,N'FIYAT',N'["DAHIL","HARIC","KISI_BASI","ODA_BASI"]',N'OTEL_DETAY'),
(N'ACIK_BUFE',N'YEME_ICME',N'ACIK BUFE',N'fa-bowl-food',1,0,130,1,N'FIYAT',N'["KISI_BASI","DAHIL"]',N'OTEL_DETAY'),
(N'A_LA_CARTE',N'YEME_ICME',N'A LA CARTE',N'fa-utensils',1,0,140,1,N'FIYAT',N'["KISI_BASI","MENU"]',N'OTEL_DETAY'),
(N'ODA_SERVISI',N'YEME_ICME',N'ODA SERVISI',N'fa-bell-concierge',1,0,150,1,N'FIYAT',N'["SERVIS_BEDELI","URUN_BAZLI"]',N'OTEL_DETAY'),
(N'BAR',N'YEME_ICME',N'BAR',N'fa-wine-glass',0,0,160,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'MINIBAR',N'ODA_DONANIMI',N'MINIBAR',N'fa-wine-bottle',1,0,210,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'EMANET_KASASI',N'ODA_DONANIMI',N'EMANET KASASI',N'fa-vault',0,0,220,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'TV',N'ODA_DONANIMI',N'TELEVIZYON',N'fa-tv',0,0,230,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'KAHVE_CAY_SETI',N'ODA_DONANIMI',N'KAHVE CAY SETI',N'fa-mug-hot',0,0,240,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'BALKON',N'ODA_DONANIMI',N'BALKON',N'fa-door-open',0,0,250,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'SPA',N'SPA_SAGLIK',N'SPA',N'fa-spa',1,0,310,1,N'FIYAT',N'["KISI_BASI","PAKET"]',N'OTEL_DETAY'),
(N'SAUNA',N'SPA_SAGLIK',N'SAUNA',N'fa-fire',1,0,320,1,N'FIYAT',N'["KISI_BASI","SEANS"]',N'OTEL_DETAY'),
(N'HAMAM',N'SPA_SAGLIK',N'HAMAM',N'fa-hot-tub-person',1,0,330,1,N'FIYAT',N'["KISI_BASI","SEANS"]',N'OTEL_DETAY'),
(N'FITNESS',N'SPA_SAGLIK',N'FITNESS',N'fa-dumbbell',0,0,340,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'HAVUZ_ACIK',N'SPOR_AKTIVITE',N'ACIK HAVUZ',N'fa-water-ladder',0,1,410,1,N'BOOL',NULL,N'OTEL_KARTI'),
(N'HAVUZ_KAPALI',N'SPOR_AKTIVITE',N'KAPALI HAVUZ',N'fa-water-ladder',0,0,420,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'COCUK_HAVUZU',N'SPOR_AKTIVITE',N'COCUK HAVUZU',N'fa-person-swimming',0,0,430,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'AILE_ODASI',N'COCUK_AILE',N'AILE ODASI',N'fa-people-roof',0,1,510,1,N'BOOL',NULL,N'OTEL_KARTI'),
(N'COCUK_KULUBU',N'COCUK_AILE',N'COCUK KULUBU',N'fa-child',1,0,520,1,N'FIYAT',N'["KISI_BASI","GUNLUK"]',N'OTEL_DETAY'),
(N'BEBEK_YATAGI',N'COCUK_AILE',N'BEBEK YATAGI',N'fa-baby',1,0,530,1,N'FIYAT',N'["GECELIK","KONAKLAMA"]',N'OTEL_DETAY'),

(N'ENGELLI_ERISIMI',N'ERISILEBILIRLIK',N'ENGELLI ERISIMI',N'fa-wheelchair',0,0,610,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'ENGELLI_BANYO',N'ERISILEBILIRLIK',N'ENGELLI BANYO',N'fa-wheelchair-move',0,0,620,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'OTOPARK',N'ULASIM_OTOPARK',N'OTOPARK',N'fa-square-parking',1,1,710,1,N'FIYAT',N'["UCRETSIZ","GUNLUK","SAATLIK"]',N'OTEL_KARTI'),
(N'HAVAALANI_SERVISI',N'ULASIM_OTOPARK',N'HAVAALANI SERVISI',N'fa-van-shuttle',1,0,720,1,N'FIYAT',N'["KISI_BASI","ARAC_BASI"]',N'OTEL_DETAY'),

(N'TOPLANTI_ODASI',N'IS_TOPLANTI',N'TOPLANTI ODASI',N'fa-people-group',1,0,810,1,N'FIYAT',N'["SAATLIK","GUNLUK"]',N'OTEL_DETAY'),
(N'IS_MERKEZI',N'IS_TOPLANTI',N'IS MERKEZI',N'fa-briefcase',0,0,820,1,N'BOOL',NULL,N'OTEL_DETAY'),

(N'KARTLI_GIRIS',N'GUVENLIK',N'KARTLI GIRIS',N'fa-id-card',0,0,910,1,N'BOOL',NULL,N'OTEL_DETAY'),
(N'KAMERA_SISTEMI',N'GUVENLIK',N'KAMERA SISTEMI',N'fa-video',0,0,920,1,N'BOOL',NULL,N'OTEL_DETAY');

DECLARE @sql_ozellik_upsert nvarchar(max) = N'
;WITH cte AS
(
    SELECT s.*, k.ID AS KAT_ID
    FROM #oz_seed s
    INNER JOIN dbo.OTEL_OZELLIK_KATEGORILERI k ON k.KATEGORI_ADI = s.KATEGORI_ADI
)
INSERT INTO dbo.OTEL_OZELLIKLERI
(
    KATEGORI_ID, OZELLIK_ADI, OZELLIK_IKON, UCRETLI_MI, ONE_CIKAN_OZELLIK, SIRALAMA, AKTIF_MI,
    OZELLIK_KODU, FILTRELENEBILIR_MI, DEGER_TIPI, SECENEKLER_JSON, GORUNUM_ALANI
)
SELECT
    c.KAT_ID, c.OZELLIK_ADI, c.OZELLIK_IKON, c.UCRETLI_MI, c.ONE_CIKAN_OZELLIK, c.SIRALAMA, 1,
    c.OZELLIK_KODU, c.FILTRELENEBILIR_MI, c.DEGER_TIPI, c.SECENEKLER_JSON, c.GORUNUM_ALANI
FROM cte c
WHERE NOT EXISTS (SELECT 1 FROM dbo.OTEL_OZELLIKLERI o WHERE o.OZELLIK_KODU = c.OZELLIK_KODU);

UPDATE o
SET
    o.KATEGORI_ID = c.KAT_ID,
    o.OZELLIK_ADI = c.OZELLIK_ADI,
    o.OZELLIK_IKON = c.OZELLIK_IKON,
    o.UCRETLI_MI = c.UCRETLI_MI,
    o.ONE_CIKAN_OZELLIK = c.ONE_CIKAN_OZELLIK,
    o.SIRALAMA = c.SIRALAMA,
    o.AKTIF_MI = 1,
    o.FILTRELENEBILIR_MI = c.FILTRELENEBILIR_MI,
    o.DEGER_TIPI = c.DEGER_TIPI,
    o.SECENEKLER_JSON = c.SECENEKLER_JSON,
    o.GORUNUM_ALANI = c.GORUNUM_ALANI
FROM dbo.OTEL_OZELLIKLERI o
INNER JOIN
(
    SELECT s.*, k.ID AS KAT_ID
    FROM #oz_seed s
    INNER JOIN dbo.OTEL_OZELLIK_KATEGORILERI k ON k.KATEGORI_ADI = s.KATEGORI_ADI
) c ON c.OZELLIK_KODU = o.OZELLIK_KODU;

UPDATE dbo.OTEL_OZELLIKLERI
SET OZELLIK_KODU = UPPER(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(OZELLIK_ADI)), N'' '', N''_''), N''-'', N''_''), N''/'', N''_''))
WHERE OZELLIK_KODU IS NULL;
';
EXEC sp_executesql @sql_ozellik_upsert;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_OTEL_OZELLIKLERI_OZELLIK_KODU' AND object_id = OBJECT_ID('dbo.OTEL_OZELLIKLERI'))
BEGIN
    EXEC(N'CREATE UNIQUE NONCLUSTERED INDEX IX_OTEL_OZELLIKLERI_OZELLIK_KODU ON dbo.OTEL_OZELLIKLERI(OZELLIK_KODU);');
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_OTEL_OZELLIK_ILISKILERI_OTEL_KAT_OZ' AND object_id = OBJECT_ID('dbo.OTEL_OZELLIK_ILISKILERI'))
    CREATE NONCLUSTERED INDEX IX_OTEL_OZELLIK_ILISKILERI_OTEL_KAT_OZ ON dbo.OTEL_OZELLIK_ILISKILERI(OTEL_ID, KATEGORI_ID, OZELLIK_ID);

COMMIT TRAN;
