-- Tablo: dbo.ANASAYFA_OTEL_BOLUMLERI — anasayfa otel vitrin bölümleri
IF OBJECT_ID(N'dbo.ANASAYFA_OTEL_BOLUMLERI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ANASAYFA_OTEL_BOLUMLERI]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [BOLUM_KODU] nvarchar(50) NOT NULL,
        [BASLIK] nvarchar(200) NOT NULL,
        [ALT_BASLIK] nvarchar(300) NULL,
        [SIRALAMA] int NOT NULL CONSTRAINT [DF_ANASAYFA_OTEL_BOLUMLERI_SIRALAMA] DEFAULT ((100)),
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_ANASAYFA_OTEL_BOLUMLERI_AKTIF] DEFAULT ((1)),
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_ANASAYFA_OTEL_BOLUMLERI_OLUSTURMA] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_ANASAYFA_OTEL_BOLUMLERI] PRIMARY KEY CLUSTERED ([ID] ASC)
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_ANASAYFA_OTEL_BOLUMLERI_AKTIF_SIRALAMA'
      AND object_id = OBJECT_ID(N'dbo.ANASAYFA_OTEL_BOLUMLERI')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ANASAYFA_OTEL_BOLUMLERI_AKTIF_SIRALAMA]
        ON [dbo].[ANASAYFA_OTEL_BOLUMLERI] ([AKTIF_MI] ASC, [SIRALAMA] ASC)
        INCLUDE ([BOLUM_KODU], [BASLIK], [ALT_BASLIK]);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UQ_ANASAYFA_OTEL_BOLUMLERI_OZEL_ROTALAR'
      AND object_id = OBJECT_ID(N'dbo.ANASAYFA_OTEL_BOLUMLERI')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_ANASAYFA_OTEL_BOLUMLERI_OZEL_ROTALAR]
        ON [dbo].[ANASAYFA_OTEL_BOLUMLERI] ([BOLUM_KODU] ASC)
        WHERE [BOLUM_KODU] = N'ozel-rotalar';
END
GO

-- Tablo: dbo.ANASAYFA_OTEL_KAYITLARI — bölüm içi otel seçimleri
IF OBJECT_ID(N'dbo.ANASAYFA_OTEL_KAYITLARI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ANASAYFA_OTEL_KAYITLARI]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [BOLUM_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [SIRALAMA] int NOT NULL CONSTRAINT [DF_ANASAYFA_OTEL_KAYITLARI_SIRALAMA] DEFAULT ((100)),
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_ANASAYFA_OTEL_KAYITLARI_AKTIF] DEFAULT ((1)),
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_ANASAYFA_OTEL_KAYITLARI_OLUSTURMA] DEFAULT (sysutcdatetime()),
        CONSTRAINT [PK_ANASAYFA_OTEL_KAYITLARI] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_ANASAYFA_OTEL_KAYITLARI_BOLUM] FOREIGN KEY ([BOLUM_ID]) REFERENCES [dbo].[ANASAYFA_OTEL_BOLUMLERI] ([ID]),
        CONSTRAINT [FK_ANASAYFA_OTEL_KAYITLARI_OTEL] FOREIGN KEY ([OTEL_ID]) REFERENCES [dbo].[OTELLER] ([ID])
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UQ_ANASAYFA_OTEL_KAYITLARI_BOLUM_OTEL'
      AND object_id = OBJECT_ID(N'dbo.ANASAYFA_OTEL_KAYITLARI')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_ANASAYFA_OTEL_KAYITLARI_BOLUM_OTEL]
        ON [dbo].[ANASAYFA_OTEL_KAYITLARI] ([BOLUM_ID] ASC, [OTEL_ID] ASC);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_ANASAYFA_OTEL_KAYITLARI_BOLUM_SIRALAMA'
      AND object_id = OBJECT_ID(N'dbo.ANASAYFA_OTEL_KAYITLARI')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ANASAYFA_OTEL_KAYITLARI_BOLUM_SIRALAMA]
        ON [dbo].[ANASAYFA_OTEL_KAYITLARI] ([BOLUM_ID] ASC, [AKTIF_MI] ASC, [SIRALAMA] ASC)
        INCLUDE ([OTEL_ID]);
END
GO

-- Varsayılan "Seçilen Özel Rotalar" bölümü
IF OBJECT_ID(N'dbo.ANASAYFA_OTEL_BOLUMLERI', N'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [dbo].[ANASAYFA_OTEL_BOLUMLERI] WHERE [BOLUM_KODU] = N'ozel-rotalar')
BEGIN
    INSERT INTO [dbo].[ANASAYFA_OTEL_BOLUMLERI] ([BOLUM_KODU], [BASLIK], [ALT_BASLIK], [SIRALAMA], [AKTIF_MI])
    VALUES (N'ozel-rotalar', N'Seçilen Özel Rotalar', NULL, 10, 1);
END
GO
