/* KOMISYON_MUHASEBE_KAYITLARI — platform tahsilat takibi (H11 T415) */
SET NOCOUNT ON;

IF COL_LENGTH(N'dbo.KOMISYON_MUHASEBE_KAYITLARI', N'PLATFORM_TAHSILAT_DURUMU') IS NULL
    ALTER TABLE [dbo].[KOMISYON_MUHASEBE_KAYITLARI] ADD [PLATFORM_TAHSILAT_DURUMU] nvarchar(50) NULL;

IF COL_LENGTH(N'dbo.KOMISYON_MUHASEBE_KAYITLARI', N'PLATFORM_TAHSILAT_TARIHI') IS NULL
    ALTER TABLE [dbo].[KOMISYON_MUHASEBE_KAYITLARI] ADD [PLATFORM_TAHSILAT_TARIHI] date NULL;

IF COL_LENGTH(N'dbo.KOMISYON_MUHASEBE_KAYITLARI', N'PLATFORM_TAHSILAT_REFERANSI') IS NULL
    ALTER TABLE [dbo].[KOMISYON_MUHASEBE_KAYITLARI] ADD [PLATFORM_TAHSILAT_REFERANSI] nvarchar(80) NULL;

IF COL_LENGTH(N'dbo.KOMISYON_MUHASEBE_KAYITLARI', N'PLATFORM_TAHSILAT_NOTU') IS NULL
    ALTER TABLE [dbo].[KOMISYON_MUHASEBE_KAYITLARI] ADD [PLATFORM_TAHSILAT_NOTU] nvarchar(500) NULL;

GO

UPDATE [dbo].[KOMISYON_MUHASEBE_KAYITLARI]
SET [PLATFORM_TAHSILAT_DURUMU] = N'Bekliyor'
WHERE [PLATFORM_TAHSILAT_DURUMU] IS NULL;

GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_komisyon_donem_otel'
      AND object_id = OBJECT_ID(N'dbo.KOMISYON_MUHASEBE_KAYITLARI')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_komisyon_donem_otel]
        ON [dbo].[KOMISYON_MUHASEBE_KAYITLARI] ([DONEM] ASC, [OTEL_ID] ASC)
        INCLUDE ([KOMISYON_TUTARI], [PLATFORM_TAHSILAT_DURUMU], [OTELE_ODEME_DURUMU], [PARTNER_ID]);
END

GO
