-- Şafak sürprizi indirim kolonları (REZERVASYONLAR)
SET NOCOUNT ON;

IF COL_LENGTH('dbo.REZERVASYONLAR', 'SAFAK_SURPRIZI_ORANI') IS NULL
BEGIN
    ALTER TABLE dbo.REZERVASYONLAR
        ADD SAFAK_SURPRIZI_ORANI tinyint NULL;
END;

IF COL_LENGTH('dbo.REZERVASYONLAR', 'SAFAK_SURPRIZI_INDIRIM_TUTARI') IS NULL
BEGIN
    ALTER TABLE dbo.REZERVASYONLAR
        ADD SAFAK_SURPRIZI_INDIRIM_TUTARI decimal(10, 2) NULL;
END;
