-- Idempotent: OTEL_LISTE_ABONELIKLERI.KAPSAM_DEGERI_NORMALIZE (listing scope pin)
SET NOCOUNT ON;
GO

IF OBJECT_ID(N'dbo.OTEL_LISTE_ABONELIKLERI', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH(N'dbo.OTEL_LISTE_ABONELIKLERI', N'KAPSAM_DEGERI_NORMALIZE') IS NULL
    BEGIN
        ALTER TABLE [dbo].[OTEL_LISTE_ABONELIKLERI]
            ADD [KAPSAM_DEGERI_NORMALIZE] nvarchar(160) NULL;
    END

    UPDATE [dbo].[OTEL_LISTE_ABONELIKLERI]
    SET [KAPSAM_DEGERI_NORMALIZE] = LOWER(LTRIM(RTRIM(REPLACE(REPLACE(REPLACE([KAPSAM_DEGERI], N'ı', N'i'), N'İ', N'i'), N'ş', N's'))))
    WHERE [KAPSAM_DEGERI_NORMALIZE] IS NULL
      AND NULLIF(LTRIM(RTRIM([KAPSAM_DEGERI])), N'') IS NOT NULL;

    IF EXISTS (
        SELECT 1
        FROM [dbo].[OTEL_LISTE_ABONELIKLERI]
        WHERE [KAPSAM_DEGERI_NORMALIZE] IS NULL
    )
    BEGIN
        UPDATE [dbo].[OTEL_LISTE_ABONELIKLERI]
        SET [KAPSAM_DEGERI_NORMALIZE] = N''
        WHERE [KAPSAM_DEGERI_NORMALIZE] IS NULL;
    END

    IF COL_LENGTH(N'dbo.OTEL_LISTE_ABONELIKLERI', N'KAPSAM_DEGERI_NORMALIZE') IS NOT NULL
       AND NOT EXISTS (
            SELECT 1
            FROM sys.columns c
            INNER JOIN sys.tables t ON t.object_id = c.object_id
            WHERE t.name = N'OTEL_LISTE_ABONELIKLERI'
              AND SCHEMA_NAME(t.schema_id) = N'dbo'
              AND c.name = N'KAPSAM_DEGERI_NORMALIZE'
              AND c.is_nullable = 0
        )
    BEGIN
        ALTER TABLE [dbo].[OTEL_LISTE_ABONELIKLERI]
            ALTER COLUMN [KAPSAM_DEGERI_NORMALIZE] nvarchar(160) NOT NULL;
    END
END
GO
