-- Tablo: dbo.PUAN_AYAR — otel bazlı puan kazanım ve indirim kuralları
IF OBJECT_ID(N'dbo.PUAN_AYAR', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PUAN_AYAR]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [AYAR_TIPI] nvarchar(20) NOT NULL,
        [MIN_DEGER] decimal(18,2) NOT NULL,
        [MAX_DEGER] decimal(18,2) NULL,
        [PUAN_DEGERI] int NULL,
        [INDIRIM_YUZDE] decimal(5,2) NULL,
        [ACIKLAMA] nvarchar(300) NULL,
        [AKTIF_MI] bit NOT NULL CONSTRAINT [DF_PUAN_AYAR_AKTIF] DEFAULT ((1)),
        [SIRA_NO] int NOT NULL CONSTRAINT [DF_PUAN_AYAR_SIRA] DEFAULT ((100)),
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_PUAN_AYAR_OLUSTURMA] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_PUAN_AYAR] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [CK_PUAN_AYAR_TIPI] CHECK ([AYAR_TIPI] IN (N'KAZANIM', N'INDIRIM'))
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_PUAN_AYAR_TIPI_AKTIF_SIRA'
      AND object_id = OBJECT_ID(N'dbo.PUAN_AYAR')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_PUAN_AYAR_TIPI_AKTIF_SIRA]
        ON [dbo].[PUAN_AYAR] ([AYAR_TIPI] ASC, [AKTIF_MI] ASC, [SIRA_NO] ASC)
        INCLUDE ([MIN_DEGER], [MAX_DEGER], [PUAN_DEGERI], [INDIRIM_YUZDE], [ACIKLAMA]);
END
GO

-- Tablo: dbo.PUAN_KULLANICI — kullanıcı+otel bazlı puan bakiyesi
IF OBJECT_ID(N'dbo.PUAN_KULLANICI', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PUAN_KULLANICI]
    (
        [ID] bigint IDENTITY(1,1) NOT NULL,
        [KULLANICI_ID] bigint NOT NULL,
        [OTEL_ID] bigint NOT NULL,
        [TOPLAM_KAZANILAN] int NOT NULL CONSTRAINT [DF_PUAN_KULLANICI_TOPLAM_KAZANILAN] DEFAULT ((0)),
        [KULLANILABILIR_PUAN] int NOT NULL CONSTRAINT [DF_PUAN_KULLANICI_KULLANILABILIR] DEFAULT ((0)),
        [KULLANILAN_PUAN] int NOT NULL CONSTRAINT [DF_PUAN_KULLANICI_KULLANILAN] DEFAULT ((0)),
        [SON_KAZANIM_TARIHI] datetime2(0) NULL,
        [SON_KULLANIM_TARIHI] datetime2(0) NULL,
        [OLUSTURULMA_TARIHI] datetime2(0) NOT NULL CONSTRAINT [DF_PUAN_KULLANICI_OLUSTURMA] DEFAULT (sysutcdatetime()),
        [GUNCELLENME_TARIHI] datetime2(0) NULL,
        CONSTRAINT [PK_PUAN_KULLANICI] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_PUAN_KULLANICI_KULLANICI] FOREIGN KEY ([KULLANICI_ID]) REFERENCES [dbo].[KULLANICILAR] ([ID]),
        CONSTRAINT [FK_PUAN_KULLANICI_OTEL] FOREIGN KEY ([OTEL_ID]) REFERENCES [dbo].[OTELLER] ([ID])
    );
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UQ_PUAN_KULLANICI_KULLANICI_OTEL'
      AND object_id = OBJECT_ID(N'dbo.PUAN_KULLANICI')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_PUAN_KULLANICI_KULLANICI_OTEL]
        ON [dbo].[PUAN_KULLANICI] ([KULLANICI_ID] ASC, [OTEL_ID] ASC);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_PUAN_KULLANICI_OTEL'
      AND object_id = OBJECT_ID(N'dbo.PUAN_KULLANICI')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_PUAN_KULLANICI_OTEL]
        ON [dbo].[PUAN_KULLANICI] ([OTEL_ID] ASC)
        INCLUDE ([KULLANICI_ID], [TOPLAM_KAZANILAN], [KULLANILABILIR_PUAN], [KULLANILAN_PUAN]);
END
GO

-- KULLANICI_PUAN_HAREKETLERI — otel bazlı denetim izi
IF COL_LENGTH(N'dbo.KULLANICI_PUAN_HAREKETLERI', N'OTEL_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[KULLANICI_PUAN_HAREKETLERI]
        ADD [OTEL_ID] bigint NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_KULLANICI_PUAN_HAREKETLERI_OTEL'
      AND object_id = OBJECT_ID(N'dbo.KULLANICI_PUAN_HAREKETLERI')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_KULLANICI_PUAN_HAREKETLERI_OTEL]
        ON [dbo].[KULLANICI_PUAN_HAREKETLERI] ([OTEL_ID] ASC, [ISLEM_TARIHI] DESC)
        INCLUDE ([KULLANICI_ID], [REZERVASYON_ID], [HAREKET_TIPI], [PUAN_DEGISIM]);
END
GO

PRINT N'PUAN_AYAR / PUAN_KULLANICI tabloları ve KULLANICI_PUAN_HAREKETLERI.OTEL_ID hazır.';
GO
