/* Adres hiyerarşisi: ülke → il/eyalet → ilçe → mahalle (ID zinciri) */
SET NOCOUNT ON;
GO

/* --- ILLER --- */
IF COL_LENGTH(N'dbo.ILLER', N'ULKE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[ILLER] ADD [ULKE_ID] bigint NULL;
END
GO

IF COL_LENGTH(N'dbo.ILLER', N'BOLGE_TIPI') IS NULL
BEGIN
    ALTER TABLE [dbo].[ILLER] ADD [BOLGE_TIPI] nvarchar(20) NULL;
END
GO

IF COL_LENGTH(N'dbo.ILLER', N'DIS_KOD') IS NULL
BEGIN
    ALTER TABLE [dbo].[ILLER] ADD [DIS_KOD] nvarchar(16) NULL;
END
GO

DECLARE @trUlkeId bigint = (
    SELECT TOP (1) [ID]
    FROM [dbo].[ULKELER]
    WHERE [AKTIF_MI] = 1 AND RTRIM([ISO2_KODU]) = N'TR'
    ORDER BY [VARSAYILAN_ULKE] DESC, [ID] ASC
);

IF @trUlkeId IS NOT NULL
BEGIN
    UPDATE [dbo].[ILLER]
    SET [ULKE_ID] = @trUlkeId,
        [BOLGE_TIPI] = COALESCE(NULLIF(LTRIM(RTRIM([BOLGE_TIPI])), N''), N'IL'),
        [DIS_KOD] = COALESCE(NULLIF(LTRIM(RTRIM([DIS_KOD])), N''), RIGHT(N'00' + CAST([PLAKA_KODU] AS nvarchar(3)), 2))
    WHERE [ULKE_ID] IS NULL;
END
GO

UPDATE [dbo].[ILLER]
SET [BOLGE_TIPI] = N'IL'
WHERE [BOLGE_TIPI] IS NULL OR LTRIM(RTRIM([BOLGE_TIPI])) = N'';
GO

IF EXISTS (
    SELECT 1 FROM [dbo].[ILLER]
    WHERE [ULKE_ID] IS NULL
)
BEGIN
    RAISERROR(N'ILLER.ULKE_ID backfill tamamlanamadi. Once ULKELER (TR) seed uygulanin.', 16, 1);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.ILLER') AND name = N'ULKE_ID' AND is_nullable = 0
)
BEGIN
    ALTER TABLE [dbo].[ILLER] ALTER COLUMN [ULKE_ID] bigint NOT NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.ILLER') AND name = N'BOLGE_TIPI' AND is_nullable = 0
)
BEGIN
    ALTER TABLE [dbo].[ILLER] ALTER COLUMN [BOLGE_TIPI] nvarchar(20) NOT NULL;
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.default_constraints dc
    INNER JOIN sys.columns c ON c.default_object_id = dc.object_id
    WHERE dc.parent_object_id = OBJECT_ID(N'dbo.ILLER') AND c.name = N'BOLGE_TIPI'
)
BEGIN
    ALTER TABLE [dbo].[ILLER] ADD CONSTRAINT [DF__iller__bolge_tipi] DEFAULT (N'IL') FOR [BOLGE_TIPI];
END
GO

/* --- ILCELER / MAHALLELER (yalnizca Turkiye verisi) --- */
IF COL_LENGTH(N'dbo.ILCELER', N'ULKE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[ILCELER] ADD [ULKE_ID] bigint NULL;
END
GO

IF COL_LENGTH(N'dbo.MAHALLELER', N'ULKE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[MAHALLELER] ADD [ULKE_ID] bigint NULL;
END
GO

DECLARE @trUlkeId2 bigint = (
    SELECT TOP (1) [ID]
    FROM [dbo].[ULKELER]
    WHERE [AKTIF_MI] = 1 AND RTRIM([ISO2_KODU]) = N'TR'
    ORDER BY [VARSAYILAN_ULKE] DESC, [ID] ASC
);

IF @trUlkeId2 IS NOT NULL
BEGIN
    UPDATE c
    SET c.[ULKE_ID] = @trUlkeId2
    FROM [dbo].[ILCELER] AS c
    WHERE c.[ULKE_ID] IS NULL;

    UPDATE m
    SET m.[ULKE_ID] = @trUlkeId2
    FROM [dbo].[MAHALLELER] AS m
    WHERE m.[ULKE_ID] IS NULL;
END
GO

/* --- OTELLER adres ID kolonlari --- */
IF COL_LENGTH(N'dbo.OTELLER', N'ULKE_ID') IS NOT NULL
BEGIN
    DECLARE @ulkeType sysname = (
        SELECT t.name
        FROM sys.columns c
        INNER JOIN sys.types t ON c.user_type_id = t.user_type_id
        WHERE c.object_id = OBJECT_ID(N'dbo.OTELLER') AND c.name = N'ULKE_ID'
    );
    IF @ulkeType = N'smallint'
    BEGIN
        ALTER TABLE [dbo].[OTELLER] ALTER COLUMN [ULKE_ID] bigint NULL;
    END
END
GO

IF COL_LENGTH(N'dbo.OTELLER', N'SEHIR_ID') IS NOT NULL
BEGIN
    DECLARE @sehirType sysname = (
        SELECT t.name
        FROM sys.columns c
        INNER JOIN sys.types t ON c.user_type_id = t.user_type_id
        WHERE c.object_id = OBJECT_ID(N'dbo.OTELLER') AND c.name = N'SEHIR_ID'
    );
    IF @sehirType = N'int'
    BEGIN
        ALTER TABLE [dbo].[OTELLER] ALTER COLUMN [SEHIR_ID] bigint NULL;
    END
END
GO

IF COL_LENGTH(N'dbo.OTELLER', N'ILCE_ID') IS NOT NULL
BEGIN
    DECLARE @ilceType sysname = (
        SELECT t.name
        FROM sys.columns c
        INNER JOIN sys.types t ON c.user_type_id = t.user_type_id
        WHERE c.object_id = OBJECT_ID(N'dbo.OTELLER') AND c.name = N'ILCE_ID'
    );
    IF @ilceType = N'int'
    BEGIN
        ALTER TABLE [dbo].[OTELLER] ALTER COLUMN [ILCE_ID] bigint NULL;
    END
END
GO

IF COL_LENGTH(N'dbo.OTELLER', N'MAHALLE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[OTELLER] ADD [MAHALLE_ID] bigint NULL;
END
GO

/* --- REZERVASYON misafir adres ID --- */
IF COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_ULKE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] ADD [MISAFIR_ULKE_ID] bigint NULL;
END
GO

IF COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_IL_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] ADD [MISAFIR_IL_ID] bigint NULL;
END
GO

IF COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_ILCE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] ADD [MISAFIR_ILCE_ID] bigint NULL;
END
GO

IF COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_MAHALLE_ID') IS NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] ADD [MISAFIR_MAHALLE_ID] bigint NULL;
END
GO

IF OBJECT_ID(N'dbo.REZERVASYON_TASLAKLARI', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH(N'dbo.REZERVASYON_TASLAKLARI', N'MISAFIR_ULKE_ID') IS NULL
        ALTER TABLE [dbo].[REZERVASYON_TASLAKLARI] ADD [MISAFIR_ULKE_ID] bigint NULL;
    IF COL_LENGTH(N'dbo.REZERVASYON_TASLAKLARI', N'MISAFIR_IL_ID') IS NULL
        ALTER TABLE [dbo].[REZERVASYON_TASLAKLARI] ADD [MISAFIR_IL_ID] bigint NULL;
    IF COL_LENGTH(N'dbo.REZERVASYON_TASLAKLARI', N'MISAFIR_ILCE_ID') IS NULL
        ALTER TABLE [dbo].[REZERVASYON_TASLAKLARI] ADD [MISAFIR_ILCE_ID] bigint NULL;
    IF COL_LENGTH(N'dbo.REZERVASYON_TASLAKLARI', N'MISAFIR_MAHALLE_ID') IS NULL
        ALTER TABLE [dbo].[REZERVASYON_TASLAKLARI] ADD [MISAFIR_MAHALLE_ID] bigint NULL;
END
GO

/* --- Foreign keys --- */
IF OBJECT_ID(N'dbo.FK_iller_ulkeler', N'F') IS NULL
BEGIN
    ALTER TABLE [dbo].[ILLER] WITH CHECK ADD CONSTRAINT [FK_iller_ulkeler] FOREIGN KEY ([ULKE_ID]) REFERENCES [dbo].[ULKELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_ilceler_iller', N'F') IS NULL
BEGIN
    ALTER TABLE [dbo].[ILCELER] WITH CHECK ADD CONSTRAINT [FK_ilceler_iller] FOREIGN KEY ([IL_ID]) REFERENCES [dbo].[ILLER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_ilceler_ulkeler', N'F') IS NULL AND COL_LENGTH(N'dbo.ILCELER', N'ULKE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[ILCELER] WITH CHECK ADD CONSTRAINT [FK_ilceler_ulkeler] FOREIGN KEY ([ULKE_ID]) REFERENCES [dbo].[ULKELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_mahalleler_ilceler', N'F') IS NULL
BEGIN
    ALTER TABLE [dbo].[MAHALLELER] WITH CHECK ADD CONSTRAINT [FK_mahalleler_ilceler] FOREIGN KEY ([ILCE_ID]) REFERENCES [dbo].[ILCELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_mahalleler_iller', N'F') IS NULL
BEGIN
    ALTER TABLE [dbo].[MAHALLELER] WITH CHECK ADD CONSTRAINT [FK_mahalleler_iller] FOREIGN KEY ([IL_ID]) REFERENCES [dbo].[ILLER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_mahalleler_ulkeler', N'F') IS NULL AND COL_LENGTH(N'dbo.MAHALLELER', N'ULKE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[MAHALLELER] WITH CHECK ADD CONSTRAINT [FK_mahalleler_ulkeler] FOREIGN KEY ([ULKE_ID]) REFERENCES [dbo].[ULKELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_oteller_ulkeler', N'F') IS NULL AND COL_LENGTH(N'dbo.OTELLER', N'ULKE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[OTELLER] WITH CHECK ADD CONSTRAINT [FK_oteller_ulkeler] FOREIGN KEY ([ULKE_ID]) REFERENCES [dbo].[ULKELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_oteller_iller', N'F') IS NULL AND COL_LENGTH(N'dbo.OTELLER', N'SEHIR_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[OTELLER] WITH CHECK ADD CONSTRAINT [FK_oteller_iller] FOREIGN KEY ([SEHIR_ID]) REFERENCES [dbo].[ILLER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_oteller_ilceler', N'F') IS NULL AND COL_LENGTH(N'dbo.OTELLER', N'ILCE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[OTELLER] WITH CHECK ADD CONSTRAINT [FK_oteller_ilceler] FOREIGN KEY ([ILCE_ID]) REFERENCES [dbo].[ILCELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_oteller_mahalleler', N'F') IS NULL AND COL_LENGTH(N'dbo.OTELLER', N'MAHALLE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[OTELLER] WITH CHECK ADD CONSTRAINT [FK_oteller_mahalleler] FOREIGN KEY ([MAHALLE_ID]) REFERENCES [dbo].[MAHALLELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_rezervasyonlar_misafir_ulke', N'F') IS NULL AND COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_ULKE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] WITH CHECK ADD CONSTRAINT [FK_rezervasyonlar_misafir_ulke] FOREIGN KEY ([MISAFIR_ULKE_ID]) REFERENCES [dbo].[ULKELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_rezervasyonlar_misafir_il', N'F') IS NULL AND COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_IL_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] WITH CHECK ADD CONSTRAINT [FK_rezervasyonlar_misafir_il] FOREIGN KEY ([MISAFIR_IL_ID]) REFERENCES [dbo].[ILLER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_rezervasyonlar_misafir_ilce', N'F') IS NULL AND COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_ILCE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] WITH CHECK ADD CONSTRAINT [FK_rezervasyonlar_misafir_ilce] FOREIGN KEY ([MISAFIR_ILCE_ID]) REFERENCES [dbo].[ILCELER] ([ID]);
END
GO

IF OBJECT_ID(N'dbo.FK_rezervasyonlar_misafir_mahalle', N'F') IS NULL AND COL_LENGTH(N'dbo.REZERVASYONLAR', N'MISAFIR_MAHALLE_ID') IS NOT NULL
BEGIN
    ALTER TABLE [dbo].[REZERVASYONLAR] WITH CHECK ADD CONSTRAINT [FK_rezervasyonlar_misafir_mahalle] FOREIGN KEY ([MISAFIR_MAHALLE_ID]) REFERENCES [dbo].[MAHALLELER] ([ID]);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID(N'dbo.ILLER') AND name = N'IX_ILLER_ULKE_ID'
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ILLER_ULKE_ID] ON [dbo].[ILLER] ([ULKE_ID] ASC, [BOLGE_TIPI] ASC, [IL_ADI] ASC);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id = OBJECT_ID(N'dbo.ILLER') AND name = N'UX_ILLER_ULKE_DIS_KOD'
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UX_ILLER_ULKE_DIS_KOD]
        ON [dbo].[ILLER] ([ULKE_ID] ASC, [DIS_KOD] ASC)
        WHERE [DIS_KOD] IS NOT NULL;
END
GO
