-- Idempotent: irmhro0+user@gmail.com kullanıcı hesabını aktifleştir (e-posta + telefon doğrulama)
-- Canlı kayıt: recep yılmaz / user rolü — giriş için EPOSTA_DOGRULAMA_TARIHI zorunlu
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

IF OBJECT_ID(N'dbo.KULLANICILAR', N'U') IS NULL
BEGIN
    RAISERROR(N'KULLANICILAR tablosu bulunamadi.', 16, 1);
    RETURN;
END;

DECLARE @Email nvarchar(100) = N'irmhro0+user@gmail.com';
DECLARE @UserId bigint;

SELECT @UserId = [ID]
FROM [dbo].[KULLANICILAR]
WHERE [EPOSTA] = @Email;

IF @UserId IS NULL
BEGIN
    PRINT N'Kullanici bulunamadi: ' + @Email;
    RETURN;
END;

UPDATE [dbo].[KULLANICILAR]
SET
    [HESAP_DURUMU] = 1,
    [EPOSTA_DOGRULAMA_TARIHI] = COALESCE([EPOSTA_DOGRULAMA_TARIHI], SYSUTCDATETIME()),
    [TELEFON_DOGRULAMA_DURUMU] = CASE
        WHEN [TELEFON_E164] IS NOT NULL AND LTRIM(RTRIM([TELEFON_E164])) <> N'' THEN N'Dogrulandi'
        ELSE [TELEFON_DOGRULAMA_DURUMU]
    END,
    [TELEFON_DOGRULAMA_TARIHI] = CASE
        WHEN [TELEFON_E164] IS NOT NULL AND LTRIM(RTRIM([TELEFON_E164])) <> N''
            THEN COALESCE([TELEFON_DOGRULAMA_TARIHI], SYSUTCDATETIME())
        ELSE [TELEFON_DOGRULAMA_TARIHI]
    END,
    [BASARISIZ_GIRIS_SAYISI] = 0,
    [GIRIS_KILIT_BITIS_TARIHI] = NULL,
    [GUNCELLENME_TARIHI] = SYSUTCDATETIME()
WHERE [ID] = @UserId
  AND (
        [HESAP_DURUMU] <> 1
     OR [EPOSTA_DOGRULAMA_TARIHI] IS NULL
     OR ([TELEFON_E164] IS NOT NULL AND [TELEFON_DOGRULAMA_TARIHI] IS NULL)
     OR [BASARISIZ_GIRIS_SAYISI] > 0
     OR [GIRIS_KILIT_BITIS_TARIHI] IS NOT NULL
  );

PRINT CONCAT(N'Aktif kullanici ID=', @UserId, N' | guncellenen satir=', @@ROWCOUNT);
GO
