SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;

DECLARE @AdminEmail nvarchar(256) = N'irmhro0@gmail.com';
DECLARE @AdminUserId bigint;

SELECT @AdminUserId = ID
FROM dbo.KULLANICILAR
WHERE EPOSTA = @AdminEmail;

IF @AdminUserId IS NULL
BEGIN
    THROW 51001, 'Temizlik durduruldu: korunacak admin kullanici bulunamadi.', 1;
END;

BEGIN TRANSACTION;

EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';

DECLARE @ClearTables TABLE (TableName sysname NOT NULL PRIMARY KEY);

INSERT INTO @ClearTables (TableName)
VALUES
(N'ADMIN_ISLEM_LOGLARI'),
(N'API_LOGLARI'),
(N'BASARISIZ_ODEME_DENEMELERI'),
(N'BILDIRIM_LOGLARI'),
(N'DEVELOPER_BILDIRIMLERI'),
(N'DIS_KUTU_MESAJLARI'),
(N'EPOSTA_DOGRULAMA_TOKENLARI'),
(N'FATURALAR'),
(N'FIRMA_BASVURU_HAREKETLERI'),
(N'FIRMA_CALISANLARI'),
(N'FIRMA_HARCAMA_LIMITLERI'),
(N'FIRMA_ODA_FIYAT_MUSAITLIK'),
(N'FIRMA_REZERVASYONLARI'),
(N'FIRMALAR'),
(N'FIYAT_INDIRIMLERI'),
(N'GELISTIRME_TALEPLERI'),
(N'GUVENLI_DOSYA_ERISIM_TOKENLARI'),
(N'GUVENLI_DOSYA_VARLIKLARI'),
(N'KAMPANYA_OTELLER'),
(N'KOMISYON_MUHASEBE_KAYITLARI'),
(N'KOMISYON_VERGILER'),
(N'KULLANICI_AKTIVITE_LOGLARI'),
(N'KULLANICI_BILDIRIM_CIHAZLARI'),
(N'KULLANICI_BILDIRIM_TERCIHLERI'),
(N'KULLANICI_BUTCE_PLANLARI'),
(N'KULLANICI_DEPARTMAN'),
(N'KULLANICI_DIJITAL_PASAPORTLARI'),
(N'KULLANICI_FAVORI_FIYAT_ALARM_ISLERI'),
(N'KULLANICI_FAVORI_FIYAT_ALARMLARI'),
(N'KULLANICI_FAVORI_OTELLER'),
(N'KULLANICI_GIRIS_2FA_TOKENLARI'),
(N'KULLANICI_GIRIS_LOGLARI'),
(N'KULLANICI_KONUM_LOGLARI'),
(N'KULLANICI_ODEME_YONTEMLERI'),
(N'KULLANICI_OTURUM_ISTATISTIKLERI'),
(N'KULLANICI_OZEL_TEKLIFLERI'),
(N'KULLANICI_PARTNERLERI'),
(N'KULLANICI_PUAN_HAREKETLERI'),
(N'KULLANICI_ROZETLERI'),
(N'KULLANICI_SADAKAT_HESAPLARI'),
(N'KULLANICI_SEYAHAT_PLAN_OTEL_SECIMLERI'),
(N'KULLANICI_SEYAHAT_PLANLARI'),
(N'KULLANICI_TELEFON_GECMISI'),
(N'KULLANICILAR_ARSIV_YEDEK'),
(N'MESAJ_DOSYALARI'),
(N'MESAJLAR'),
(N'MESAJ_KONUSMALARI'),
(N'MESAJ_SABLONLARI'),
(N'ODA_FIYAT_MUSAITLIK'),
(N'ODA_GORSELLERI'),
(N'ODA_OZELLIK_ILISKILERI'),
(N'ODA_TIPI_OZELLIKLERI'),
(N'ODA_TIPLERI'),
(N'ODEME_ISLEMLERI'),
(N'OTEL_GORSELLERI'),
(N'OTEL_ISTATISTIKLERI'),
(N'OTEL_KOORDINAT_DEGISIM_LOGLARI'),
(N'OTEL_KOSUL_SECIMLERI'),
(N'OTEL_KOSULLARI'),
(N'OTEL_KULLANICI_SAHIPLIKLERI'),
(N'OTEL_LISTE_ABONELIKLERI'),
(N'OTEL_OZELLIK_ILISKILERI'),
(N'OTEL_RAKIP_ANALIZI'),
(N'OTEL_UYUM_DURUMLARI'),
(N'OTEL_YEMEK_HIZMETLERI'),
(N'OTELLER'),
(N'PANEL_HEADER_BILDIRI_OKUMALARI'),
(N'PARTNER_BASVURU_EVRAKLARI'),
(N'PARTNER_BASVURU_HAREKETLERI'),
(N'PARTNER_DESTEK_MESAJLARI'),
(N'PARTNER_DESTEK_TALEPLERI'),
(N'PARTNER_DETAYLARI'),
(N'PARTNER_PAKET_BASVURULARI'),
(N'PARTNER_PANEL_TERCIHLERI'),
(N'PARTNER_TESIS_KULLANICILARI'),
(N'PLATFORM_EPOSTA_MESAJLARI'),
(N'REZERVASYON_FATURALARI'),
(N'REZERVASYON_ODEME_KALEMLERI'),
(N'REZERVASYON_TASLAKLARI'),
(N'REZERVASYONLAR'),
(N'REZERVASYONLAR_ARSIV'),
(N'SATIS_MUSTERI_NOTLARI'),
(N'SATIS_MUSTERILERI'),
(N'SEPET_BLOKAJLARI'),
(N'SIFRE_SIFIRLAMA_TOKENLARI'),
(N'SISTEM_HATA_LOGLARI'),
(N'SISTEM_ICI_BILDIRIMLER'),
(N'SOZLESME_GONDERIM_LOGLARI'),
(N'SOZLESME_KABULLERI'),
(N'TELEFON_DOGRULAMA_TOKENLARI'),
(N'WHATSAPP_MESAJ_LOGLARI'),
(N'YORUM_KALDIRMA_TALEPLERI'),
(N'YORUMLAR');

DECLARE @TableName sysname;
DECLARE @Sql nvarchar(max);

DECLARE clear_cursor CURSOR LOCAL FAST_FORWARD FOR
SELECT TableName
FROM @ClearTables
WHERE OBJECT_ID(N'dbo.' + QUOTENAME(TableName), N'U') IS NOT NULL;

OPEN clear_cursor;
FETCH NEXT FROM clear_cursor INTO @TableName;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @Sql = N'DELETE FROM dbo.' + QUOTENAME(@TableName) + N';';
    EXEC sp_executesql @Sql;
    FETCH NEXT FROM clear_cursor INTO @TableName;
END;

CLOSE clear_cursor;
DEALLOCATE clear_cursor;

IF OBJECT_ID(N'dbo.ADMIN_KULLANICI_ROLLER', N'U') IS NOT NULL
BEGIN
    DELETE FROM dbo.ADMIN_KULLANICI_ROLLER
    WHERE ADMIN_KULLANICI_ID <> @AdminUserId;
END;

IF OBJECT_ID(N'dbo.KULLANICI_ROLLERI', N'U') IS NOT NULL
BEGIN
    DELETE FROM dbo.KULLANICI_ROLLERI
    WHERE KULLANICI_ID <> @AdminUserId;

    UPDATE dbo.KULLANICI_ROLLERI
    SET ATAYAN_KULLANICI_ID = @AdminUserId
    WHERE KULLANICI_ID = @AdminUserId
      AND ATAYAN_KULLANICI_ID IS NOT NULL
      AND ATAYAN_KULLANICI_ID <> @AdminUserId;
END;

DELETE FROM dbo.KULLANICILAR
WHERE ID <> @AdminUserId;

UPDATE dbo.KULLANICILAR
SET ROL = N'admin',
    HESAP_DURUMU = 1,
    EPOSTA_DOGRULAMA_TARIHI = COALESCE(EPOSTA_DOGRULAMA_TARIHI, SYSUTCDATETIME()),
    GUNCELLENME_TARIHI = SYSUTCDATETIME()
WHERE ID = @AdminUserId;

EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL';

COMMIT TRANSACTION;

SELECT
    (SELECT COUNT(*) FROM dbo.KULLANICILAR) AS KULLANICI_SAYISI,
    (SELECT COUNT(*) FROM dbo.OTELLER) AS OTEL_SAYISI,
    (SELECT COUNT(*) FROM dbo.ODA_TIPLERI) AS ODA_TIPI_SAYISI,
    (SELECT COUNT(*) FROM dbo.REZERVASYONLAR) AS REZERVASYON_SAYISI;
