/* dbo.ULKELER: dunya ulke listesi (UTF-8) — sqlcmd -f 65001 ile calistirin */
IF OBJECT_ID(N'dbo.ULKELER', N'U') IS NULL RETURN;
SET NOCOUNT ON;
GO

IF COL_LENGTH(N'dbo.ULKELER', N'BAYRAK_IKON_KODU') IS NULL
BEGIN
    ALTER TABLE [dbo].[ULKELER] ADD [BAYRAK_IKON_KODU] nvarchar(16) NULL;
END
GO

IF OBJECT_ID('tempdb..#ulke_seed') IS NOT NULL DROP TABLE #ulke_seed;
CREATE TABLE #ulke_seed (
    ISO2 nchar(2) NOT NULL PRIMARY KEY,
    ULKE_ADI nvarchar(150) NOT NULL,
    ISO3 nchar(3) NOT NULL,
    BAYRAK_IKON_KODU nvarchar(16) NOT NULL,
    VARSAYILAN_ULKE bit NOT NULL,
    AKTIF_MI bit NOT NULL
);
GO

INSERT INTO #ulke_seed (ISO2, ULKE_ADI, ISO3, BAYRAK_IKON_KODU, VARSAYILAN_ULKE, AKTIF_MI) VALUES
(N'TR',N'Türkiye',N'TUR',N'tr',1,1),
(N'UM',N'ABD Küçük Harici Adaları',N'UMI',N'um',0,1),
(N'VI',N'ABD Virjin Adaları',N'VIR',N'vi',0,1),
(N'AF',N'Afganistan',N'AFG',N'af',0,1),
(N'DE',N'Almanya',N'DEU',N'de',0,1),
(N'US',N'Amerika Birleşik Devletleri',N'USA',N'us',0,1),
(N'AS',N'Amerikan Samoası',N'ASM',N'as',0,1),
(N'AD',N'Andorra',N'AND',N'ad',0,1),
(N'AO',N'Angola',N'AGO',N'ao',0,1),
(N'AI',N'Anguilla',N'AIA',N'ai',0,1),
(N'AQ',N'Antarktika',N'ATA',N'aq',0,1),
(N'AG',N'Antigua ve Barbuda',N'ATG',N'ag',0,1),
(N'AR',N'Arjantin',N'ARG',N'ar',0,1),
(N'AL',N'Arnavutluk',N'ALB',N'al',0,1),
(N'AW',N'Aruba',N'ABW',N'aw',0,1),
(N'AU',N'Avustralya',N'AUS',N'au',0,1),
(N'AT',N'Avusturya',N'AUT',N'at',0,1),
(N'AZ',N'Azerbaycan',N'AZE',N'az',0,1),
(N'BS',N'Bahamalar',N'BHS',N'bs',0,1),
(N'BH',N'Bahreyn',N'BHR',N'bh',0,1),
(N'BD',N'Bangladeş',N'BGD',N'bd',0,1),
(N'BB',N'Barbados',N'BRB',N'bb',0,1),
(N'EH',N'Batı Sahra',N'ESH',N'eh',0,1),
(N'BY',N'Belarus',N'BLR',N'by',0,1),
(N'BZ',N'Belize',N'BLZ',N'bz',0,1),
(N'BE',N'Belçika',N'BEL',N'be',0,1),
(N'BJ',N'Benin',N'BEN',N'bj',0,1),
(N'BM',N'Bermuda',N'BMU',N'bm',0,1),
(N'AE',N'Birleşik Arap Emirlikleri',N'ARE',N'ae',0,1),
(N'GB',N'Birleşik Krallık',N'GBR',N'gb',0,1),
(N'BO',N'Bolivya',N'BOL',N'bo',0,1),
(N'BA',N'Bosna-Hersek',N'BIH',N'ba',0,1),
(N'BW',N'Botsvana',N'BWA',N'bw',0,1),
(N'BV',N'Bouvet Adası',N'BVT',N'bv',0,1),
(N'BR',N'Brezilya',N'BRA',N'br',0,1),

(N'IO',N'Britanya Hint Okyanusu Toprakları',N'IOT',N'io',0,1),
(N'VG',N'Britanya Virjin Adaları',N'VGB',N'vg',0,1),
(N'BN',N'Brunei',N'BRN',N'bn',0,1),
(N'BG',N'Bulgaristan',N'BGR',N'bg',0,1),
(N'BF',N'Burkina Faso',N'BFA',N'bf',0,1),
(N'BI',N'Burundi',N'BDI',N'bi',0,1),
(N'BT',N'Butan',N'BTN',N'bt',0,1),
(N'CV',N'Cabo Verde',N'CPV',N'cv',0,1),
(N'KY',N'Cayman Adaları',N'CYM',N'ky',0,1),
(N'GI',N'Cebelitarık',N'GIB',N'gi',0,1),
(N'DZ',N'Cezayir',N'DZA',N'dz',0,1),
(N'CX',N'Christmas Adası',N'CXR',N'cx',0,1),
(N'DJ',N'Cibuti',N'DJI',N'dj',0,1),
(N'CC',N'Cocos (Keeling) Adaları',N'CCK',N'cc',0,1),
(N'CK',N'Cook Adaları',N'COK',N'ck',0,1),
(N'CW',N'Curaçao',N'CUW',N'cw',0,1),
(N'CI',N'Côte d’Ivoire',N'CIV',N'ci',0,1),
(N'DK',N'Danimarka',N'DNK',N'dk',0,1),
(N'DO',N'Dominik Cumhuriyeti',N'DOM',N'do',0,1),
(N'DM',N'Dominika',N'DMA',N'dm',0,1),
(N'EC',N'Ekvador',N'ECU',N'ec',0,1),
(N'GQ',N'Ekvator Ginesi',N'GNQ',N'gq',0,1),
(N'SV',N'El Salvador',N'SLV',N'sv',0,1),
(N'ID',N'Endonezya',N'IDN',N'id',0,1),
(N'ER',N'Eritre',N'ERI',N'er',0,1),
(N'AM',N'Ermenistan',N'ARM',N'am',0,1),
(N'EE',N'Estonya',N'EST',N'ee',0,1),
(N'SZ',N'Esvatini',N'SWZ',N'sz',0,1),
(N'ET',N'Etiyopya',N'ETH',N'et',0,1),
(N'FK',N'Falkland Adaları',N'FLK',N'fk',0,1),
(N'FO',N'Faroe Adaları',N'FRO',N'fo',0,1),
(N'MA',N'Fas',N'MAR',N'ma',0,1),
(N'FJ',N'Fiji',N'FJI',N'fj',0,1),
(N'PH',N'Filipinler',N'PHL',N'ph',0,1),
(N'PS',N'Filistin Bölgeleri',N'PSE',N'ps',0,1),

(N'FI',N'Finlandiya',N'FIN',N'fi',0,1),
(N'FR',N'Fransa',N'FRA',N'fr',0,1),
(N'GF',N'Fransız Guyanası',N'GUF',N'gf',0,1),
(N'TF',N'Fransız Güney Toprakları',N'ATF',N'tf',0,1),
(N'PF',N'Fransız Polinezyası',N'PYF',N'pf',0,1),
(N'GA',N'Gabon',N'GAB',N'ga',0,1),
(N'GM',N'Gambiya',N'GMB',N'gm',0,1),
(N'GH',N'Gana',N'GHA',N'gh',0,1),
(N'GN',N'Gine',N'GIN',N'gn',0,1),
(N'GW',N'Gine-Bissau',N'GNB',N'gw',0,1),
(N'GD',N'Grenada',N'GRD',N'gd',0,1),
(N'GL',N'Grönland',N'GRL',N'gl',0,1),
(N'GP',N'Guadeloupe',N'GLP',N'gp',0,1),
(N'GU',N'Guam',N'GUM',N'gu',0,1),
(N'GT',N'Guatemala',N'GTM',N'gt',0,1),
(N'GG',N'Guernsey',N'GGY',N'gg',0,1),
(N'GY',N'Guyana',N'GUY',N'gy',0,1),
(N'ZA',N'Güney Afrika',N'ZAF',N'za',0,1),
(N'GS',N'Güney Georgia ve Güney Sandwich Adaları',N'SGS',N'gs',0,1),
(N'KR',N'Güney Kore',N'KOR',N'kr',0,1),
(N'SS',N'Güney Sudan',N'SSD',N'ss',0,1),
(N'GE',N'Gürcistan',N'GEO',N'ge',0,1),
(N'HT',N'Haiti',N'HTI',N'ht',0,1),
(N'HM',N'Heard Adası ve McDonald Adaları',N'HMD',N'hm',0,1),
(N'IN',N'Hindistan',N'IND',N'in',0,1),
(N'NL',N'Hollanda',N'NLD',N'nl',0,1),
(N'HN',N'Honduras',N'HND',N'hn',0,1),
(N'HR',N'Hırvatistan',N'HRV',N'hr',0,1),
(N'IQ',N'Irak',N'IRQ',N'iq',0,1),
(N'JM',N'Jamaika',N'JAM',N'jm',0,1),
(N'JP',N'Japonya',N'JPN',N'jp',0,1),
(N'JE',N'Jersey',N'JEY',N'je',0,1),
(N'KH',N'Kamboçya',N'KHM',N'kh',0,1),
(N'CM',N'Kamerun',N'CMR',N'cm',0,1),
(N'CA',N'Kanada',N'CAN',N'ca',0,1),

(N'ME',N'Karadağ',N'MNE',N'me',0,1),
(N'BQ',N'Karayip Hollandası',N'BES',N'bq',0,1),
(N'QA',N'Katar',N'QAT',N'qa',0,1),
(N'KZ',N'Kazakistan',N'KAZ',N'kz',0,1),
(N'KE',N'Kenya',N'KEN',N'ke',0,1),
(N'KI',N'Kiribati',N'KIR',N'ki',0,1),
(N'CO',N'Kolombiya',N'COL',N'co',0,1),
(N'KM',N'Komorlar',N'COM',N'km',0,1),
(N'CG',N'Kongo - Brazavil',N'COG',N'cg',0,1),
(N'CD',N'Kongo - Kinşasa',N'COD',N'cd',0,1),
(N'CR',N'Kosta Rika',N'CRI',N'cr',0,1),
(N'KW',N'Kuveyt',N'KWT',N'kw',0,1),
(N'KP',N'Kuzey Kore',N'PRK',N'kp',0,1),
(N'MK',N'Kuzey Makedonya',N'MKD',N'mk',0,1),
(N'MP',N'Kuzey Mariana Adaları',N'MNP',N'mp',0,1),
(N'CU',N'Küba',N'CUB',N'cu',0,1),
(N'CY',N'Kıbrıs',N'CYP',N'cy',0,1),
(N'KG',N'Kırgızistan',N'KGZ',N'kg',0,1),
(N'LA',N'Laos',N'LAO',N'la',0,1),
(N'LS',N'Lesotho',N'LSO',N'ls',0,1),
(N'LV',N'Letonya',N'LVA',N'lv',0,1),
(N'LR',N'Liberya',N'LBR',N'lr',0,1),
(N'LY',N'Libya',N'LBY',N'ly',0,1),
(N'LI',N'Liechtenstein',N'LIE',N'li',0,1),
(N'LT',N'Litvanya',N'LTU',N'lt',0,1),
(N'LB',N'Lübnan',N'LBN',N'lb',0,1),
(N'LU',N'Lüksemburg',N'LUX',N'lu',0,1),
(N'HU',N'Macaristan',N'HUN',N'hu',0,1),
(N'MG',N'Madagaskar',N'MDG',N'mg',0,1),
(N'MW',N'Malavi',N'MWI',N'mw',0,1),
(N'MV',N'Maldivler',N'MDV',N'mv',0,1),
(N'MY',N'Malezya',N'MYS',N'my',0,1),
(N'ML',N'Mali',N'MLI',N'ml',0,1),
(N'MT',N'Malta',N'MLT',N'mt',0,1),
(N'IM',N'Man Adası',N'IMN',N'im',0,1),

(N'MH',N'Marshall Adaları',N'MHL',N'mh',0,1),
(N'MQ',N'Martinik',N'MTQ',N'mq',0,1),
(N'MU',N'Mauritius',N'MUS',N'mu',0,1),
(N'YT',N'Mayotte',N'MYT',N'yt',0,1),
(N'MX',N'Meksika',N'MEX',N'mx',0,1),
(N'FM',N'Mikronezya',N'FSM',N'fm',0,1),
(N'MD',N'Moldova',N'MDA',N'md',0,1),
(N'MC',N'Monako',N'MCO',N'mc',0,1),
(N'MS',N'Montserrat',N'MSR',N'ms',0,1),
(N'MR',N'Moritanya',N'MRT',N'mr',0,1),
(N'MZ',N'Mozambik',N'MOZ',N'mz',0,1),
(N'MN',N'Moğolistan',N'MNG',N'mn',0,1),
(N'MM',N'Myanmar (Burma)',N'MMR',N'mm',0,1),
(N'EG',N'Mısır',N'EGY',N'eg',0,1),
(N'NA',N'Namibya',N'NAM',N'na',0,1),
(N'NR',N'Nauru',N'NRU',N'nr',0,1),
(N'NP',N'Nepal',N'NPL',N'np',0,1),
(N'NE',N'Nijer',N'NER',N'ne',0,1),
(N'NG',N'Nijerya',N'NGA',N'ng',0,1),
(N'NI',N'Nikaragua',N'NIC',N'ni',0,1),
(N'NU',N'Niue',N'NIU',N'nu',0,1),
(N'NF',N'Norfolk Adası',N'NFK',N'nf',0,1),
(N'NO',N'Norveç',N'NOR',N'no',0,1),
(N'CF',N'Orta Afrika Cumhuriyeti',N'CAF',N'cf',0,1),
(N'PK',N'Pakistan',N'PAK',N'pk',0,1),
(N'PW',N'Palau',N'PLW',N'pw',0,1),
(N'PA',N'Panama',N'PAN',N'pa',0,1),
(N'PG',N'Papua Yeni Gine',N'PNG',N'pg',0,1),
(N'PY',N'Paraguay',N'PRY',N'py',0,1),
(N'PE',N'Peru',N'PER',N'pe',0,1),
(N'PN',N'Pitcairn Adaları',N'PCN',N'pn',0,1),
(N'PL',N'Polonya',N'POL',N'pl',0,1),
(N'PT',N'Portekiz',N'PRT',N'pt',0,1),
(N'PR',N'Porto Riko',N'PRI',N'pr',0,1),
(N'RE',N'Reunion',N'REU',N're',0,1),

(N'RO',N'Romanya',N'ROU',N'ro',0,1),
(N'RW',N'Ruanda',N'RWA',N'rw',0,1),
(N'RU',N'Rusya',N'RUS',N'ru',0,1),
(N'BL',N'Saint Barthelemy',N'BLM',N'bl',0,1),
(N'SH',N'Saint Helena',N'SHN',N'sh',0,1),
(N'KN',N'Saint Kitts ve Nevis',N'KNA',N'kn',0,1),
(N'LC',N'Saint Lucia',N'LCA',N'lc',0,1),
(N'MF',N'Saint Martin',N'MAF',N'mf',0,1),
(N'PM',N'Saint Pierre ve Miquelon',N'SPM',N'pm',0,1),
(N'VC',N'Saint Vincent ve Grenadinler',N'VCT',N'vc',0,1),
(N'WS',N'Samoa',N'WSM',N'ws',0,1),
(N'SM',N'San Marino',N'SMR',N'sm',0,1),
(N'ST',N'Sao Tome ve Principe',N'STP',N'st',0,1),
(N'SN',N'Senegal',N'SEN',N'sn',0,1),
(N'SC',N'Seyşeller',N'SYC',N'sc',0,1),
(N'SL',N'Sierra Leone',N'SLE',N'sl',0,1),
(N'SG',N'Singapur',N'SGP',N'sg',0,1),
(N'SX',N'Sint Maarten',N'SXM',N'sx',0,1),
(N'SK',N'Slovakya',N'SVK',N'sk',0,1),
(N'SI',N'Slovenya',N'SVN',N'si',0,1),
(N'SB',N'Solomon Adaları',N'SLB',N'sb',0,1),
(N'SO',N'Somali',N'SOM',N'so',0,1),
(N'LK',N'Sri Lanka',N'LKA',N'lk',0,1),
(N'SD',N'Sudan',N'SDN',N'sd',0,1),
(N'SR',N'Surinam',N'SUR',N'sr',0,1),
(N'SY',N'Suriye',N'SYR',N'sy',0,1),
(N'SA',N'Suudi Arabistan',N'SAU',N'sa',0,1),
(N'SJ',N'Svalbard ve Jan Mayen',N'SJM',N'sj',0,1),
(N'RS',N'Sırbistan',N'SRB',N'rs',0,1),
(N'TJ',N'Tacikistan',N'TJK',N'tj',0,1),
(N'TZ',N'Tanzanya',N'TZA',N'tz',0,1),
(N'TH',N'Tayland',N'THA',N'th',0,1),
(N'TW',N'Tayvan',N'TWN',N'tw',0,1),
(N'TL',N'Timor-Leste',N'TLS',N'tl',0,1),
(N'TG',N'Togo',N'TGO',N'tg',0,1),

(N'TK',N'Tokelau',N'TKL',N'tk',0,1),
(N'TO',N'Tonga',N'TON',N'to',0,1),
(N'TT',N'Trinidad ve Tobago',N'TTO',N'tt',0,1),
(N'TN',N'Tunus',N'TUN',N'tn',0,1),
(N'TC',N'Turks ve Caicos Adaları',N'TCA',N'tc',0,1),
(N'TV',N'Tuvalu',N'TUV',N'tv',0,1),
(N'TM',N'Türkmenistan',N'TKM',N'tm',0,1),
(N'UG',N'Uganda',N'UGA',N'ug',0,1),
(N'UA',N'Ukrayna',N'UKR',N'ua',0,1),
(N'OM',N'Umman',N'OMN',N'om',0,1),
(N'UY',N'Uruguay',N'URY',N'uy',0,1),
(N'VU',N'Vanuatu',N'VUT',N'vu',0,1),
(N'VA',N'Vatikan',N'VAT',N'va',0,1),
(N'VE',N'Venezuela',N'VEN',N've',0,1),
(N'VN',N'Vietnam',N'VNM',N'vn',0,1),
(N'WF',N'Wallis ve Futuna',N'WLF',N'wf',0,1),
(N'YE',N'Yemen',N'YEM',N'ye',0,1),
(N'NC',N'Yeni Kaledonya',N'NCL',N'nc',0,1),
(N'NZ',N'Yeni Zelanda',N'NZL',N'nz',0,1),
(N'GR',N'Yunanistan',N'GRC',N'gr',0,1),
(N'ZM',N'Zambiya',N'ZMB',N'zm',0,1),
(N'ZW',N'Zimbabve',N'ZWE',N'zw',0,1),
(N'AX',N'Åland Adaları',N'ALA',N'ax',0,1),
(N'TD',N'Çad',N'TCD',N'td',0,1),
(N'CZ',N'Çekya',N'CZE',N'cz',0,1),
(N'CN',N'Çin',N'CHN',N'cn',0,1),
(N'HK',N'Çin Hong Kong ÖİB',N'HKG',N'hk',0,1),
(N'MO',N'Çin Makao ÖİB',N'MAC',N'mo',0,1),
(N'UZ',N'Özbekistan',N'UZB',N'uz',0,1),
(N'JO',N'Ürdün',N'JOR',N'jo',0,1),
(N'IR',N'İran',N'IRN',N'ir',0,1),
(N'IE',N'İrlanda',N'IRL',N'ie',0,1),
(N'ES',N'İspanya',N'ESP',N'es',0,1),
(N'IL',N'İsrail',N'ISR',N'il',0,1),
(N'SE',N'İsveç',N'SWE',N'se',0,1),

(N'CH',N'İsviçre',N'CHE',N'ch',0,1),
(N'IT',N'İtalya',N'ITA',N'it',0,1),
(N'IS',N'İzlanda',N'ISL',N'is',0,1),
(N'CL',N'Şili',N'CHL',N'cl',0,1);

GO

MERGE [dbo].[ULKELER] AS t
USING #ulke_seed AS s ON t.[ISO2_KODU] = s.[ISO2]
WHEN MATCHED THEN UPDATE SET
    [ULKE_ADI] = s.[ULKE_ADI],
    [ISO3_KODU] = s.[ISO3],
    [BAYRAK_IKON_KODU] = s.[BAYRAK_IKON_KODU],
    [VARSAYILAN_ULKE] = s.[VARSAYILAN_ULKE],
    [AKTIF_MI] = s.[AKTIF_MI],
    [GUNCELLENME_TARIHI] = sysutcdatetime()
WHEN NOT MATCHED THEN INSERT ([ULKE_ADI],[ISO2_KODU],[ISO3_KODU],[BAYRAK_IKON_KODU],[VARSAYILAN_ULKE],[AKTIF_MI])
    VALUES (s.[ULKE_ADI], s.[ISO2], s.[ISO3], s.[BAYRAK_IKON_KODU], s.[VARSAYILAN_ULKE], s.[AKTIF_MI]);
GO

-- Toplam: 249 ulke
