-- Idempotent: DEMO-ANTALYA-2026 + DEMO-KAPADOKYA-2026 — tam demo oteller (2'şer oda, 31 günlük fiyat)
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET DATEFIRST 1;

DECLARE @TrUlkeId bigint = (SELECT TOP (1) [ID] FROM [dbo].[ULKELER] WHERE [ISO2_KODU] = N'TR' ORDER BY [ID]);
IF @TrUlkeId IS NULL BEGIN RAISERROR(N'ULKELER eksik.', 16, 1); RETURN; END;

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_TIPLERI] WHERE [KOD] = N'HOTEL')
    INSERT INTO [dbo].[OTEL_TIPLERI] ([KOD],[TIP_ADI],[ACIKLAMA],[AKTIF_MI],[SIRALAMA]) VALUES (N'HOTEL',N'OTEL',N'Demo otel tipi',1,1);

DECLARE @HotelTypeId int = (SELECT TOP (1) [ID] FROM [dbo].[OTEL_TIPLERI] WHERE [KOD]=N'HOTEL' ORDER BY [ID]);
DECLARE @PartnerUserId bigint = (SELECT TOP (1) [ID] FROM [dbo].[KULLANICILAR] WHERE [EPOSTA]=N'ork-demo-partner@otelturizm.local');
DECLARE @PartnerId bigint = (SELECT TOP (1) [ID] FROM [dbo].[PARTNER_DETAYLARI] WHERE [VERGI_NUMARASI]=N'ORK-DEMO-0001');
DECLARE @DemoPasswordHash nvarchar(64) = LOWER(CONVERT(VARCHAR(64), HASHBYTES('SHA2_256', N'Demo123!'), 2));
DECLARE @Today date = CAST(SYSUTCDATETIME() AS date);
DECLARE @PriceDays int = 31;
DECLARE @WeekendIndirimId bigint;
DECLARE @ErkenIndirimId bigint;
DECLARE @KampanyaId bigint = (SELECT TOP (1) [ID] FROM [dbo].[KAMPANYALAR] WHERE [KAMPANYA_KODU]=N'KMP-2026-SEHIR');
DECLARE @KampanyaBas datetime2(0) = COALESCE((SELECT [BASLANGIC_TARIHI] FROM [dbo].[KAMPANYALAR] WHERE [ID]=@KampanyaId), CAST(N'2026-01-01' AS datetime2(0)));
DECLARE @KampanyaBit datetime2(0) = COALESCE((SELECT [BITIS_TARIHI] FROM [dbo].[KAMPANYALAR] WHERE [ID]=@KampanyaId), CAST(N'2035-12-31 23:59:59' AS datetime2(0)));

IF @PartnerUserId IS NULL BEGIN
    INSERT INTO [dbo].[KULLANICILAR]([AD_SOYAD],[EPOSTA],[TELEFON],[SIFRE],[ROL],[HESAP_DURUMU],[KAYIT_KAYNAGI],[OLUSTURULMA_TARIHI])
    VALUES(N'Orkestra Demo Partner',N'ork-demo-partner@otelturizm.local',N'5000000099',@DemoPasswordHash,N'partner',1,N'DemoHotelSeed',SYSUTCDATETIME());
    SET @PartnerUserId = SCOPE_IDENTITY();
END;
IF @PartnerId IS NULL BEGIN
    INSERT INTO [dbo].[PARTNER_DETAYLARI]([KULLANICI_ID],[FIRMA_UNVANI],[FIRMA_TURU],[VERGI_DAIRESI],[VERGI_NUMARASI],[FATURA_ADRESI],[FATURA_IL],[FATURA_ILCE],[YETKILI_AD_SOYAD],[YETKILI_TC_NO],[YETKILI_TELEFON],[YETKILI_EPOSTA],[BANKA_ADI],[IBAN],[HESAP_SAHIBI_ADI],[ONAY_DURUMU],[ONAY_TARIHI],[AKTIF_MI],[OTEL_TIPI_ID],[OLUSTURULMA_TARIHI])
    VALUES(@PartnerUserId,N'Orkestra Demo Partner A.S.',N'Limited Sirketi',N'Demo VD',N'ORK-DEMO-0001',N'Demo Adres',N'Istanbul',N'Beyoglu',N'Orkestra Demo Partner',N'11111111111',N'5000000099',N'ork-demo-partner@otelturizm.local',N'Demo Bank',N'TR000000000000000000000001',N'Orkestra Demo Partner',N'Onaylandi',SYSUTCDATETIME(),1,@HotelTypeId,SYSUTCDATETIME());
    SET @PartnerId = SCOPE_IDENTITY();
END;

IF OBJECT_ID(N'dbo.FIYAT_INDIRIMLERI', N'U') IS NOT NULL BEGIN
    SELECT @WeekendIndirimId=[ID] FROM [dbo].[FIYAT_INDIRIMLERI] WHERE [INDIRIM_ADI]=N'Hafta Sonu Demo';
    IF @WeekendIndirimId IS NULL BEGIN INSERT INTO [dbo].[FIYAT_INDIRIMLERI]([INDIRIM_ADI],[KISA_ACIKLAMA],[IKON_CLASS],[RENK_KODU],[AKTIF_MI],[SIRALAMA]) VALUES(N'Hafta Sonu Demo',N'Cumartesi-Pazar %15',N'fa-calendar-week',N'#0F766E',1,10); SET @WeekendIndirimId=SCOPE_IDENTITY(); END;
    SELECT @ErkenIndirimId=[ID] FROM [dbo].[FIYAT_INDIRIMLERI] WHERE [INDIRIM_ADI]=N'Demo Erken Rezervasyon';
    IF @ErkenIndirimId IS NULL BEGIN INSERT INTO [dbo].[FIYAT_INDIRIMLERI]([INDIRIM_ADI],[KISA_ACIKLAMA],[IKON_CLASS],[RENK_KODU],[AKTIF_MI],[SIRALAMA],[GORSEL_URL]) VALUES(N'Demo Erken Rezervasyon',N'14+ gun %20',N'fa-clock',N'#B45309',1,5,N'/assets/img/campaigns/early-bird.svg'); SET @ErkenIndirimId=SCOPE_IDENTITY(); END;
END;

IF OBJECT_ID(N'dbo.ODA_OZELLIKLERI', N'U') IS NOT NULL BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ODA_OZELLIKLERI] WHERE [OZELLIK_ADI]=N'Klima') INSERT INTO [dbo].[ODA_OZELLIKLERI]([KATEGORI],[OZELLIK_ADI],[OZELLIK_IKON],[SIRALAMA],[AKTIF_MI]) VALUES(N'Konfor',N'Klima',N'fa-fan',10,1);
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ODA_OZELLIKLERI] WHERE [OZELLIK_ADI]=N'Minibar') INSERT INTO [dbo].[ODA_OZELLIKLERI]([KATEGORI],[OZELLIK_ADI],[OZELLIK_IKON],[SIRALAMA],[AKTIF_MI]) VALUES(N'Konfor',N'Minibar',N'fa-wine-bottle',20,1);
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ODA_OZELLIKLERI] WHERE [OZELLIK_ADI]=N'LED TV') INSERT INTO [dbo].[ODA_OZELLIKLERI]([KATEGORI],[OZELLIK_ADI],[OZELLIK_IKON],[SIRALAMA],[AKTIF_MI]) VALUES(N'Teknoloji',N'LED TV',N'fa-tv',30,1);
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ODA_OZELLIKLERI] WHERE [OZELLIK_ADI]=N'Sac Kurutma Makinesi') INSERT INTO [dbo].[ODA_OZELLIKLERI]([KATEGORI],[OZELLIK_ADI],[OZELLIK_IKON],[SIRALAMA],[AKTIF_MI]) VALUES(N'Banyo',N'Sac Kurutma Makinesi',N'fa-wind',40,1);
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ODA_OZELLIKLERI] WHERE [OZELLIK_ADI]=N'Kasa') INSERT INTO [dbo].[ODA_OZELLIKLERI]([KATEGORI],[OZELLIK_ADI],[OZELLIK_IKON],[SIRALAMA],[AKTIF_MI]) VALUES(N'Guvenlik',N'Kasa',N'fa-vault',50,1);
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ODA_OZELLIKLERI] WHERE [OZELLIK_ADI]=N'Nespresso') INSERT INTO [dbo].[ODA_OZELLIKLERI]([KATEGORI],[OZELLIK_ADI],[OZELLIK_IKON],[SIRALAMA],[AKTIF_MI]) VALUES(N'Konfor',N'Nespresso',N'fa-mug-hot',55,1);
END;

DECLARE @FullOzellikKodlari TABLE (Kod nvarchar(80) NOT NULL PRIMARY KEY);
INSERT INTO @FullOzellikKodlari (Kod) VALUES
(N'RESEPSIYON_24_SAAT'),(N'UCRETSIZ_WIFI'),(N'ASANSOR'),(N'KLIMA'),(N'GUNLUK_TEMIZLIK'),(N'RESTORAN'),(N'KAHVALTI'),(N'ACIK_BUFE'),(N'ODA_SERVISI'),(N'BAR'),
(N'MINIBAR'),(N'EMANET_KASASI'),(N'TV'),(N'KAHVE_CAY_SETI'),(N'BALKON'),(N'SPA'),(N'SAUNA'),(N'HAMAM'),(N'FITNESS'),(N'HAVUZ_KAPALI'),(N'COCUK_HAVUZU'),
(N'AILE_ODASI'),(N'COCUK_KULUBU'),(N'BEBEK_YATAGI'),(N'ENGELLI_ERISIMI'),(N'ENGELLI_BANYO'),(N'OTOPARK'),(N'HAVAALANI_SERVISI'),(N'VALE_HIZMETI'),(N'SEHIR_ICI_TRANSFER'),
(N'TOPLANTI_ODASI'),(N'IS_MERKEZI'),(N'KARTLI_GIRIS'),(N'KAMERA_SISTEMI');

-- ANTALYA
DECLARE @AntalyaIlId bigint = (SELECT TOP (1) [ID] FROM [dbo].[ILLER] WHERE [IL_ADI] LIKE N'Antalya%' ORDER BY [ID]);
DECLARE @KonyaaltiIlceId bigint = (SELECT TOP (1) [ID] FROM [dbo].[ILCELER] WHERE [IL_ID]=@AntalyaIlId AND ([SEO_SLUG]=N'konyaalti' OR [ILCE_ADI] LIKE N'Konyaalt%') ORDER BY [ID]);
IF @AntalyaIlId IS NULL OR @KonyaaltiIlceId IS NULL BEGIN RAISERROR(N'Antalya geo eksik.',16,1); RETURN; END;

DECLARE @OtelKodu nvarchar(32)=N'DEMO-ANTALYA-2026', @HotelId bigint, @Room1Id bigint, @Room2Id bigint;
DECLARE @StdFiyat decimal(10,2)=6800, @DlxFiyat decimal(10,2)=8950, @d int, @Tarih date, @IsWeekend bit, @Indirimli decimal(10,2);
DECLARE @RoomId bigint, @CoverUrl nvarchar(500), @Url nvarchar(500), @RoomCover nvarchar(500), @RoomUrl2 nvarchar(500), @i int;
DECLARE @AntRooms TABLE (RoomId bigint NOT NULL PRIMARY KEY);

SELECT @HotelId=[ID] FROM [dbo].[OTELLER] WHERE [OTEL_KODU]=@OtelKodu;
IF @HotelId IS NULL BEGIN
    INSERT INTO [dbo].[OTELLER]([OTEL_KODU],[PARTNER_ID],[KULLANICI_ID],[OTEL_ADI],[OTEL_TURU],[OTEL_TIPI_ID],[YILDIZ_SAYISI],[ULKE],[SEHIR],[ILCE],[MAHALLE],[TAM_ADRES],[ENLEM],[BOYLAM],[ULKE_ID],[SEHIR_ID],[ILCE_ID],[TELEFON_1],[EPOSTA],[REZERVASYON_TELEFONU],[SATIS_KONTAK_ADI],[SATIS_KONTAK_TELEFONU],[SATIS_KONTAK_EPOSTA],[CHECK_IN_SAATI],[CHECK_OUT_SAATI],[TOPLAM_ODA_SAYISI],[KISA_ACIKLAMA],[UZUN_ACIKLAMA],[KONUM_ACIKLAMASI],[VARSAYILAN_KOMISYON_ORANI],[ODEME_VADESI],[ODEME_YONTEMI],[FATURA_KESIM_TURU],[ORTALAMA_PUAN],[TOPLAM_YORUM_SAYISI],[YAYIN_DURUMU],[ONAY_DURUMU],[ONAY_TARIHI],[ONE_CIKAN_OTEL],[TAVSIYE_EDILEN_OTEL],[POPULERLIK_SIRASI],[OLUSTURULMA_TARIHI])
    VALUES(@OtelKodu,@PartnerId,@PartnerUserId,N'Akdeniz Konyaalti Sahil Hotel',N'Hotel',@HotelTypeId,5,N'Turkiye',N'Antalya',N'Konyaalti',N'Lara Sahil',N'Konyaalti Sahil Yolu No:88 Antalya',36.8565,30.6063,@TrUlkeId,@AntalyaIlId,@KonyaaltiIlceId,N'2425556600',N'rez.antalya@demo.otelturizm.local',N'2425556601',N'Antalya Demo',N'2425556602',N'ork-demo-partner@otelturizm.local','14:00:00','12:00:00',56,N'Konyaalti sahil bandinda deniz manzarali gelistirme demo oteli.',N'Akdeniz Konyaalti Sahil Hotel, Antalya sahil hattinda acik-kapali havuz, spa ve deniz manzarali odalarla konfor sunar.',N'Konyaalti plajina 2 dk yuruyus.',15,N'Cikis Gunu',N'Online',N'Otel Keser',8.7,0,N'Yayında',N'Onaylandı',SYSUTCDATETIME(),1,1,95,SYSUTCDATETIME());
    SET @HotelId=SCOPE_IDENTITY();
END ELSE UPDATE [dbo].[OTELLER] SET [YAYIN_DURUMU]=N'Yayında',[ONAY_DURUMU]=N'Onaylandı',[ONE_CIKAN_OTEL]=1,[TAVSIYE_EDILEN_OTEL]=1 WHERE [ID]=@HotelId;

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_KULLANICI_SAHIPLIKLERI] WHERE [OTEL_ID]=@HotelId AND [KULLANICI_ID]=@PartnerUserId)
    INSERT INTO [dbo].[OTEL_KULLANICI_SAHIPLIKLERI]([OTEL_ID],[KULLANICI_ID],[PARTNER_ID],[ROL],[ANA_SORUMLU_MU],[AKTIF_MI],[OLUSTURULMA_TARIHI]) VALUES(@HotelId,@PartnerUserId,@PartnerId,N'owner',1,1,SYSUTCDATETIME());
IF OBJECT_ID(N'dbo.OTEL_KOSULLARI',N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_KOSULLARI] WHERE [OTEL_ID]=@HotelId)
    INSERT INTO [dbo].[OTEL_KOSULLARI]([OTEL_ID],[IPTAL_POLITIKASI_OZET],[DETAYLI_IPTAL_KOSULLARI],[UCRETSIZ_IPTAL_SURESI],[SIGARA_POLITIKASI],[EVCIL_HAYVAN_POLITIKASI],[COCUK_KABUL_YAS_ARALIGI],[KREDI_KARTI_ILE_ODEME_KABUL],[GUNCELLENME_TARIHI])
    VALUES(@HotelId,N'48 saat once ucretsiz iptal.',N'48 saat oncesi ucretsiz; gec iptalde ilk gece ucreti.',2,N'Odalarda sigara yasak.',N'Kucuk evcil hayvan ucretli.',N'0-12 yas ucretsiz',1,SYSUTCDATETIME());
IF OBJECT_ID(N'dbo.OTEL_OZELLIK_ILISKILERI',N'U') IS NOT NULL
    INSERT INTO [dbo].[OTEL_OZELLIK_ILISKILERI]([OTEL_ID],[OZELLIK_ID],[AKTIF_MI]) SELECT @HotelId,o.[ID],1 FROM [dbo].[OTEL_OZELLIKLERI] o INNER JOIN @FullOzellikKodlari k ON k.[Kod]=o.[OZELLIK_KODU] WHERE NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_OZELLIK_ILISKILERI] i WHERE i.[OTEL_ID]=@HotelId AND i.[OZELLIK_ID]=o.[ID]);

SELECT @Room1Id=[ID] FROM [dbo].[ODA_TIPLERI] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_KODU]=N'ANT-STD';
IF @Room1Id IS NULL BEGIN INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[ODA_METREKARE],[MANZARA_TIPI],[OZELLIKLER],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA]) VALUES(@HotelId,N'ANT-STD',N'Deniz Manzarali Standart',N'Standart Oda',2,2,1,N'Queen',1,26,N'Deniz',N'Klima, Minibar, LED TV, balkon',@StdFiyat,30,1,1); SET @Room1Id=SCOPE_IDENTITY(); END ELSE UPDATE [dbo].[ODA_TIPLERI] SET [STANDART_GECELIK_FIYAT]=@StdFiyat,[AKTIF_MI]=1 WHERE [ID]=@Room1Id;
SELECT @Room2Id=[ID] FROM [dbo].[ODA_TIPLERI] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_KODU]=N'ANT-SUIT';
IF @Room2Id IS NULL BEGIN INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[ODA_METREKARE],[BALKON_VAR_MI],[MANZARA_TIPI],[OZELLIKLER],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA]) VALUES(@HotelId,N'ANT-SUIT',N'Aile Suit Panoramik',N'Suit Oda',4,3,2,N'King + Sofa',2,42,1,N'Deniz',N'Jakuzi, Minibar, LED TV',@DlxFiyat,14,1,2); SET @Room2Id=SCOPE_IDENTITY(); END ELSE UPDATE [dbo].[ODA_TIPLERI] SET [STANDART_GECELIK_FIYAT]=@DlxFiyat,[AKTIF_MI]=1 WHERE [ID]=@Room2Id;

INSERT INTO @AntRooms VALUES(@Room1Id),(@Room2Id);
WHILE EXISTS(SELECT 1 FROM @AntRooms) BEGIN SELECT TOP(1) @RoomId=RoomId FROM @AntRooms ORDER BY RoomId;
    IF OBJECT_ID(N'dbo.ODA_TIPI_OZELLIKLERI',N'U') IS NOT NULL INSERT INTO [dbo].[ODA_TIPI_OZELLIKLERI]([ODA_TIP_ID],[OZELLIK_ID],[MIKTAR]) SELECT @RoomId,oo.[ID],1 FROM [dbo].[ODA_OZELLIKLERI] oo WHERE oo.[AKTIF_MI]=1 AND oo.[OZELLIK_ADI] IN (N'Klima',N'Minibar',N'LED TV',N'Sac Kurutma Makinesi',N'Kasa',N'Nespresso') AND NOT EXISTS (SELECT 1 FROM [dbo].[ODA_TIPI_OZELLIKLERI] x WHERE x.[ODA_TIP_ID]=@RoomId AND x.[OZELLIK_ID]=oo.[ID]);
    DELETE FROM @AntRooms WHERE RoomId=@RoomId; END;

SET @d=0; WHILE @d<@PriceDays BEGIN SET @Tarih=DATEADD(DAY,@d,@Today); SET @IsWeekend=CASE WHEN DATEPART(WEEKDAY,@Tarih) IN (6,7) THEN 1 ELSE 0 END;
    SET @Indirimli=CASE WHEN @IsWeekend=1 THEN CAST(@StdFiyat*0.85 AS decimal(10,2)) WHEN @d>=14 THEN CAST(@StdFiyat*0.80 AS decimal(10,2)) ELSE NULL END;
    IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_FIYAT_MUSAITLIK] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room1Id AND [TARIH]=@Tarih) INSERT INTO [dbo].[ODA_FIYAT_MUSAITLIK]([ODA_TIP_ID],[OTEL_ID],[TARIH],[GECELIK_FIYAT],[INDIRIMLI_FIYAT],[INDIRIM_ID],[KAMPANYA_ID],[TOPLAM_ODA_SAYISI],[KAPALI_SATIS],[KAMPANYA_ETIKETI]) VALUES(@Room1Id,@HotelId,@Tarih,@StdFiyat,@Indirimli,CASE WHEN @Indirimli IS NOT NULL AND @IsWeekend=1 THEN @WeekendIndirimId WHEN @Indirimli IS NOT NULL AND @d>=14 THEN @ErkenIndirimId ELSE NULL END,@KampanyaId,30,0,N'AKDENIZ');
    ELSE UPDATE [dbo].[ODA_FIYAT_MUSAITLIK] SET [GECELIK_FIYAT]=@StdFiyat,[INDIRIMLI_FIYAT]=@Indirimli,[KAPALI_SATIS]=0 WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room1Id AND [TARIH]=@Tarih;
    SET @Indirimli=CASE WHEN @IsWeekend=1 THEN CAST(@DlxFiyat*0.85 AS decimal(10,2)) WHEN @d>=14 THEN CAST(@DlxFiyat*0.80 AS decimal(10,2)) ELSE NULL END;
    IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_FIYAT_MUSAITLIK] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room2Id AND [TARIH]=@Tarih) INSERT INTO [dbo].[ODA_FIYAT_MUSAITLIK]([ODA_TIP_ID],[OTEL_ID],[TARIH],[GECELIK_FIYAT],[INDIRIMLI_FIYAT],[INDIRIM_ID],[KAMPANYA_ID],[TOPLAM_ODA_SAYISI],[KAPALI_SATIS],[KAMPANYA_ETIKETI]) VALUES(@Room2Id,@HotelId,@Tarih,@DlxFiyat,@Indirimli,CASE WHEN @Indirimli IS NOT NULL AND @IsWeekend=1 THEN @WeekendIndirimId WHEN @Indirimli IS NOT NULL AND @d>=14 THEN @ErkenIndirimId ELSE NULL END,@KampanyaId,14,0,N'AKDENIZ');
    ELSE UPDATE [dbo].[ODA_FIYAT_MUSAITLIK] SET [GECELIK_FIYAT]=@DlxFiyat,[INDIRIMLI_FIYAT]=@Indirimli,[KAPALI_SATIS]=0 WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room2Id AND [TARIH]=@Tarih;
    SET @d+=1; END;

IF @KampanyaId IS NOT NULL AND OBJECT_ID(N'dbo.KAMPANYA_OTELLER',N'U') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[KAMPANYA_OTELLER] WHERE [KAMPANYA_ID]=@KampanyaId AND [OTEL_ID]=@HotelId)
    INSERT INTO [dbo].[KAMPANYA_OTELLER]([KAMPANYA_ID],[OTEL_ID],[PARTNER_ID],[KATILIM_DURUMU],[KATILIM_KAYNAGI],[BASLANGIC_TARIHI],[BITIS_TARIHI],[ADMIN_ONAY_TARIHI],[PARTNER_ONAY_TARIHI],[OLUSTURULMA_TARIHI]) VALUES(@KampanyaId,@HotelId,@PartnerId,N'Aktif',N'AntalyaDemoSeed',@KampanyaBas,@KampanyaBit,SYSUTCDATETIME(),SYSUTCDATETIME(),SYSUTCDATETIME());

IF OBJECT_ID(N'dbo.OTEL_GORSELLERI',N'U') IS NOT NULL BEGIN
    SET @CoverUrl=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/hotel/demo-cover.webp';
    IF NOT EXISTS(SELECT 1 FROM [dbo].[OTEL_GORSELLERI] WHERE [OTEL_ID]=@HotelId AND [GORSEL_URL]=@CoverUrl) BEGIN INSERT INTO [dbo].[OTEL_GORSELLERI]([OTEL_ID],[GORSEL_URL],[GORSEL_TURU],[BASLIK],[KAPAK_FOTOGRAFI_MI],[ONE_CIKAN],[SIRALAMA],[ONAY_DURUMU]) VALUES(@HotelId,@CoverUrl,N'Genel Alan',N'Kapak',1,1,0,N'Onaylandı'); UPDATE [dbo].[OTELLER] SET [KAPAK_FOTOGRAFI]=@CoverUrl WHERE [ID]=@HotelId; END;
    SET @i=1; WHILE @i<=3 BEGIN SET @Url=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/hotel/demo-'+RIGHT(N'0'+CAST(@i AS nvarchar(2)),2)+N'.webp'; IF NOT EXISTS(SELECT 1 FROM [dbo].[OTEL_GORSELLERI] WHERE [OTEL_ID]=@HotelId AND [GORSEL_URL]=@Url) INSERT INTO [dbo].[OTEL_GORSELLERI]([OTEL_ID],[GORSEL_URL],[GORSEL_TURU],[BASLIK],[KAPAK_FOTOGRAFI_MI],[SIRALAMA],[ONAY_DURUMU]) VALUES(@HotelId,@Url,N'Genel Alan',CONCAT(N'Galeri ',@i),0,@i,N'Onaylandı'); SET @i+=1; END; END;
INSERT INTO @AntRooms VALUES(@Room1Id),(@Room2Id);
WHILE EXISTS(SELECT 1 FROM @AntRooms) BEGIN SELECT TOP(1) @RoomId=RoomId FROM @AntRooms ORDER BY RoomId;
    IF OBJECT_ID(N'dbo.ODA_GORSELLERI',N'U') IS NOT NULL BEGIN SET @RoomCover=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/rooms/'+CAST(@RoomId AS nvarchar(20))+N'/demo-room-cover.webp'; IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_GORSELLERI] WHERE [ODA_TIP_ID]=@RoomId AND [GORSEL_URL]=@RoomCover) INSERT INTO [dbo].[ODA_GORSELLERI]([ODA_TIP_ID],[GORSEL_URL],[BASLIK],[KAPAK_FOTOGRAFI_MI],[SIRALAMA],[ONAY_DURUMU]) VALUES(@RoomId,@RoomCover,N'Oda kapak',1,0,N'Onaylandı');
    SET @RoomUrl2=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/rooms/'+CAST(@RoomId AS nvarchar(20))+N'/demo-room-02.webp'; IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_GORSELLERI] WHERE [ODA_TIP_ID]=@RoomId AND [GORSEL_URL]=@RoomUrl2) INSERT INTO [dbo].[ODA_GORSELLERI]([ODA_TIP_ID],[GORSEL_URL],[BASLIK],[KAPAK_FOTOGRAFI_MI],[SIRALAMA],[ONAY_DURUMU]) VALUES(@RoomId,@RoomUrl2,N'Oda detay',0,1,N'Onaylandı'); END;
    DELETE FROM @AntRooms WHERE RoomId=@RoomId; END;
PRINT N'Antalya demo otel tamam. OTEL_ID='+CAST(@HotelId AS nvarchar(20));

-- KAPADOKYA
DECLARE @NevsehirIlId bigint = (SELECT TOP (1) [ID] FROM [dbo].[ILLER] WHERE [IL_ADI] LIKE N'Nev%ehir%' ORDER BY [ID]);
DECLARE @GoremeIlceId bigint = (SELECT TOP (1) [ID] FROM [dbo].[ILCELER] WHERE [IL_ID]=@NevsehirIlId AND ([SEO_SLUG]=N'urgup' OR [ILCE_ADI] LIKE N'%rg%p%') ORDER BY [ID]);
IF @NevsehirIlId IS NULL OR @GoremeIlceId IS NULL BEGIN RAISERROR(N'Nevsehir/Urgup geo eksik.',16,1); RETURN; END;
SET @OtelKodu=N'DEMO-KAPADOKYA-2026'; SET @StdFiyat=7500; SET @DlxFiyat=9800; SET @HotelId=NULL; SET @Room1Id=NULL; SET @Room2Id=NULL;
SELECT @HotelId=[ID] FROM [dbo].[OTELLER] WHERE [OTEL_KODU]=@OtelKodu;
IF @HotelId IS NULL BEGIN
    INSERT INTO [dbo].[OTELLER]([OTEL_KODU],[PARTNER_ID],[KULLANICI_ID],[OTEL_ADI],[OTEL_TURU],[OTEL_TIPI_ID],[YILDIZ_SAYISI],[ULKE],[SEHIR],[ILCE],[MAHALLE],[TAM_ADRES],[ENLEM],[BOYLAM],[ULKE_ID],[SEHIR_ID],[ILCE_ID],[TELEFON_1],[EPOSTA],[REZERVASYON_TELEFONU],[SATIS_KONTAK_ADI],[SATIS_KONTAK_TELEFONU],[SATIS_KONTAK_EPOSTA],[CHECK_IN_SAATI],[CHECK_OUT_SAATI],[TOPLAM_ODA_SAYISI],[KISA_ACIKLAMA],[UZUN_ACIKLAMA],[KONUM_ACIKLAMASI],[VARSAYILAN_KOMISYON_ORANI],[ODEME_VADESI],[ODEME_YONTEMI],[FATURA_KESIM_TURU],[ORTALAMA_PUAN],[TOPLAM_YORUM_SAYISI],[YAYIN_DURUMU],[ONAY_DURUMU],[ONAY_TARIHI],[ONE_CIKAN_OTEL],[TAVSIYE_EDILEN_OTEL],[POPULERLIK_SIRASI],[OLUSTURULMA_TARIHI])
    VALUES(@OtelKodu,@PartnerId,@PartnerUserId,N'Goreme Vadi Cave Suites',N'Hotel',@HotelTypeId,4,N'Turkiye',N'Nevsehir',N'Urgup',N'Goreme',N'Goreme Kasabasi Uchisar Yolu No:5 Nevsehir',38.6431,34.8287,@TrUlkeId,@NevsehirIlId,@GoremeIlceId,N'3845557700',N'rez.kapadokya@demo.otelturizm.local',N'3845557701',N'Kapadokya Demo',N'3845557702',N'ork-demo-partner@otelturizm.local','15:00:00','11:00:00',32,N'Goreme vadisinde tas mimari butik cave otel.',N'Goreme Vadi Cave Suites, restore edilmis tas odalar, gun dogumu terasi ve yerel sarap tadimi sunar.',N'Balon kalkis alanina 5 dk.',15,N'Cikis Gunu',N'Online',N'Otel Keser',9.0,0,N'Yayında',N'Onaylandı',SYSUTCDATETIME(),1,1,90,SYSUTCDATETIME());
    SET @HotelId=SCOPE_IDENTITY();
END ELSE UPDATE [dbo].[OTELLER] SET [YAYIN_DURUMU]=N'Yayında',[ONAY_DURUMU]=N'Onaylandı',[ONE_CIKAN_OTEL]=1,[TAVSIYE_EDILEN_OTEL]=1 WHERE [ID]=@HotelId;

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_KULLANICI_SAHIPLIKLERI] WHERE [OTEL_ID]=@HotelId AND [KULLANICI_ID]=@PartnerUserId)
    INSERT INTO [dbo].[OTEL_KULLANICI_SAHIPLIKLERI]([OTEL_ID],[KULLANICI_ID],[PARTNER_ID],[ROL],[ANA_SORUMLU_MU],[AKTIF_MI],[OLUSTURULMA_TARIHI]) VALUES(@HotelId,@PartnerUserId,@PartnerId,N'owner',1,1,SYSUTCDATETIME());
IF OBJECT_ID(N'dbo.OTEL_KOSULLARI',N'U') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_KOSULLARI] WHERE [OTEL_ID]=@HotelId)
    INSERT INTO [dbo].[OTEL_KOSULLARI]([OTEL_ID],[IPTAL_POLITIKASI_OZET],[DETAYLI_IPTAL_KOSULLARI],[UCRETSIZ_IPTAL_SURESI],[SIGARA_POLITIKASI],[EVCIL_HAYVAN_POLITIKASI],[COCUK_KABUL_YAS_ARALIGI],[KREDI_KARTI_ILE_ODEME_KABUL],[GUNCELLENME_TARIHI])
    VALUES(@HotelId,N'72 saat once ucretsiz iptal.',N'Balon turu iptallerinde 72 saat kurali gecerlidir.',3,N'Teras haric sigara yasak.',N'Evcil hayvan kabul edilmez.',N'0-6 yas ucretsiz',1,SYSUTCDATETIME());
IF OBJECT_ID(N'dbo.OTEL_OZELLIK_ILISKILERI',N'U') IS NOT NULL
    INSERT INTO [dbo].[OTEL_OZELLIK_ILISKILERI]([OTEL_ID],[OZELLIK_ID],[AKTIF_MI]) SELECT @HotelId,o.[ID],1 FROM [dbo].[OTEL_OZELLIKLERI] o INNER JOIN @FullOzellikKodlari k ON k.[Kod]=o.[OZELLIK_KODU] WHERE NOT EXISTS (SELECT 1 FROM [dbo].[OTEL_OZELLIK_ILISKILERI] i WHERE i.[OTEL_ID]=@HotelId AND i.[OZELLIK_ID]=o.[ID]);

SELECT @Room1Id=[ID] FROM [dbo].[ODA_TIPLERI] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_KODU]=N'CAVE-STD';
IF @Room1Id IS NULL BEGIN INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[ODA_METREKARE],[MANZARA_TIPI],[OZELLIKLER],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA]) VALUES(@HotelId,N'CAVE-STD',N'Tas Oda Vadi Manzarali',N'Cave Oda',2,2,0,N'Queen',1,24,N'Vadi',N'Tas duvar, Klima, Minibar',@StdFiyat,18,1,1); SET @Room1Id=SCOPE_IDENTITY(); END ELSE UPDATE [dbo].[ODA_TIPLERI] SET [STANDART_GECELIK_FIYAT]=@StdFiyat,[AKTIF_MI]=1 WHERE [ID]=@Room1Id;
SELECT @Room2Id=[ID] FROM [dbo].[ODA_TIPLERI] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_KODU]=N'CAVE-DLX';
IF @Room2Id IS NULL BEGIN INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[ODA_METREKARE],[BALKON_VAR_MI],[MANZARA_TIPI],[OZELLIKLER],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA]) VALUES(@HotelId,N'CAVE-DLX',N'Jakuzili Cave Suite',N'Cave Suite',3,2,1,N'King',1,36,1,N'Peri Bacasi',N'Jakuzi, somine, Minibar',@DlxFiyat,8,1,2); SET @Room2Id=SCOPE_IDENTITY(); END ELSE UPDATE [dbo].[ODA_TIPLERI] SET [STANDART_GECELIK_FIYAT]=@DlxFiyat,[AKTIF_MI]=1 WHERE [ID]=@Room2Id;

DELETE FROM @AntRooms; INSERT INTO @AntRooms VALUES(@Room1Id),(@Room2Id);
WHILE EXISTS(SELECT 1 FROM @AntRooms) BEGIN SELECT TOP(1) @RoomId=RoomId FROM @AntRooms ORDER BY RoomId;
    IF OBJECT_ID(N'dbo.ODA_TIPI_OZELLIKLERI',N'U') IS NOT NULL INSERT INTO [dbo].[ODA_TIPI_OZELLIKLERI]([ODA_TIP_ID],[OZELLIK_ID],[MIKTAR]) SELECT @RoomId,oo.[ID],1 FROM [dbo].[ODA_OZELLIKLERI] oo WHERE oo.[AKTIF_MI]=1 AND oo.[OZELLIK_ADI] IN (N'Klima',N'Minibar',N'LED TV',N'Sac Kurutma Makinesi',N'Kasa',N'Nespresso') AND NOT EXISTS (SELECT 1 FROM [dbo].[ODA_TIPI_OZELLIKLERI] x WHERE x.[ODA_TIP_ID]=@RoomId AND x.[OZELLIK_ID]=oo.[ID]);
    DELETE FROM @AntRooms WHERE RoomId=@RoomId; END;

SET @d=0; WHILE @d<@PriceDays BEGIN SET @Tarih=DATEADD(DAY,@d,@Today); SET @IsWeekend=CASE WHEN DATEPART(WEEKDAY,@Tarih) IN (6,7) THEN 1 ELSE 0 END;
    SET @Indirimli=CASE WHEN @IsWeekend=1 THEN CAST(@StdFiyat*0.85 AS decimal(10,2)) WHEN @d>=14 THEN CAST(@StdFiyat*0.80 AS decimal(10,2)) ELSE NULL END;
    IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_FIYAT_MUSAITLIK] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room1Id AND [TARIH]=@Tarih) INSERT INTO [dbo].[ODA_FIYAT_MUSAITLIK]([ODA_TIP_ID],[OTEL_ID],[TARIH],[GECELIK_FIYAT],[INDIRIMLI_FIYAT],[INDIRIM_ID],[KAMPANYA_ID],[TOPLAM_ODA_SAYISI],[KAPALI_SATIS],[KAMPANYA_ETIKETI]) VALUES(@Room1Id,@HotelId,@Tarih,@StdFiyat,@Indirimli,CASE WHEN @Indirimli IS NOT NULL AND @IsWeekend=1 THEN @WeekendIndirimId WHEN @Indirimli IS NOT NULL AND @d>=14 THEN @ErkenIndirimId ELSE NULL END,@KampanyaId,18,0,N'VADI');
    ELSE UPDATE [dbo].[ODA_FIYAT_MUSAITLIK] SET [GECELIK_FIYAT]=@StdFiyat,[INDIRIMLI_FIYAT]=@Indirimli,[KAPALI_SATIS]=0 WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room1Id AND [TARIH]=@Tarih;
    SET @Indirimli=CASE WHEN @IsWeekend=1 THEN CAST(@DlxFiyat*0.85 AS decimal(10,2)) WHEN @d>=14 THEN CAST(@DlxFiyat*0.80 AS decimal(10,2)) ELSE NULL END;
    IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_FIYAT_MUSAITLIK] WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room2Id AND [TARIH]=@Tarih) INSERT INTO [dbo].[ODA_FIYAT_MUSAITLIK]([ODA_TIP_ID],[OTEL_ID],[TARIH],[GECELIK_FIYAT],[INDIRIMLI_FIYAT],[INDIRIM_ID],[KAMPANYA_ID],[TOPLAM_ODA_SAYISI],[KAPALI_SATIS],[KAMPANYA_ETIKETI]) VALUES(@Room2Id,@HotelId,@Tarih,@DlxFiyat,@Indirimli,CASE WHEN @Indirimli IS NOT NULL AND @IsWeekend=1 THEN @WeekendIndirimId WHEN @Indirimli IS NOT NULL AND @d>=14 THEN @ErkenIndirimId ELSE NULL END,@KampanyaId,8,0,N'VADI');
    ELSE UPDATE [dbo].[ODA_FIYAT_MUSAITLIK] SET [GECELIK_FIYAT]=@DlxFiyat,[INDIRIMLI_FIYAT]=@Indirimli,[KAPALI_SATIS]=0 WHERE [OTEL_ID]=@HotelId AND [ODA_TIP_ID]=@Room2Id AND [TARIH]=@Tarih;
    SET @d+=1; END;

IF @KampanyaId IS NOT NULL AND OBJECT_ID(N'dbo.KAMPANYA_OTELLER',N'U') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[KAMPANYA_OTELLER] WHERE [KAMPANYA_ID]=@KampanyaId AND [OTEL_ID]=@HotelId)
    INSERT INTO [dbo].[KAMPANYA_OTELLER]([KAMPANYA_ID],[OTEL_ID],[PARTNER_ID],[KATILIM_DURUMU],[KATILIM_KAYNAGI],[BASLANGIC_TARIHI],[BITIS_TARIHI],[ADMIN_ONAY_TARIHI],[PARTNER_ONAY_TARIHI],[OLUSTURULMA_TARIHI]) VALUES(@KampanyaId,@HotelId,@PartnerId,N'Aktif',N'KapadokyaDemoSeed',@KampanyaBas,@KampanyaBit,SYSUTCDATETIME(),SYSUTCDATETIME(),SYSUTCDATETIME());

IF OBJECT_ID(N'dbo.OTEL_GORSELLERI',N'U') IS NOT NULL BEGIN
    SET @CoverUrl=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/hotel/demo-cover.webp';
    IF NOT EXISTS(SELECT 1 FROM [dbo].[OTEL_GORSELLERI] WHERE [OTEL_ID]=@HotelId AND [GORSEL_URL]=@CoverUrl) BEGIN INSERT INTO [dbo].[OTEL_GORSELLERI]([OTEL_ID],[GORSEL_URL],[GORSEL_TURU],[BASLIK],[KAPAK_FOTOGRAFI_MI],[ONE_CIKAN],[SIRALAMA],[ONAY_DURUMU]) VALUES(@HotelId,@CoverUrl,N'Genel Alan',N'Kapak',1,1,0,N'Onaylandı'); UPDATE [dbo].[OTELLER] SET [KAPAK_FOTOGRAFI]=@CoverUrl WHERE [ID]=@HotelId; END;
    SET @i=1; WHILE @i<=3 BEGIN SET @Url=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/hotel/demo-'+RIGHT(N'0'+CAST(@i AS nvarchar(2)),2)+N'.webp'; IF NOT EXISTS(SELECT 1 FROM [dbo].[OTEL_GORSELLERI] WHERE [OTEL_ID]=@HotelId AND [GORSEL_URL]=@Url) INSERT INTO [dbo].[OTEL_GORSELLERI]([OTEL_ID],[GORSEL_URL],[GORSEL_TURU],[BASLIK],[KAPAK_FOTOGRAFI_MI],[SIRALAMA],[ONAY_DURUMU]) VALUES(@HotelId,@Url,N'Genel Alan',CONCAT(N'Galeri ',@i),0,@i,N'Onaylandı'); SET @i+=1; END; END;
INSERT INTO @AntRooms VALUES(@Room1Id),(@Room2Id);
WHILE EXISTS(SELECT 1 FROM @AntRooms) BEGIN SELECT TOP(1) @RoomId=RoomId FROM @AntRooms ORDER BY RoomId;
    IF OBJECT_ID(N'dbo.ODA_GORSELLERI',N'U') IS NOT NULL BEGIN SET @RoomCover=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/rooms/'+CAST(@RoomId AS nvarchar(20))+N'/demo-room-cover.webp'; IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_GORSELLERI] WHERE [ODA_TIP_ID]=@RoomId AND [GORSEL_URL]=@RoomCover) INSERT INTO [dbo].[ODA_GORSELLERI]([ODA_TIP_ID],[GORSEL_URL],[BASLIK],[KAPAK_FOTOGRAFI_MI],[SIRALAMA],[ONAY_DURUMU]) VALUES(@RoomId,@RoomCover,N'Oda kapak',1,0,N'Onaylandı');
    SET @RoomUrl2=N'/uploads/images/'+CAST(@HotelId AS nvarchar(20))+N'/rooms/'+CAST(@RoomId AS nvarchar(20))+N'/demo-room-02.webp'; IF NOT EXISTS(SELECT 1 FROM [dbo].[ODA_GORSELLERI] WHERE [ODA_TIP_ID]=@RoomId AND [GORSEL_URL]=@RoomUrl2) INSERT INTO [dbo].[ODA_GORSELLERI]([ODA_TIP_ID],[GORSEL_URL],[BASLIK],[KAPAK_FOTOGRAFI_MI],[SIRALAMA],[ONAY_DURUMU]) VALUES(@RoomId,@RoomUrl2,N'Oda detay',0,1,N'Onaylandı'); END;
    DELETE FROM @AntRooms WHERE RoomId=@RoomId; END;
PRINT N'Kapadokya demo otel tamam. OTEL_ID='+CAST(@HotelId AS nvarchar(20));
