-- Varsayılan otel bazlı puan kazanım ve indirim kuralları
IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'KAZANIM' AND [MIN_DEGER] = 0 AND [MAX_DEGER] = 2000)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [PUAN_DEGERI], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'KAZANIM', 0, 2000, 5, N'0–2.000 TL rezervasyon tutarı', 1, 10);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'KAZANIM' AND [MIN_DEGER] = 2001 AND [MAX_DEGER] = 5000)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [PUAN_DEGERI], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'KAZANIM', 2001, 5000, 10, N'2.001–5.000 TL rezervasyon tutarı', 1, 20);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'KAZANIM' AND [MIN_DEGER] = 5001 AND [MAX_DEGER] = 10000)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [PUAN_DEGERI], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'KAZANIM', 5001, 10000, 20, N'5.001–10.000 TL rezervasyon tutarı', 1, 30);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'KAZANIM' AND [MIN_DEGER] = 10001 AND [MAX_DEGER] IS NULL)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [PUAN_DEGERI], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'KAZANIM', 10001, NULL, 35, N'10.001 TL ve üzeri rezervasyon tutarı', 1, 40);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'INDIRIM' AND [MIN_DEGER] = 10 AND [MAX_DEGER] = 24)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [INDIRIM_YUZDE], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'INDIRIM', 10, 24, 2, N'10–24 puan ile %2 indirim', 1, 10);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'INDIRIM' AND [MIN_DEGER] = 25 AND [MAX_DEGER] = 49)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [INDIRIM_YUZDE], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'INDIRIM', 25, 49, 5, N'25–49 puan ile %5 indirim', 1, 20);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'INDIRIM' AND [MIN_DEGER] = 50 AND [MAX_DEGER] = 99)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [INDIRIM_YUZDE], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'INDIRIM', 50, 99, 8, N'50–99 puan ile %8 indirim', 1, 30);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[PUAN_AYAR] WHERE [AYAR_TIPI] = N'INDIRIM' AND [MIN_DEGER] = 100 AND [MAX_DEGER] IS NULL)
BEGIN
    INSERT INTO [dbo].[PUAN_AYAR] ([AYAR_TIPI], [MIN_DEGER], [MAX_DEGER], [INDIRIM_YUZDE], [ACIKLAMA], [AKTIF_MI], [SIRA_NO])
    VALUES (N'INDIRIM', 100, NULL, 12, N'100+ puan ile %12 indirim', 1, 40);
END
GO

PRINT N'PUAN_AYAR varsayılan kuralları seed tamamlandı.';
GO
