-- Idempotent: platform EPOSTA_SERVISLERI kayitlarini aktif et (SMTP gonderim icin)
-- Not: SMTP_SIFRE repoda tutulmaz; Admin > Mail Merkezi veya Email:SharedMailboxPassword ile tamamlanir.
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

IF OBJECT_ID(N'dbo.EPOSTA_SERVISLERI', N'U') IS NULL
BEGIN
    RAISERROR(N'EPOSTA_SERVISLERI tablosu bulunamadi.', 16, 1);
    RETURN;
END;

UPDATE [dbo].[EPOSTA_SERVISLERI]
SET
    [AKTIF_MI] = 1,
    [TEST_MODU] = 0,
    [SMTP_HOST] = COALESCE(NULLIF(LTRIM(RTRIM([SMTP_HOST])), N''), N'umay.muvhost.com'),
    [SMTP_PORT] = COALESCE(NULLIF([SMTP_PORT], 0), 465),
    [SMTP_KULLANICI_ADI] = COALESCE(NULLIF(LTRIM(RTRIM([SMTP_KULLANICI_ADI])), N''), [GONDEREN_EPOSTA]),
    [GUVENLIK_TIPI] = COALESCE(NULLIF(LTRIM(RTRIM([GUVENLIK_TIPI])), N''), N'SSL/TLS'),
    [GONDEREN_AD] = COALESCE(NULLIF(LTRIM(RTRIM([GONDEREN_AD])), N''), N'otelturizm.com'),
    [YANITLA_EPOSTA] = COALESCE(NULLIF(LTRIM(RTRIM([YANITLA_EPOSTA])), N''), [GONDEREN_EPOSTA]),
    [SON_HATA_MESAJI] = CASE
        WHEN NULLIF(LTRIM(RTRIM([SMTP_SIFRE])), N'') IS NULL
            THEN N'SMTP sifresi tanimlanmali (Admin > Mail Merkezi veya Email:SharedMailboxPassword).'
        ELSE NULL
    END,
    [GUNCELLENME_TARIHI] = SYSUTCDATETIME()
WHERE NULLIF(LTRIM(RTRIM([SMTP_HOST])), N'') IS NOT NULL
   OR [SERVIS_KODU] LIKE N'platform[_]%';

SELECT
    [ID],
    [SERVIS_KODU],
    [AKTIF_MI],
    [TEST_MODU],
    [GONDEREN_EPOSTA],
    CASE WHEN NULLIF(LTRIM(RTRIM([SMTP_SIFRE])), N'') IS NULL THEN 0 ELSE 1 END AS [SIFRE_TANIMLI]
FROM [dbo].[EPOSTA_SERVISLERI]
ORDER BY [ID];
GO
