-- Tekil otel INSERT (007-010) — GO ile ayrilmis
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTELLER] WHERE [OTEL_KODU]=N'ORK-SEED-007')
BEGIN
  DECLARE @p bigint=(SELECT TOP 1 id FROM PARTNER_DETAYLARI);
  DECLARE @u bigint=(SELECT TOP 1 id FROM KULLANICILAR WHERE [EPOSTA]=N'ork-demo-partner@otelturizm.local');
  DECLARE @t int=(SELECT TOP 1 id FROM OTEL_TIPLERI WHERE [KOD]=N'HOTEL');
  DECLARE @ulke bigint=(SELECT TOP 1 id FROM ULKELER WHERE [ISO2_KODU]=N'TR');
  DECLARE @il bigint=(SELECT TOP 1 id FROM ILLER WHERE [IL_ADI] LIKE N'%stanbul%');
  DECLARE @ilce bigint=(SELECT TOP 1 id FROM ILCELER WHERE [IL_ID]=@il ORDER BY [ID]);
  INSERT INTO [dbo].[OTELLER]([OTEL_KODU],[PARTNER_ID],[KULLANICI_ID],[OTEL_ADI],[OTEL_TURU],[OTEL_TIPI_ID],[YILDIZ_SAYISI],[ULKE],[SEHIR],[ILCE],[MAHALLE],[TAM_ADRES],[ULKE_ID],[SEHIR_ID],[ILCE_ID],[TELEFON_1],[EPOSTA],[REZERVASYON_TELEFONU],[SATIS_KONTAK_ADI],[SATIS_KONTAK_TELEFONU],[SATIS_KONTAK_EPOSTA],[CHECK_IN_SAATI],[CHECK_OUT_SAATI],[TOPLAM_ODA_SAYISI],[KISA_ACIKLAMA],[UZUN_ACIKLAMA],[VARSAYILAN_KOMISYON_ORANI],[ODEME_VADESI],[ODEME_YONTEMI],[FATURA_KESIM_TURU],[YAYIN_DURUMU],[ONAY_DURUMU],[ONAY_TARIHI],[OLUSTURULMA_TARIHI])
  VALUES(N'ORK-SEED-007',@p,@u,N'Orkestra Fatih Heritage',N'Hotel',@t,4,N'Turkiye',N'Istanbul',N'Fatih',N'Sultanahmet',N'Sultanahmet, Istanbul',@ulke,@il,@ilce,N'2125550007',N'rez.orkseed007@demo.otelturizm.local',N'2125550001',N'Demo',N'2125550002',N'ork-demo-partner@otelturizm.local','14:00:00','12:00:00',20,N'Demo',N'Demo',15,N'Ayın 15''i',N'Online',N'Otel Keser',N'Yayında',N'Onaylandı',SYSUTCDATETIME(),SYSUTCDATETIME());
  DECLARE @h bigint=SCOPE_IDENTITY();
  INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA])
  VALUES(@h,N'STD-DEMO',N'Standart',N'Standart',2,2,1,N'Queen',1,5200,10,1,1);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTELLER] WHERE [OTEL_KODU]=N'ORK-SEED-008')
BEGIN
  DECLARE @p bigint=(SELECT TOP 1 id FROM PARTNER_DETAYLARI);
  DECLARE @u bigint=(SELECT TOP 1 id FROM KULLANICILAR WHERE [EPOSTA]=N'ork-demo-partner@otelturizm.local');
  DECLARE @t int=(SELECT TOP 1 id FROM OTEL_TIPLERI WHERE [KOD]=N'HOTEL');
  DECLARE @ulke bigint=(SELECT TOP 1 id FROM ULKELER WHERE [ISO2_KODU]=N'TR');
  DECLARE @il bigint=(SELECT TOP 1 id FROM ILLER WHERE [IL_ADI] LIKE N'%stanbul%');
  DECLARE @ilce bigint=(SELECT TOP 1 id FROM ILCELER WHERE [IL_ID]=@il ORDER BY [ID]);
  INSERT INTO [dbo].[OTELLER]([OTEL_KODU],[PARTNER_ID],[KULLANICI_ID],[OTEL_ADI],[OTEL_TURU],[OTEL_TIPI_ID],[YILDIZ_SAYISI],[ULKE],[SEHIR],[ILCE],[MAHALLE],[TAM_ADRES],[ULKE_ID],[SEHIR_ID],[ILCE_ID],[TELEFON_1],[EPOSTA],[REZERVASYON_TELEFONU],[SATIS_KONTAK_ADI],[SATIS_KONTAK_TELEFONU],[SATIS_KONTAK_EPOSTA],[CHECK_IN_SAATI],[CHECK_OUT_SAATI],[TOPLAM_ODA_SAYISI],[KISA_ACIKLAMA],[UZUN_ACIKLAMA],[VARSAYILAN_KOMISYON_ORANI],[ODEME_VADESI],[ODEME_YONTEMI],[FATURA_KESIM_TURU],[YAYIN_DURUMU],[ONAY_DURUMU],[ONAY_TARIHI],[OLUSTURULMA_TARIHI])
  VALUES(N'ORK-SEED-008',@p,@u,N'Orkestra Bakirkoy Sahil',N'Hotel',@t,4,N'Turkiye',N'Istanbul',N'Bakirkoy',N'Atakoy',N'Atakoy, Istanbul',@ulke,@il,@ilce,N'2125550008',N'rez.orkseed008@demo.otelturizm.local',N'2125550001',N'Demo',N'2125550002',N'ork-demo-partner@otelturizm.local','14:00:00','12:00:00',20,N'Demo',N'Demo',15,N'Ayın 15''i',N'Online',N'Otel Keser',N'Yayında',N'Onaylandı',SYSUTCDATETIME(),SYSUTCDATETIME());
  DECLARE @h bigint=SCOPE_IDENTITY();
  INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA])
  VALUES(@h,N'STD-DEMO',N'Standart',N'Standart',2,2,1,N'Queen',1,4400,10,1,1);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTELLER] WHERE [OTEL_KODU]=N'ORK-SEED-009')
BEGIN
  DECLARE @p bigint=(SELECT TOP 1 id FROM PARTNER_DETAYLARI);
  DECLARE @u bigint=(SELECT TOP 1 id FROM KULLANICILAR WHERE [EPOSTA]=N'ork-demo-partner@otelturizm.local');
  DECLARE @t int=(SELECT TOP 1 id FROM OTEL_TIPLERI WHERE [KOD]=N'HOTEL');
  DECLARE @ulke bigint=(SELECT TOP 1 id FROM ULKELER WHERE [ISO2_KODU]=N'TR');
  DECLARE @il bigint=(SELECT TOP 1 id FROM ILLER WHERE [IL_ADI] LIKE N'%stanbul%');
  DECLARE @ilce bigint=(SELECT TOP 1 id FROM ILCELER WHERE [IL_ID]=@il ORDER BY [ID]);
  INSERT INTO [dbo].[OTELLER]([OTEL_KODU],[PARTNER_ID],[KULLANICI_ID],[OTEL_ADI],[OTEL_TURU],[OTEL_TIPI_ID],[YILDIZ_SAYISI],[ULKE],[SEHIR],[ILCE],[MAHALLE],[TAM_ADRES],[ULKE_ID],[SEHIR_ID],[ILCE_ID],[TELEFON_1],[EPOSTA],[REZERVASYON_TELEFONU],[SATIS_KONTAK_ADI],[SATIS_KONTAK_TELEFONU],[SATIS_KONTAK_EPOSTA],[CHECK_IN_SAATI],[CHECK_OUT_SAATI],[TOPLAM_ODA_SAYISI],[KISA_ACIKLAMA],[UZUN_ACIKLAMA],[VARSAYILAN_KOMISYON_ORANI],[ODEME_VADESI],[ODEME_YONTEMI],[FATURA_KESIM_TURU],[YAYIN_DURUMU],[ONAY_DURUMU],[ONAY_TARIHI],[OLUSTURULMA_TARIHI])
  VALUES(N'ORK-SEED-009',@p,@u,N'Orkestra Maltepe City',N'Hotel',@t,3,N'Turkiye',N'Istanbul',N'Maltepe',N'Cevizli',N'Cevizli, Istanbul',@ulke,@il,@ilce,N'2125550009',N'rez.orkseed009@demo.otelturizm.local',N'2125550001',N'Demo',N'2125550002',N'ork-demo-partner@otelturizm.local','14:00:00','12:00:00',20,N'Demo',N'Demo',15,N'Ayın 15''i',N'Online',N'Otel Keser',N'Yayında',N'Onaylandı',SYSUTCDATETIME(),SYSUTCDATETIME());
  DECLARE @h bigint=SCOPE_IDENTITY();
  INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA])
  VALUES(@h,N'STD-DEMO',N'Standart',N'Standart',2,2,1,N'Queen',1,3100,10,1,1);
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[OTELLER] WHERE [OTEL_KODU]=N'ORK-SEED-010')
BEGIN
  DECLARE @p bigint=(SELECT TOP 1 id FROM PARTNER_DETAYLARI);
  DECLARE @u bigint=(SELECT TOP 1 id FROM KULLANICILAR WHERE [EPOSTA]=N'ork-demo-partner@otelturizm.local');
  DECLARE @t int=(SELECT TOP 1 id FROM OTEL_TIPLERI WHERE [KOD]=N'HOTEL');
  DECLARE @ulke bigint=(SELECT TOP 1 id FROM ULKELER WHERE [ISO2_KODU]=N'TR');
  DECLARE @il bigint=(SELECT TOP 1 id FROM ILLER WHERE [IL_ADI] LIKE N'%stanbul%');
  DECLARE @ilce bigint=(SELECT TOP 1 id FROM ILCELER WHERE [IL_ID]=@il ORDER BY [ID]);
  INSERT INTO [dbo].[OTELLER]([OTEL_KODU],[PARTNER_ID],[KULLANICI_ID],[OTEL_ADI],[OTEL_TURU],[OTEL_TIPI_ID],[YILDIZ_SAYISI],[ULKE],[SEHIR],[ILCE],[MAHALLE],[TAM_ADRES],[ULKE_ID],[SEHIR_ID],[ILCE_ID],[TELEFON_1],[EPOSTA],[REZERVASYON_TELEFONU],[SATIS_KONTAK_ADI],[SATIS_KONTAK_TELEFONU],[SATIS_KONTAK_EPOSTA],[CHECK_IN_SAATI],[CHECK_OUT_SAATI],[TOPLAM_ODA_SAYISI],[KISA_ACIKLAMA],[UZUN_ACIKLAMA],[VARSAYILAN_KOMISYON_ORANI],[ODEME_VADESI],[ODEME_YONTEMI],[FATURA_KESIM_TURU],[YAYIN_DURUMU],[ONAY_DURUMU],[ONAY_TARIHI],[OLUSTURULMA_TARIHI])
  VALUES(N'ORK-SEED-010',@p,@u,N'Orkestra Atasehir Tower',N'Hotel',@t,5,N'Turkiye',N'Istanbul',N'Atasehir',N'Kucukbakkalkoy',N'Atasehir, Istanbul',@ulke,@il,@ilce,N'2125550010',N'rez.orkseed010@demo.otelturizm.local',N'2125550001',N'Demo',N'2125550002',N'ork-demo-partner@otelturizm.local','14:00:00','12:00:00',20,N'Demo',N'Demo',15,N'Ayın 15''i',N'Online',N'Otel Keser',N'Yayında',N'Onaylandı',SYSUTCDATETIME(),SYSUTCDATETIME());
  DECLARE @h bigint=SCOPE_IDENTITY();
  INSERT INTO [dbo].[ODA_TIPLERI]([OTEL_ID],[ODA_TIP_KODU],[ODA_ADI],[ODA_KATEGORISI],[MAKSIMUM_KISI_SAYISI],[MAKSIMUM_YETISKIN_SAYISI],[MAKSIMUM_COCUK_SAYISI],[YATAK_TIPI],[YATAK_SAYISI],[STANDART_GECELIK_FIYAT],[TOPLAM_ODA_SAYISI],[AKTIF_MI],[SIRALAMA])
  VALUES(@h,N'STD-DEMO',N'Standart',N'Standart',2,2,1,N'Queen',1,5800,10,1,1);
END
GO
