CREATE TABLE IF NOT EXISTS `partner_panel_tercihleri` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `kullanici_id` bigint unsigned NOT NULL,
  `partner_id` bigint unsigned NOT NULL,
  `varsayilan_otel_id` bigint unsigned DEFAULT NULL,
  `dil` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT 'tr',
  `para_birimi` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT 'TRY',
  `zaman_dilimi` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'Europe/Istanbul',
  `takvim_gorunumu` enum('Gunluk','Haftalik','Aylik') COLLATE utf8mb4_unicode_ci DEFAULT 'Aylik',
  `email_bildirimleri` tinyint(1) DEFAULT '1',
  `sms_bildirimleri` tinyint(1) DEFAULT '0',
  `push_bildirimleri` tinyint(1) DEFAULT '1',
  `masaustu_bildirimleri` tinyint(1) DEFAULT '1',
  `yeni_rezervasyon_bildirimi` tinyint(1) DEFAULT '1',
  `iptal_bildirimi` tinyint(1) DEFAULT '1',
  `odeme_bildirimi` tinyint(1) DEFAULT '1',
  `yorum_bildirimi` tinyint(1) DEFAULT '1',
  `otomatik_fiyat_onerileri` tinyint(1) DEFAULT '1',
  `otomatik_kapali_gun_uyarisi` tinyint(1) DEFAULT '1',
  `cihazi_hatirla` tinyint(1) DEFAULT '1',
  `olusturulma_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `guncellenme_tarihi` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_partner_panel_tercihleri_kullanici` (`kullanici_id`),
  KEY `idx_partner_panel_tercihleri_partner` (`partner_id`),
  KEY `idx_partner_panel_tercihleri_otel` (`varsayilan_otel_id`),
  CONSTRAINT `fk_partner_panel_tercihleri_user` FOREIGN KEY (`kullanici_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_partner_panel_tercihleri_partner` FOREIGN KEY (`partner_id`) REFERENCES `partner_detaylari` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_partner_panel_tercihleri_otel` FOREIGN KEY (`varsayilan_otel_id`) REFERENCES `oteller` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
