CREATE TABLE IF NOT EXISTS [partner_panel_tercihleri] (
  [id] bigint  NOT NULL IDENTITY(1,1),
  [kullanici_id] bigint  NOT NULL,
  [partner_id] bigint  NOT NULL,
  [varsayilan_otel_id] bigint  DEFAULT NULL,
  [dil] varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT 'tr',
  [para_birimi] varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT 'TRY',
  [zaman_dilimi] varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT 'Europe/Istanbul',
  [takvim_gorunumu] enum('Gunluk','Haftalik','Aylik') COLLATE utf8mb4_unicode_ci DEFAULT 'Aylik',
  [email_bildirimleri] BIT DEFAULT '1',
  [sms_bildirimleri] BIT DEFAULT '0',
  [push_bildirimleri] BIT DEFAULT '1',
  [masaustu_bildirimleri] BIT DEFAULT '1',
  [yeni_rezervasyon_bildirimi] BIT DEFAULT '1',
  [iptal_bildirimi] BIT DEFAULT '1',
  [odeme_bildirimi] BIT DEFAULT '1',
  [yorum_bildirimi] BIT DEFAULT '1',
  [otomatik_fiyat_onerileri] BIT DEFAULT '1',
  [otomatik_kapali_gun_uyarisi] BIT DEFAULT '1',
  [cihazi_hatirla] BIT DEFAULT '1',
  [olusturulma_tarihi] DATETIME2 NULL DEFAULT GETDATE(),
  [guncellenme_tarihi] DATETIME2 NULL DEFAULT NULL,
  PRIMARY KEY ([id]),
  UNIQUE KEY [uk_partner_panel_tercihleri_kullanici] ([kullanici_id]),
  KEY [idx_partner_panel_tercihleri_partner] ([partner_id]),
  KEY [idx_partner_panel_tercihleri_otel] ([varsayilan_otel_id]),
  CONSTRAINT [fk_partner_panel_tercihleri_user] FOREIGN KEY ([kullanici_id]) REFERENCES [users] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_partner_panel_tercihleri_partner] FOREIGN KEY ([partner_id]) REFERENCES [partner_detaylari] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_partner_panel_tercihleri_otel] FOREIGN KEY ([varsayilan_otel_id]) REFERENCES [oteller] ([id]) ON DELETE SET NULL
);
