CREATE TABLE IF NOT EXISTS `partner_destek_talepleri` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `partner_id` bigint unsigned NOT NULL,
  `kullanici_id` bigint unsigned NOT NULL,
  `otel_id` bigint unsigned DEFAULT NULL,
  `talep_no` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `konu` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `kategori` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `oncelik` enum('Dusuk','Normal','Yuksek','Kritik') COLLATE utf8mb4_unicode_ci DEFAULT 'Normal',
  `durum` enum('Acik','Partner Yaniti Bekleniyor','Inceleniyor','Cozuldu','Kapatildi') COLLATE utf8mb4_unicode_ci DEFAULT 'Acik',
  `atanan_admin_id` bigint unsigned DEFAULT NULL,
  `son_mesaj_tarihi` timestamp NULL DEFAULT NULL,
  `olusturulma_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `guncellenme_tarihi` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_partner_destek_talep_no` (`talep_no`),
  KEY `idx_partner_destek_partner` (`partner_id`,`durum`),
  KEY `idx_partner_destek_kullanici` (`kullanici_id`),
  KEY `idx_partner_destek_otel` (`otel_id`),
  CONSTRAINT `fk_partner_destek_partner` FOREIGN KEY (`partner_id`) REFERENCES `partner_detaylari` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_partner_destek_user` FOREIGN KEY (`kullanici_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_partner_destek_otel` FOREIGN KEY (`otel_id`) REFERENCES `oteller` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_partner_destek_admin` FOREIGN KEY (`atanan_admin_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
