CREATE TABLE IF NOT EXISTS [partner_destek_talepleri] (
  [id] bigint  NOT NULL IDENTITY(1,1),
  [partner_id] bigint  NOT NULL,
  [kullanici_id] bigint  NOT NULL,
  [otel_id] bigint  DEFAULT NULL,
  [talep_no] varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  [konu] varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  [kategori] varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  [oncelik] enum('Dusuk','Normal','Yuksek','Kritik') COLLATE utf8mb4_unicode_ci DEFAULT 'Normal',
  [durum] enum('Acik','Partner Yaniti Bekleniyor','Inceleniyor','Cozuldu','Kapatildi') COLLATE utf8mb4_unicode_ci DEFAULT 'Acik',
  [atanan_admin_id] bigint  DEFAULT NULL,
  [son_mesaj_tarihi] DATETIME2 NULL DEFAULT NULL,
  [olusturulma_tarihi] DATETIME2 NULL DEFAULT GETDATE(),
  [guncellenme_tarihi] DATETIME2 NULL DEFAULT NULL,
  PRIMARY KEY ([id]),
  UNIQUE KEY [uk_partner_destek_talep_no] ([talep_no]),
  KEY [idx_partner_destek_partner] ([partner_id],[durum]),
  KEY [idx_partner_destek_kullanici] ([kullanici_id]),
  KEY [idx_partner_destek_otel] ([otel_id]),
  CONSTRAINT [fk_partner_destek_partner] FOREIGN KEY ([partner_id]) REFERENCES [partner_detaylari] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_partner_destek_user] FOREIGN KEY ([kullanici_id]) REFERENCES [users] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_partner_destek_otel] FOREIGN KEY ([otel_id]) REFERENCES [oteller] ([id]) ON DELETE SET NULL,
  CONSTRAINT [fk_partner_destek_admin] FOREIGN KEY ([atanan_admin_id]) REFERENCES [users] ([id]) ON DELETE SET NULL
);
