CREATE TABLE IF NOT EXISTS `kullanici_oturum_istatistikleri` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `kullanici_id` bigint unsigned NOT NULL,
  `hesap_tipi` enum('user','partner','admin','firma') COLLATE utf8mb4_unicode_ci NOT NULL,
  `partner_id` bigint unsigned DEFAULT NULL,
  `cihaz_anahtari` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cihaz_etiketi` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `beni_hatirla_tercihi` tinyint(1) DEFAULT '0',
  `toplam_ziyaret_sayisi` int unsigned DEFAULT '0',
  `toplam_oturum_suresi_saniye` bigint unsigned DEFAULT '0',
  `son_oturum_baslangici` timestamp NULL DEFAULT NULL,
  `son_oturum_bitisi` timestamp NULL DEFAULT NULL,
  `son_aktivite_tarihi` timestamp NULL DEFAULT NULL,
  `son_ip_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `son_user_agent_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `olusturulma_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `guncellenme_tarihi` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_kullanici_oturum_istatistikleri` (`kullanici_id`,`cihaz_anahtari`),
  KEY `idx_kullanici_oturum_istatistikleri_partner` (`partner_id`),
  KEY `idx_kullanici_oturum_istatistikleri_aktivite` (`son_aktivite_tarihi`),
  CONSTRAINT `fk_kullanici_oturum_istatistikleri_user` FOREIGN KEY (`kullanici_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_kullanici_oturum_istatistikleri_partner` FOREIGN KEY (`partner_id`) REFERENCES `partner_detaylari` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
