CREATE TABLE IF NOT EXISTS [kullanici_oturum_istatistikleri] (
  [id] bigint  NOT NULL IDENTITY(1,1),
  [kullanici_id] bigint  NOT NULL,
  [hesap_tipi] enum('user','partner','admin','firma') COLLATE utf8mb4_unicode_ci NOT NULL,
  [partner_id] bigint  DEFAULT NULL,
  [cihaz_anahtari] varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  [cihaz_etiketi] varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  [beni_hatirla_tercihi] BIT DEFAULT '0',
  [toplam_ziyaret_sayisi] int  DEFAULT '0',
  [toplam_oturum_suresi_saniye] bigint  DEFAULT '0',
  [son_oturum_baslangici] DATETIME2 NULL DEFAULT NULL,
  [son_oturum_bitisi] DATETIME2 NULL DEFAULT NULL,
  [son_aktivite_tarihi] DATETIME2 NULL DEFAULT NULL,
  [son_ip_hash] char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  [son_user_agent_hash] char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  [olusturulma_tarihi] DATETIME2 NULL DEFAULT GETDATE(),
  [guncellenme_tarihi] DATETIME2 NULL DEFAULT NULL,
  PRIMARY KEY ([id]),
  UNIQUE KEY [uk_kullanici_oturum_istatistikleri] ([kullanici_id],[cihaz_anahtari]),
  KEY [idx_kullanici_oturum_istatistikleri_partner] ([partner_id]),
  KEY [idx_kullanici_oturum_istatistikleri_aktivite] ([son_aktivite_tarihi]),
  CONSTRAINT [fk_kullanici_oturum_istatistikleri_user] FOREIGN KEY ([kullanici_id]) REFERENCES [users] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_kullanici_oturum_istatistikleri_partner] FOREIGN KEY ([partner_id]) REFERENCES [partner_detaylari] ([id]) ON DELETE SET NULL
);
