CREATE TABLE IF NOT EXISTS `firmalar` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `firma_kodu` varchar(32) NOT NULL,
  `firma_adi` varchar(200) NOT NULL,
  `firma_turu` enum('Anonim Şirketi','Limited Şirketi','Şahıs Firması','Holding','Kamu Kurumu','STK','Dernek','Vakıf','Teknoloji Şirketi','Turizm Şirketi','Danışmanlık Şirketi') NOT NULL DEFAULT 'Limited Şirketi',
  `vergi_no` varchar(20) NOT NULL,
  `vergi_dairesi` varchar(100) DEFAULT NULL,
  `ticaret_sicil_no` varchar(50) DEFAULT NULL,
  `mersis_no` varchar(32) DEFAULT NULL,
  `firma_eposta` varchar(100) DEFAULT NULL,
  `firma_telefon` varchar(20) DEFAULT NULL,
  `web_sitesi` varchar(255) DEFAULT NULL,
  `logo_yolu` varchar(255) DEFAULT NULL,
  `sektor` varchar(100) DEFAULT NULL,
  `calisan_sayisi` int unsigned DEFAULT 0,
  `aylik_seyahat_butcesi` decimal(12,2) DEFAULT NULL,
  `varsayilan_para_birimi` varchar(3) NOT NULL DEFAULT 'TRY',
  `acik_adres` text DEFAULT NULL,
  `sehir` varchar(100) DEFAULT NULL,
  `ilce` varchar(100) DEFAULT NULL,
  `posta_kodu` varchar(10) DEFAULT NULL,
  `yetkili_ad_soyad` varchar(100) DEFAULT NULL,
  `yetkili_eposta` varchar(100) DEFAULT NULL,
  `yetkili_telefon` varchar(20) DEFAULT NULL,
  `onay_durumu` enum('Beklemede','Onaylandı','Reddedildi','Askıda') NOT NULL DEFAULT 'Beklemede',
  `aktif_mi` tinyint(1) NOT NULL DEFAULT 1,
  `notlar` text DEFAULT NULL,
  `olusturulma_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `guncellenme_tarihi` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_firmalar_firma_kodu` (`firma_kodu`),
  UNIQUE KEY `uk_firmalar_vergi_no` (`vergi_no`),
  KEY `idx_firmalar_onay_aktif` (`onay_durumu`,`aktif_mi`),
  KEY `idx_firmalar_sehir_ilce` (`sehir`,`ilce`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;
