CREATE TABLE IF NOT EXISTS [firma_harcama_limitleri] (
  [id] bigint  NOT NULL IDENTITY(1,1),
  [firma_id] bigint  NOT NULL,
  [departman] varchar(100) DEFAULT NULL,
  [kullanici_id] bigint  DEFAULT NULL,
  [gecelik_limit] decimal(10,2) DEFAULT NULL,
  [rezervasyon_basi_limit] decimal(10,2) DEFAULT NULL,
  [aylik_limit] decimal(10,2) DEFAULT NULL,
  [onay_gereksinimi] BIT NOT NULL DEFAULT 0,
  [otomatik_onay_limit] decimal(10,2) DEFAULT NULL,
  [aktif_mi] BIT NOT NULL DEFAULT 1,
  [olusturulma_tarihi] DATETIME2 NULL DEFAULT GETDATE(),
  [guncellenme_tarihi] DATETIME2 NULL DEFAULT NULL,
  PRIMARY KEY ([id]),
  KEY [idx_firma_harcama_limitleri_firma] ([firma_id]),
  KEY [idx_firma_harcama_limitleri_kullanici] ([kullanici_id]),
  KEY [idx_firma_harcama_limitleri_departman] ([departman]),
  CONSTRAINT [fk_firma_harcama_limitleri_firma] FOREIGN KEY ([firma_id]) REFERENCES [firmalar] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_firma_harcama_limitleri_kullanici] FOREIGN KEY ([kullanici_id]) REFERENCES [users] ([id]) ON DELETE CASCADE
);
