CREATE TABLE IF NOT EXISTS [firma_ozel_fiyatlar] (
  [id] bigint  NOT NULL IDENTITY(1,1),
  [firma_id] bigint  NOT NULL,
  [otel_id] bigint  NOT NULL,
  [oda_tip_id] bigint  DEFAULT NULL,
  [minimum_oda_sayisi] tinyint  NOT NULL DEFAULT 1,
  [maksimum_oda_sayisi] tinyint  DEFAULT NULL,
  [indirim_orani] decimal(5,2) DEFAULT NULL,
  [ozel_fiyat] decimal(10,2) DEFAULT NULL,
  [gecerlilik_baslangic] date DEFAULT NULL,
  [gecerlilik_bitis] date DEFAULT NULL,
  [aktif_mi] BIT NOT NULL DEFAULT 1,
  [oncelik_sirasi] smallint  NOT NULL DEFAULT 0,
  [aciklama] varchar(255) DEFAULT NULL,
  [olusturulma_tarihi] DATETIME2 NULL DEFAULT GETDATE(),
  [guncellenme_tarihi] DATETIME2 NULL DEFAULT NULL,
  PRIMARY KEY ([id]),
  UNIQUE KEY [uk_firma_ozel_fiyatlar_benzersiz] ([firma_id],[otel_id],[oda_tip_id],[minimum_oda_sayisi]),
  KEY [idx_firma_ozel_fiyatlar_firma_aktif] ([firma_id],[aktif_mi]),
  KEY [idx_firma_ozel_fiyatlar_otel] ([otel_id]),
  CONSTRAINT [fk_firma_ozel_fiyatlar_firma] FOREIGN KEY ([firma_id]) REFERENCES [firmalar] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_firma_ozel_fiyatlar_otel] FOREIGN KEY ([otel_id]) REFERENCES [oteller] ([id]) ON DELETE CASCADE,
  CONSTRAINT [fk_firma_ozel_fiyatlar_oda] FOREIGN KEY ([oda_tip_id]) REFERENCES [oda_tipleri] ([id]) ON DELETE CASCADE
);
