CREATE TABLE IF NOT EXISTS `firma_ozel_fiyatlar` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `firma_id` bigint unsigned NOT NULL,
  `otel_id` bigint unsigned NOT NULL,
  `oda_tip_id` bigint unsigned DEFAULT NULL,
  `minimum_oda_sayisi` tinyint unsigned NOT NULL DEFAULT 1,
  `maksimum_oda_sayisi` tinyint unsigned DEFAULT NULL,
  `indirim_orani` decimal(5,2) DEFAULT NULL,
  `ozel_fiyat` decimal(10,2) DEFAULT NULL,
  `gecerlilik_baslangic` date DEFAULT NULL,
  `gecerlilik_bitis` date DEFAULT NULL,
  `aktif_mi` tinyint(1) NOT NULL DEFAULT 1,
  `oncelik_sirasi` smallint unsigned NOT NULL DEFAULT 0,
  `aciklama` varchar(255) DEFAULT NULL,
  `olusturulma_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `guncellenme_tarihi` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_firma_ozel_fiyatlar_benzersiz` (`firma_id`,`otel_id`,`oda_tip_id`,`minimum_oda_sayisi`),
  KEY `idx_firma_ozel_fiyatlar_firma_aktif` (`firma_id`,`aktif_mi`),
  KEY `idx_firma_ozel_fiyatlar_otel` (`otel_id`),
  CONSTRAINT `fk_firma_ozel_fiyatlar_firma` FOREIGN KEY (`firma_id`) REFERENCES `firmalar` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_firma_ozel_fiyatlar_otel` FOREIGN KEY (`otel_id`) REFERENCES `oteller` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_firma_ozel_fiyatlar_oda` FOREIGN KEY (`oda_tip_id`) REFERENCES `oda_tipleri` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;
