INSERT INTO rezervasyonlar
(
    rezervasyon_no,
    otel_id,
    oda_tip_id,
    kullanici_id,
    firma_id,
    firma_calisan_id,
    misafir_ad_soyad,
    misafir_eposta,
    misafir_telefon,
    giris_tarihi,
    cikis_tarihi,
    yetiskin_sayisi,
    oda_sayisi,
    gecelik_fiyat,
    toplam_oda_tutari,
    indirim_tutari,
    toplam_tasarruf,
    toplam_tutar,
    komisyon_orani,
    para_birimi,
    odeme_durumu,
    durum,
    firma_onay_durumu,
    kaynak,
    olusturulma_tarihi
)
SELECT
    'FRM-RES-1001',
    20,
    16,
    47,
    1,
    47,
    'Ahmet Yılmaz',
    'ahmet.yilmaz@abcteknoloji.com',
    '05320000001',
    '2026-04-18',
    '2026-04-20',
    2,
    2,
    3400.00,
    13600.00,
    1700.00,
    1700.00,
    11900.00,
    12.00,
    'TRY',
    'Tamamlandı',
    'Onaylandı',
    'Onaylandı',
    'Kurumsal',
    SYSDATETIME()
WHERE NOT EXISTS (SELECT 1 FROM rezervasyonlar WHERE rezervasyon_no = 'FRM-RES-1001');

INSERT INTO rezervasyonlar
(
    rezervasyon_no,
    otel_id,
    oda_tip_id,
    kullanici_id,
    firma_id,
    firma_calisan_id,
    misafir_ad_soyad,
    misafir_eposta,
    misafir_telefon,
    giris_tarihi,
    cikis_tarihi,
    yetiskin_sayisi,
    oda_sayisi,
    gecelik_fiyat,
    toplam_oda_tutari,
    indirim_tutari,
    toplam_tasarruf,
    toplam_tutar,
    komisyon_orani,
    para_birimi,
    odeme_durumu,
    durum,
    firma_onay_durumu,
    kaynak,
    olusturulma_tarihi
)
SELECT
    'FRM-RES-1002',
    25,
    21,
    48,
    1,
    48,
    'Şeyma Kaya',
    'seyma.kaya@abcteknoloji.com',
    '05320000002',
    '2026-04-24',
    '2026-04-27',
    2,
    3,
    3900.00,
    35100.00,
    3000.00,
    3000.00,
    32100.00,
    12.00,
    'TRY',
    'Ön Ödeme Alındı',
    'Onay Bekliyor',
    'Beklemede',
    'Kurumsal',
    SYSDATETIME()
WHERE NOT EXISTS (SELECT 1 FROM rezervasyonlar WHERE rezervasyon_no = 'FRM-RES-1002');

INSERT INTO rezervasyonlar
(
    rezervasyon_no,
    otel_id,
    oda_tip_id,
    kullanici_id,
    firma_id,
    firma_calisan_id,
    misafir_ad_soyad,
    misafir_eposta,
    misafir_telefon,
    giris_tarihi,
    cikis_tarihi,
    yetiskin_sayisi,
    oda_sayisi,
    gecelik_fiyat,
    toplam_oda_tutari,
    indirim_tutari,
    toplam_tasarruf,
    toplam_tutar,
    komisyon_orani,
    para_birimi,
    odeme_durumu,
    durum,
    firma_onay_durumu,
    kaynak,
    olusturulma_tarihi
)
SELECT
    'FRM-RES-1003',
    29,
    25,
    49,
    1,
    49,
    'Emre Demir',
    'emre.demir@abcteknoloji.com',
    '05320000003',
    '2026-04-16',
    '2026-04-18',
    1,
    1,
    3150.00,
    6300.00,
    500.00,
    500.00,
    5800.00,
    12.00,
    'TRY',
    'Tamamlandı',
    'Onaylandı',
    'Onay Gerekmiyor',
    'Kurumsal',
    SYSDATETIME()
WHERE NOT EXISTS (SELECT 1 FROM rezervasyonlar WHERE rezervasyon_no = 'FRM-RES-1003');

INSERT INTO faturalar
(
    fatura_no,
    fatura_tarihi,
    fatura_turu,
    rezervasyon_id,
    otel_id,
    kullanici_id,
    firma_id,
    fatura_kesen,
    fatura_kesen_unvan,
    fatura_kesen_vergi_dairesi,
    fatura_kesen_vergi_no,
    fatura_kesen_adres,
    fatura_alici_unvan,
    fatura_alici_vergi_dairesi,
    fatura_alici_vergi_no,
    fatura_alici_adres,
    fatura_alici_eposta,
    ara_toplam,
    kdv_tutari,
    genel_toplam,
    para_birimi,
    fatura_durumu,
    olusturulma_tarihi
)
SELECT
    'FRM-FAT-1001',
    '2026-04-11',
    'e-Fatura',
    (SELECT TOP (1) id FROM rezervasyonlar WHERE rezervasyon_no = 'FRM-RES-1001'),
    20,
    47,
    1,
    'Platform',
    'Otelturizm Teknoloji A.Ş.',
    'Üsküdar',
    '1234567890',
    'İstanbul Teknoloji Merkezi',
    'ABC Teknoloji A.Ş.',
    'Maslak',
    '1234567890',
    'Maslak Mahallesi, İstanbul',
    'finans@abcteknoloji.com',
    9916.67,
    1983.33,
    11900.00,
    'TRY',
    'Kesildi',
    SYSDATETIME()
WHERE NOT EXISTS (SELECT 1 FROM faturalar WHERE fatura_no = 'FRM-FAT-1001');

INSERT INTO faturalar
(
    fatura_no,
    fatura_tarihi,
    fatura_turu,
    rezervasyon_id,
    otel_id,
    kullanici_id,
    firma_id,
    fatura_kesen,
    fatura_kesen_unvan,
    fatura_kesen_vergi_dairesi,
    fatura_kesen_vergi_no,
    fatura_kesen_adres,
    fatura_alici_unvan,
    fatura_alici_vergi_dairesi,
    fatura_alici_vergi_no,
    fatura_alici_adres,
    fatura_alici_eposta,
    ara_toplam,
    kdv_tutari,
    genel_toplam,
    para_birimi,
    fatura_durumu,
    olusturulma_tarihi
)
SELECT
    'FRM-FAT-1002',
    '2026-04-11',
    'Proforma',
    (SELECT TOP (1) id FROM rezervasyonlar WHERE rezervasyon_no = 'FRM-RES-1002'),
    25,
    48,
    1,
    'Platform',
    'Otelturizm Teknoloji A.Ş.',
    'Üsküdar',
    '1234567890',
    'İstanbul Teknoloji Merkezi',
    'ABC Teknoloji A.Ş.',
    'Maslak',
    '1234567890',
    'Maslak Mahallesi, İstanbul',
    'finans@abcteknoloji.com',
    26750.00,
    5350.00,
    32100.00,
    'TRY',
    'Kesildi',
    SYSDATETIME()
WHERE NOT EXISTS (SELECT 1 FROM faturalar WHERE fatura_no = 'FRM-FAT-1002');
