CREATE TABLE IF NOT EXISTS kampanya_oteller (
    id BIGINT  NOT NULL IDENTITY(1,1) PRIMARY KEY,
    kampanya_id BIGINT  NOT NULL,
    otel_id BIGINT  NOT NULL,
    partner_id BIGINT  NULL,
    katilim_durumu ENUM('Beklemede', 'Aktif', 'Pasif', 'Reddedildi', 'Sona Erdi') NOT NULL DEFAULT 'Beklemede',
    katilim_kaynagi ENUM('Admin', 'Partner', 'Otomatik') NOT NULL DEFAULT 'Partner',
    baslangic_tarihi DATETIME2 NOT NULL,
    bitis_tarihi DATETIME2 NOT NULL,
    ozel_indirim_orani DECIMAL(5,2) NULL,
    ozel_indirim_tutari DECIMAL(10,2) NULL,
    ozel_kampanyali_fiyat DECIMAL(10,2) NULL,
    kampanya_etiketi VARCHAR(120) NULL,
    landing_url VARCHAR(500) NULL,
    partner_notu NVARCHAR(MAX) NULL,
    one_cikan BIT NOT NULL DEFAULT 0,
    siralama INT NOT NULL DEFAULT 0,
    admin_onay_tarihi DATETIME2 NULL,
    partner_onay_tarihi DATETIME2 NULL,
    olusturan_kullanici_id BIGINT  NULL,
    guncelleyen_kullanici_id BIGINT  NULL,
    olusturulma_tarihi DATETIME2 NOT NULL DEFAULT GETDATE(),
    guncellenme_tarihi DATETIME2 NULL DEFAULT NULL,
    UNIQUE KEY uk_kampanya_otel (kampanya_id, otel_id),
    KEY idx_kampanya_oteller_aktif (katilim_durumu, baslangic_tarihi, bitis_tarihi),
    KEY idx_kampanya_oteller_partner (partner_id, katilim_durumu),
    KEY idx_kampanya_oteller_otel (otel_id, katilim_durumu),
    KEY idx_kampanya_oteller_vitrin (one_cikan, siralama),
    CONSTRAINT fk_kampanya_oteller_kampanya FOREIGN KEY (kampanya_id) REFERENCES kampanyalar(id) ON DELETE CASCADE,
    CONSTRAINT fk_kampanya_oteller_otel FOREIGN KEY (otel_id) REFERENCES oteller(id) ON DELETE CASCADE,
    CONSTRAINT fk_kampanya_oteller_partner FOREIGN KEY (partner_id) REFERENCES partner_detaylari(id) ON DELETE SET NULL,
    CONSTRAINT fk_kampanya_oteller_olusturan FOREIGN KEY (olusturan_kullanici_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_kampanya_oteller_guncelleyen FOREIGN KEY (guncelleyen_kullanici_id) REFERENCES users(id) ON DELETE SET NULL
);
