CREATE TABLE IF NOT EXISTS email_services (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    servis_kodu VARCHAR(50) NOT NULL,
    servis_adi VARCHAR(100) NOT NULL,
    saglayici ENUM('SMTP','SendGrid','Amazon SES','Mailgun','Postmark','Custom') NOT NULL DEFAULT 'SMTP',
    varsayilan_mi TINYINT(1) NOT NULL DEFAULT 0,
    aktif_mi TINYINT(1) NOT NULL DEFAULT 1,
    gonderen_ad VARCHAR(120) NOT NULL,
    gonderen_eposta VARCHAR(150) NOT NULL,
    yanitla_eposta VARCHAR(150) NULL,
    smtp_host VARCHAR(255) NULL,
    smtp_port SMALLINT UNSIGNED NOT NULL DEFAULT 587,
    smtp_kullanici_adi VARCHAR(255) NULL,
    smtp_sifre TEXT NULL,
    sifre_sifrelenmis_mi TINYINT(1) NOT NULL DEFAULT 0,
    guvenlik_tipi ENUM('None','SSL','TLS','STARTTLS') NOT NULL DEFAULT 'TLS',
    api_base_url VARCHAR(255) NULL,
    api_anahtari TEXT NULL,
    api_secret TEXT NULL,
    baglanti_zaman_asimi_saniye SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    gonderim_limiti_dakika INT UNSIGNED NOT NULL DEFAULT 60,
    gonderim_limiti_saat INT UNSIGNED NOT NULL DEFAULT 1000,
    gonderim_limiti_gun INT UNSIGNED NOT NULL DEFAULT 5000,
    test_modu TINYINT(1) NOT NULL DEFAULT 1,
    hata_esigi SMALLINT UNSIGNED NOT NULL DEFAULT 10,
    son_basarili_test_tarihi TIMESTAMP NULL,
    son_hata_tarihi TIMESTAMP NULL,
    son_hata_mesaji VARCHAR(500) NULL,
    metadata JSON NULL,
    olusturulma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    guncellenme_tarihi TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_email_services_kod (servis_kodu),
    INDEX idx_email_services_aktif (aktif_mi),
    INDEX idx_email_services_varsayilan (varsayilan_mi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
