CREATE TABLE IF NOT EXISTS email_services (
    id SMALLINT IDENTITY(1,1) NOT NULL,
    servis_kodu VARCHAR(50) NOT NULL,
    servis_adi VARCHAR(100) NOT NULL,
    saglayici ENUM('SMTP','SendGrid','Amazon SES','Mailgun','Postmark','Custom') NOT NULL DEFAULT 'SMTP',
    varsayilan_mi BIT NOT NULL DEFAULT 0,
    aktif_mi BIT NOT NULL DEFAULT 1,
    gonderen_ad VARCHAR(120) NOT NULL,
    gonderen_eposta VARCHAR(150) NOT NULL,
    yanitla_eposta VARCHAR(150) NULL,
    smtp_host VARCHAR(255) NULL,
    smtp_port SMALLINT  NOT NULL DEFAULT 587,
    smtp_kullanici_adi VARCHAR(255) NULL,
    smtp_sifre NVARCHAR(MAX) NULL,
    sifre_sifrelenmis_mi BIT NOT NULL DEFAULT 0,
    guvenlik_tipi ENUM('None','SSL','TLS','STARTTLS') NOT NULL DEFAULT 'TLS',
    api_base_url VARCHAR(255) NULL,
    api_anahtari NVARCHAR(MAX) NULL,
    api_secret NVARCHAR(MAX) NULL,
    baglanti_zaman_asimi_saniye SMALLINT  NOT NULL DEFAULT 30,
    gonderim_limiti_dakika INT  NOT NULL DEFAULT 60,
    gonderim_limiti_saat INT  NOT NULL DEFAULT 1000,
    gonderim_limiti_gun INT  NOT NULL DEFAULT 5000,
    test_modu BIT NOT NULL DEFAULT 1,
    hata_esigi SMALLINT  NOT NULL DEFAULT 10,
    son_basarili_test_tarihi DATETIME2 NULL,
    son_hata_tarihi DATETIME2 NULL,
    son_hata_mesaji VARCHAR(500) NULL,
    metadata JSON NULL,
    olusturulma_tarihi DATETIME2 NOT NULL DEFAULT GETDATE(),
    guncellenme_tarihi DATETIME2 NULL DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_email_services_kod (servis_kodu),
    INDEX idx_email_services_aktif (aktif_mi),
    INDEX idx_email_services_varsayilan (varsayilan_mi)
);
