CREATE TABLE IF NOT EXISTS rezervasyon_taslaklari (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    taslak_kodu VARCHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    session_anahtari VARCHAR(100) NULL,
    kaynak ENUM('Public','Sales') NOT NULL DEFAULT 'Public',
    durum ENUM('Taslak','Profil Eksik','Giris Bekliyor','Tamamlandi','Iptal','Suresi Doldu') NOT NULL DEFAULT 'Taslak',
    otel_id BIGINT UNSIGNED NOT NULL,
    oda_tip_id BIGINT UNSIGNED NULL,
    tamamlanan_rezervasyon_id BIGINT UNSIGNED NULL,
    misafir_ad_soyad VARCHAR(120) NULL,
    misafir_eposta VARCHAR(120) NULL,
    misafir_telefon VARCHAR(20) NULL,
    misafir_sehir VARCHAR(100) NULL,
    misafir_ilce VARCHAR(100) NULL,
    misafir_mahalle VARCHAR(120) NULL,
    misafir_adres TEXT NULL,
    giris_tarihi DATE NOT NULL,
    cikis_tarihi DATE NOT NULL,
    yetiskin_sayisi TINYINT UNSIGNED NOT NULL DEFAULT 2,
    cocuk_sayisi TINYINT UNSIGNED NOT NULL DEFAULT 0,
    oda_sayisi TINYINT UNSIGNED NOT NULL DEFAULT 1,
    gecelik_fiyat DECIMAL(10,2) NULL,
    vergi_tutari DECIMAL(10,2) NULL,
    toplam_tutar DECIMAL(10,2) NULL,
    para_birimi VARCHAR(3) NOT NULL DEFAULT 'TRY',
    donus_url VARCHAR(500) NULL,
    profil_tamamlanma_url VARCHAR(500) NULL,
    notlar TEXT NULL,
    metadata JSON NULL,
    son_aktivite_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    son_bildirim_tarihi TIMESTAMP NULL,
    gecerlilik_tarihi TIMESTAMP NULL,
    olusturulma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    guncellenme_tarihi TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rezervasyon_taslaklari_kod (taslak_kodu),
    INDEX idx_rezervasyon_taslaklari_user (user_id, durum),
    INDEX idx_rezervasyon_taslaklari_session (session_anahtari, durum),
    INDEX idx_rezervasyon_taslaklari_otel (otel_id),
    INDEX idx_rezervasyon_taslaklari_gecerlilik (gecerlilik_tarihi),
    CONSTRAINT fk_rezervasyon_taslagi_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_rezervasyon_taslagi_otel FOREIGN KEY (otel_id) REFERENCES oteller(id) ON DELETE CASCADE,
    CONSTRAINT fk_rezervasyon_taslagi_oda FOREIGN KEY (oda_tip_id) REFERENCES oda_tipleri(id) ON DELETE SET NULL,
    CONSTRAINT fk_rezervasyon_taslagi_rezervasyon FOREIGN KEY (tamamlanan_rezervasyon_id) REFERENCES rezervasyonlar(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
