CREATE TABLE IF NOT EXISTS [guvenli_dosya_varliklari] (
  [id] bigint  NOT NULL IDENTITY(1,1),
  [baglam_tablo] varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  [baglam_kayit_id] bigint  NOT NULL,
  [sahibi_kullanici_id] bigint  DEFAULT NULL,
  [sahibi_firma_id] bigint  DEFAULT NULL,
  [kategori] varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'message',
  [gorunurluk_kapsami] enum('private','token-only','firma-only','user-only') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'token-only',
  [orijinal_dosya_adi] varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  [depolanan_dosya_adi] varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  [depolama_yolu] varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  [mime_tipi] varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  [dosya_uzantisi] varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  [dosya_boyutu] bigint  NOT NULL DEFAULT '0',
  [sha256_ozeti] char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  [gorsel_mi] BIT NOT NULL DEFAULT '0',
  [aktif_mi] BIT NOT NULL DEFAULT '1',
  [silinme_tarihi] DATETIME2 NULL DEFAULT NULL,
  [olusturulma_tarihi] DATETIME2 NOT NULL DEFAULT GETDATE(),
  PRIMARY KEY ([id]),
  KEY [idx_guvenli_dosya_baglam] ([baglam_tablo],[baglam_kayit_id]),
  KEY [idx_guvenli_dosya_sahibi_kullanici] ([sahibi_kullanici_id]),
  KEY [idx_guvenli_dosya_sahibi_firma] ([sahibi_firma_id]),
  CONSTRAINT [fk_guvenli_dosya_kullanici] FOREIGN KEY ([sahibi_kullanici_id]) REFERENCES [users] ([id]) ON DELETE SET NULL,
  CONSTRAINT [fk_guvenli_dosya_firma] FOREIGN KEY ([sahibi_firma_id]) REFERENCES [firmalar] ([id]) ON DELETE SET NULL
);
