CREATE TABLE IF NOT EXISTS ulkeler (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ulke_adi VARCHAR(150) NOT NULL,
    iso2_kodu CHAR(2) NULL,
    iso3_kodu CHAR(3) NULL,
    telefon_kodu VARCHAR(10) NULL,
    para_birimi_kodu VARCHAR(10) NULL,
    varsayilan_ulke TINYINT(1) NOT NULL DEFAULT 0,
    aktif_mi TINYINT(1) NOT NULL DEFAULT 1,
    olusturulma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    guncellenme_tarihi TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ulkeler_iso2 (iso2_kodu),
    UNIQUE KEY uk_ulkeler_iso3 (iso3_kodu),
    KEY idx_ulkeler_aktif (aktif_mi, ulke_adi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ulkeler (ulke_adi, iso2_kodu, iso3_kodu, varsayilan_ulke, aktif_mi)
VALUES
('Andorra', 'AD', 'AND', 0, 1),
('United Arab Emirates', 'AE', 'ARE', 0, 1),
('Afghanistan', 'AF', 'AFG', 0, 1),
('Antigua & Barbuda', 'AG', 'ATG', 0, 1),
('Albania', 'AL', 'ALB', 0, 1),
('Armenia', 'AM', 'ARM', 0, 1),
('Angola', 'AO', 'AGO', 0, 1),
('Argentina', 'AR', 'ARG', 0, 1),
('American Samoa', 'AS', 'ASM', 0, 1),
('Austria', 'AT', 'AUT', 0, 1),
('Australia', 'AU', 'AUS', 0, 1),
('Aruba', 'AW', 'ABW', 0, 1),
('Åland Islands', 'AX', 'ALA', 0, 1),
('Azerbaijan', 'AZ', 'AZE', 0, 1),
('Barbados', 'BB', 'BRB', 0, 1),
('Bangladesh', 'BD', 'BGD', 0, 1),
('Belgium', 'BE', 'BEL', 0, 1),
('Burkina Faso', 'BF', 'BFA', 0, 1),
('Bulgaria', 'BG', 'BGR', 0, 1),
('Bahrain', 'BH', 'BHR', 0, 1),
('Benin', 'BJ', 'BEN', 0, 1),
('St. Barthélemy', 'BL', 'BLM', 0, 1),
('Bermuda', 'BM', 'BMU', 0, 1),
('Brunei', 'BN', 'BRN', 0, 1),
('Bolivia', 'BO', 'BOL', 0, 1),
('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 0, 1),
('Brazil', 'BR', 'BRA', 0, 1),
('Bahamas', 'BS', 'BHS', 0, 1),
('Bhutan', 'BT', 'BTN', 0, 1),
('Botswana', 'BW', 'BWA', 0, 1),
('Belarus', 'BY', 'BLR', 0, 1),
('Belize', 'BZ', 'BLZ', 0, 1),
('Canada', 'CA', 'CAN', 0, 1),
('Cocos (Keeling) Islands', 'CC', 'CCK', 0, 1),
('Congo (DRC)', 'CD', 'COD', 0, 1),
('Central African Republic', 'CF', 'CAF', 0, 1),
('Congo', 'CG', 'COG', 0, 1),
('Switzerland', 'CH', 'CHE', 0, 1),
('Cook Islands', 'CK', 'COK', 0, 1),
('Chile', 'CL', 'CHL', 0, 1),
('Cameroon', 'CM', 'CMR', 0, 1),
('China', 'CN', 'CHN', 0, 1),
('Colombia', 'CO', 'COL', 0, 1),
('Cuba', 'CU', 'CUB', 0, 1),
('Cabo Verde', 'CV', 'CPV', 0, 1),
('Curaçao', 'CW', 'CUW', 0, 1),
('Christmas Island', 'CX', 'CXR', 0, 1),
('Cyprus', 'CY', 'CYP', 0, 1),
('Czechia', 'CZ', 'CZE', 0, 1),
('Germany', 'DE', 'DEU', 0, 1),
('Denmark', 'DK', 'DNK', 0, 1),
('Dominica', 'DM', 'DMA', 0, 1),
('Dominican Republic', 'DO', 'DOM', 0, 1),
('Algeria', 'DZ', 'DZA', 0, 1),
('Ecuador', 'EC', 'ECU', 0, 1),
('Estonia', 'EE', 'EST', 0, 1),
('Egypt', 'EG', 'EGY', 0, 1),
('Spain', 'ES', 'ESP', 0, 1),
('Ethiopia', 'ET', 'ETH', 0, 1),
('Falkland Islands', 'FK', 'FLK', 0, 1),
('Micronesia', 'FM', 'FSM', 0, 1),
('Faroe Islands', 'FO', 'FRO', 0, 1),
('France', 'FR', 'FRA', 0, 1),
('Gabon', 'GA', 'GAB', 0, 1),
('United Kingdom', 'GB', 'GBR', 0, 1),
('Grenada', 'GD', 'GRD', 0, 1),
('Georgia', 'GE', 'GEO', 0, 1),
('French Guiana', 'GF', 'GUF', 0, 1),
('Guernsey', 'GG', 'GGY', 0, 1),
('Ghana', 'GH', 'GHA', 0, 1),
('Greenland', 'GL', 'GRL', 0, 1),
('Gambia', 'GM', 'GMB', 0, 1),
('Guadeloupe', 'GP', 'GLP', 0, 1),
('Equatorial Guinea', 'GQ', 'GNQ', 0, 1),
('Greece', 'GR', 'GRC', 0, 1),
('Guatemala', 'GT', 'GTM', 0, 1),
('Guam', 'GU', 'GUM', 0, 1),
('Guinea-Bissau', 'GW', 'GNB', 0, 1),
('Guyana', 'GY', 'GUY', 0, 1),
('Hong Kong SAR', 'HK', 'HKG', 0, 1),
('Honduras', 'HN', 'HND', 0, 1),
('Croatia', 'HR', 'HRV', 0, 1),
('Hungary', 'HU', 'HUN', 0, 1),
('Jersey', 'JE', 'JEY', 0, 1),
('Jamaica', 'JM', 'JAM', 0, 1),
('Jordan', 'JO', 'JOR', 0, 1),
('Japan', 'JP', 'JPN', 0, 1),
('Kenya', 'KE', 'KEN', 0, 1),
('Kyrgyzstan', 'KG', 'KGZ', 0, 1),
('Cambodia', 'KH', 'KHM', 0, 1),
('Comoros', 'KM', 'COM', 0, 1),
('St. Kitts & Nevis', 'KN', 'KNA', 0, 1),
('North Korea', 'KP', 'PRK', 0, 1),
('Korea', 'KR', 'KOR', 0, 1),
('Kuwait', 'KW', 'KWT', 0, 1),
('Cayman Islands', 'KY', 'CYM', 0, 1),
('Kazakhstan', 'KZ', 'KAZ', 0, 1),
('Laos', 'LA', 'LAO', 0, 1),
('Lebanon', 'LB', 'LBN', 0, 1),
('St. Lucia', 'LC', 'LCA', 0, 1),
('Sri Lanka', 'LK', 'LKA', 0, 1),
('Liberia', 'LR', 'LBR', 0, 1),
('Lesotho', 'LS', 'LSO', 0, 1),
('Lithuania', 'LT', 'LTU', 0, 1),
('Luxembourg', 'LU', 'LUX', 0, 1),
('Latvia', 'LV', 'LVA', 0, 1),
('Libya', 'LY', 'LBY', 0, 1),
('Morocco', 'MA', 'MAR', 0, 1),
('Monaco', 'MC', 'MCO', 0, 1),
('Moldova', 'MD', 'MDA', 0, 1),
('Montenegro', 'ME', 'MNE', 0, 1),
('St. Martin', 'MF', 'MAF', 0, 1),
('Madagascar', 'MG', 'MDG', 0, 1),
('Marshall Islands', 'MH', 'MHL', 0, 1),
('North Macedonia', 'MK', 'MKD', 0, 1),
('Myanmar', 'MM', 'MMR', 0, 1),
('Mongolia', 'MN', 'MNG', 0, 1),
('Macao SAR', 'MO', 'MAC', 0, 1),
('Northern Mariana Islands', 'MP', 'MNP', 0, 1),
('Martinique', 'MQ', 'MTQ', 0, 1),
('Mauritania', 'MR', 'MRT', 0, 1),
('Montserrat', 'MS', 'MSR', 0, 1),
('Malta', 'MT', 'MLT', 0, 1),
('Mauritius', 'MU', 'MUS', 0, 1),
('Maldives', 'MV', 'MDV', 0, 1),
('Mexico', 'MX', 'MEX', 0, 1),
('Malaysia', 'MY', 'MYS', 0, 1),
('Mozambique', 'MZ', 'MOZ', 0, 1),
('Namibia', 'NA', 'NAM', 0, 1),
('New Caledonia', 'NC', 'NCL', 0, 1),
('Niger', 'NE', 'NER', 0, 1),
('Norfolk Island', 'NF', 'NFK', 0, 1),
('Nigeria', 'NG', 'NGA', 0, 1),
('Netherlands', 'NL', 'NLD', 0, 1),
('Norway', 'NO', 'NOR', 0, 1),
('Nepal', 'NP', 'NPL', 0, 1),
('Nauru', 'NR', 'NRU', 0, 1),
('New Zealand', 'NZ', 'NZL', 0, 1),
('Oman', 'OM', 'OMN', 0, 1),
('Panama', 'PA', 'PAN', 0, 1),
('Peru', 'PE', 'PER', 0, 1),
('French Polynesia', 'PF', 'PYF', 0, 1),
('Papua New Guinea', 'PG', 'PNG', 0, 1),
('Philippines', 'PH', 'PHL', 0, 1),
('Pakistan', 'PK', 'PAK', 0, 1),
('Poland', 'PL', 'POL', 0, 1),
('St. Pierre & Miquelon', 'PM', 'SPM', 0, 1),
('Pitcairn Islands', 'PN', 'PCN', 0, 1),
('Palestinian Authority', 'PS', 'PSE', 0, 1),
('Portugal', 'PT', 'PRT', 0, 1),
('Palau', 'PW', 'PLW', 0, 1),
('Paraguay', 'PY', 'PRY', 0, 1),
('Qatar', 'QA', 'QAT', 0, 1),
('Réunion', 'RE', 'REU', 0, 1),
('Romania', 'RO', 'ROU', 0, 1),
('Serbia', 'RS', 'SRB', 0, 1),
('Russia', 'RU', 'RUS', 0, 1),
('Rwanda', 'RW', 'RWA', 0, 1),
('Saudi Arabia', 'SA', 'SAU', 0, 1),
('Solomon Islands', 'SB', 'SLB', 0, 1),
('Seychelles', 'SC', 'SYC', 0, 1),
('Sudan', 'SD', 'SDN', 0, 1),
('Sweden', 'SE', 'SWE', 0, 1),
('Singapore', 'SG', 'SGP', 0, 1),
('St Helena, Ascension, Tristan da Cunha', 'SH', 'SHN', 0, 1),
('Svalbard & Jan Mayen', 'SJ', 'SJM', 0, 1),
('Slovakia', 'SK', 'SVK', 0, 1),
('Sierra Leone', 'SL', 'SLE', 0, 1),
('San Marino', 'SM', 'SMR', 0, 1),
('Senegal', 'SN', 'SEN', 0, 1),
('Somalia', 'SO', 'SOM', 0, 1),
('Suriname', 'SR', 'SUR', 0, 1),
('South Sudan', 'SS', 'SSD', 0, 1),
('São Tomé & Príncipe', 'ST', 'STP', 0, 1),
('El Salvador', 'SV', 'SLV', 0, 1),
('Sint Maarten', 'SX', 'SXM', 0, 1),
('Syria', 'SY', 'SYR', 0, 1),
('Eswatini', 'SZ', 'SWZ', 0, 1),
('Turks & Caicos Islands', 'TC', 'TCA', 0, 1),
('Chad', 'TD', 'TCD', 0, 1),
('Togo', 'TG', 'TGO', 0, 1),
('Thailand', 'TH', 'THA', 0, 1),
('Tajikistan', 'TJ', 'TJK', 0, 1),
('Tokelau', 'TK', 'TKL', 0, 1),
('Timor-Leste', 'TL', 'TLS', 0, 1),
('Turkmenistan', 'TM', 'TKM', 0, 1),
('Tunisia', 'TN', 'TUN', 0, 1),
('Tonga', 'TO', 'TON', 0, 1),
('Türkiye', 'TR', 'TUR', 1, 1),
('Trinidad & Tobago', 'TT', 'TTO', 0, 1),
('Tuvalu', 'TV', 'TUV', 0, 1),
('Taiwan', 'TW', 'TWN', 0, 1),
('Tanzania', 'TZ', 'TZA', 0, 1),
('Ukraine', 'UA', 'UKR', 0, 1),
('Uganda', 'UG', 'UGA', 0, 1),
('United States', 'US', 'USA', 0, 1),
('Uruguay', 'UY', 'URY', 0, 1),
('Uzbekistan', 'UZ', 'UZB', 0, 1),
('Vatican City', 'VA', 'VAT', 0, 1),
('St. Vincent & Grenadines', 'VC', 'VCT', 0, 1),
('Venezuela', 'VE', 'VEN', 0, 1),
('British Virgin Islands', 'VG', 'VGB', 0, 1),
('Vietnam', 'VN', 'VNM', 0, 1),
('Vanuatu', 'VU', 'VUT', 0, 1),
('Wallis & Futuna', 'WF', 'WLF', 0, 1),
('Samoa', 'WS', 'WSM', 0, 1),
('Kosovo', 'XK', 'XKS', 0, 1),
('Yemen', 'YE', 'YEM', 0, 1),
('Mayotte', 'YT', 'MYT', 0, 1),
('South Africa', 'ZA', 'ZAF', 0, 1),
('Zambia', 'ZM', 'ZMB', 0, 1),
('Zimbabwe', 'ZW', 'ZWE', 0, 1);
