CREATE TABLE IF NOT EXISTS email_dogrulama_tokenlari (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    kullanici_id BIGINT UNSIGNED NOT NULL,
    eposta VARCHAR(100) NOT NULL,
    token VARCHAR(96) NOT NULL,
    dogrulama_kodu VARCHAR(8) NOT NULL,
    kullanildi_mi TINYINT(1) NOT NULL DEFAULT 0,
    deneme_sayisi SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    maksimum_deneme SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    ip_adresi VARCHAR(45) NULL,
    user_agent VARCHAR(500) NULL,
    gecerlilik_suresi TIMESTAMP NOT NULL,
    kullanilma_tarihi TIMESTAMP NULL DEFAULT NULL,
    olusturulma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_email_verify_token (token),
    UNIQUE KEY uk_email_verify_code_scope (kullanici_id, dogrulama_kodu, kullanildi_mi),
    KEY idx_email_verify_user_status (kullanici_id, kullanildi_mi, gecerlilik_suresi),
    CONSTRAINT fk_email_verify_user FOREIGN KEY (kullanici_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
