IF OBJECT_ID(N'dbo.KULLANICI_OTURUM_ISTATISTIKLERI', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH(N'dbo.KULLANICI_OTURUM_ISTATISTIKLERI', N'SON_KULLANICI_ARACISI_HASH') IS NULL
    BEGIN
        ALTER TABLE [dbo].[KULLANICI_OTURUM_ISTATISTIKLERI]
        ADD [SON_KULLANICI_ARACISI_HASH] nchar(64) NULL;
    END;

    IF COL_LENGTH(N'dbo.KULLANICI_OTURUM_ISTATISTIKLERI', N'SON_USER_AGENT_HASH') IS NOT NULL
    BEGIN
        EXEC sp_executesql N'
            UPDATE [dbo].[KULLANICI_OTURUM_ISTATISTIKLERI]
            SET [SON_KULLANICI_ARACISI_HASH] = COALESCE([SON_KULLANICI_ARACISI_HASH], [SON_USER_AGENT_HASH])
            WHERE [SON_KULLANICI_ARACISI_HASH] IS NULL
              AND [SON_USER_AGENT_HASH] IS NOT NULL;';
    END;
END;
